import type { RecipeCatalogItem } from "./recipesDatabase";

/** Cină 12+ luni — lot suplimentar */
export const CINA_12PLUS_DINNER_RECIPES: RecipeCatalogItem[] = [
  {
    id: "ciorba-legume-12",
    name: "Ciorbă de legume cu tăiței",
    emoji: "🍲",
    mealType: "cina",
    time: "35 min",
    age: "12+ luni",
    difficulty: "Mediu",
    servings: "4-6",
    ingredients: [
      "1 morcov",
      "1 păstârnac",
      "½ țelină",
      "1 cartof",
      "½ cană tăiței de casă",
      "1 roșie",
      "1 lingură ulei",
      "1 vârf leuștean",
    ],
    steps: [
      "Taie toate legumele în cuburi mici.",
      "Călește morcovul, păstârnacul și țelina în ulei 3 minute.",
      "Adaugă 1.5L apă. Fierbe 20 minute.",
      "Adaugă cartoful și tăițeii. Fierbe 10 minute.",
      "Adaugă roșia tocată și leușteanul.",
      "Lasă să se răcească. Servește călduță.",
    ],
    allergens: ["Gluten"],
    relatedFoods: ["morcov", "cartof", "pastarnac", "rosii"],
    storage: "Se păstrează la frigider 3 zile.",
  },
  {
    id: "piure-cartofi-peste-12",
    name: "Piure de cartofi cu pește",
    emoji: "🐟",
    mealType: "cina",
    time: "30 min",
    age: "12+ luni",
    difficulty: "Mediu",
    servings: "2-3",
    ingredients: [
      "3 cartofi medii",
      "200g file de somon sau cod",
      "2 linguri unt",
      "¼ cană lapte",
      "1 lămâie (sucul)",
      "1 vârf mărar",
    ],
    steps: [
      "Fierbe cartofii 20 minute. Pasează cu unt și lapte.",
      "Pune peștele în hârtie de copt cu suc de lămâie.",
      "Coace la 180°C 15-18 minute.",
      "Sfărâmă peștele cu furculița (verifică oasele!).",
      "Pune piureul în castron, peștele deasupra.",
      "Presară mărar.",
    ],
    allergens: ["Lactoză", "Pește"],
    relatedFoods: ["cartof", "somon", "ulei-masline"],
    storage: "Se păstrează la frigider 2 zile.",
  },
  {
    id: "chiftele-curcan-12",
    name: "Chiftele de curcan la cuptor",
    emoji: "🍖",
    mealType: "cina",
    time: "30 min",
    age: "12+ luni",
    difficulty: "Mediu",
    servings: "10-12 chiftele",
    ingredients: [
      "300g carne tocată de curcan",
      "1 ou",
      "2 linguri fulgi de ovăz",
      "1 morcov mic ras",
      "1 vârf coriandru",
      "1 linguriță ulei de măsline",
    ],
    steps: [
      "Preîncălzește cuptorul la 190°C.",
      "Amestecă toate ingredientele.",
      "Formează chiftele de mărimea unei nuci.",
      "Pune pe tavă unsă cu ulei.",
      "Coace 20 minute, întoarce la jumătate.",
      "Verifică că sunt complet gătite.",
    ],
    allergens: ["Ou", "Gluten"],
    relatedFoods: ["curcan", "morcov", "ou"],
    storage: "Se păstrează la frigider 4 zile sau congelator 2 luni.",
  },
  {
    id: "orez-legume-pui-12",
    name: "Orez cu legume și pui",
    emoji: "🍚",
    mealType: "cina",
    time: "35 min",
    age: "12+ luni",
    difficulty: "Mediu",
    servings: "3-4",
    ingredients: [
      "1 cană orez",
      "200g piept de pui",
      "1 morcov",
      "½ cană mazăre",
      "½ ardei gras",
      "1 lingură ulei",
      "2 căni apă sau supă",
    ],
    steps: [
      "Taie puiul și legumele cuburi mici.",
      "Călește puiul în ulei 5 minute.",
      "Adaugă morcovul și ardeiul, 3 minute.",
      "Adaugă orezul, amestecă 1 minut.",
      "Adaugă apa/supa. Fierbe acoperit 20 minute.",
      "Adaugă mazărea, mai gătește 5 minute.",
    ],
    allergens: [],
    relatedFoods: ["orez", "pui", "morcov", "mazare", "ardei-gras"],
    storage: "Se păstrează la frigider 3 zile.",
  },
  {
    id: "paste-sos-rosii-carne-12",
    name: "Paste cu sos de roșii și carne",
    emoji: "🍝",
    mealType: "cina",
    time: "30 min",
    age: "12+ luni",
    difficulty: "Mediu",
    servings: "3-4",
    ingredients: [
      "200g paste (penne sau farfalle mici)",
      "200g carne tocată de vită sau porc",
      "1 cană roșii pasate",
      "1 ceapă mică",
      "1 cățel usturoi",
      "1 lingură ulei",
      "1 vârf busuioc",
    ],
    steps: [
      "Fierbe pastele al dente. Scurge.",
      "Călește ceapa și usturoiul în ulei.",
      "Adaugă carnea tocată. Gătește 8 minute.",
      "Adaugă roșiile pasate. Fierbe 10 minute.",
      "Amestecă pastele cu sosul.",
      "Presară busuioc. Taie bucățile de carne mai mici dacă e necesar.",
    ],
    allergens: ["Gluten"],
    relatedFoods: ["paste", "rosii", "vita", "usturoi"],
    storage: "Se păstrează la frigider 3 zile.",
  },
  {
    id: "supa-crema-dovleac-12",
    name: "Supă cremă de dovleac",
    emoji: "🎃",
    mealType: "cina",
    time: "40 min",
    age: "12+ luni",
    difficulty: "Ușor",
    servings: "4-5",
    ingredients: [
      "500g dovleac",
      "1 morcov",
      "1 cartof",
      "1 ceapă",
      "2 linguri ulei de cocos",
      "1 cană lapte de cocos",
      "½ linguriță scorțișoară și ghimbir",
    ],
    steps: [
      "Taie dovleacul, morcovul, cartoful și ceapa.",
      "Călește ceapa în ulei 3 minute.",
      "Adaugă restul legumelor.",
      "Acoperă cu apă și fierbe 25 minute.",
      "Pasează cu blenderul totul.",
      "Adaugă laptele de cocos și condimentele.",
      "Mai fierbe 5 minute. Servește caldă.",
    ],
    allergens: ["Nucă de cocos"],
    relatedFoods: ["dovleac", "morcov", "cartof"],
    storage: "Se păstrează la frigider 4 zile sau congelator 2 luni.",
  },
  {
    id: "fasole-rosie-legume-12",
    name: "Fasole roșie cu legume",
    emoji: "🫘",
    mealType: "cina",
    time: "30 min",
    age: "12+ luni",
    difficulty: "Ușor",
    servings: "4",
    ingredients: [
      "1 conservă fasole roșie (400g)",
      "1 roșie mare",
      "½ ardei gras",
      "1 ceapă",
      "1 cățel usturoi",
      "1 linguriță boia dulce",
      "1 lingură ulei",
    ],
    steps: [
      "Spală și scurge fasolea.",
      "Taie ceapa, ardeiul, roșia și usturoiul mărunt.",
      "Călește ceapa în ulei 3 minute.",
      "Adaugă ardeiul și usturoiul, 2 minute.",
      "Adaugă roșia și boia. Gătește 5 minute.",
      "Adaugă fasolea. Fierbe 15 minute la foc mic.",
      "Zdrobește ușor pentru textură mai fină.",
    ],
    allergens: [],
    relatedFoods: ["naut", "ardei-gras", "rosii", "usturoi"],
    storage: "Se păstrează la frigider 4 zile.",
  },
  {
    id: "piept-pui-cartofi-cuptor-12",
    name: "Piept de pui cu cartofi la cuptor",
    emoji: "🍗",
    mealType: "cina",
    time: "50 min",
    age: "12+ luni",
    difficulty: "Ușor",
    servings: "3-4",
    ingredients: [
      "2 piepturi pui",
      "4 cartofi medii",
      "2 morcovi",
      "3 linguri ulei de măsline",
      "1 linguriță boia dulce",
      "1 vârf cimbru",
      "1 lămâie (sucul)",
    ],
    steps: [
      "Preîncălzește cuptorul la 200°C.",
      "Taie cartofii și morcovii cuburi.",
      "Unge puiul și legumele cu ulei, boia și cimbru.",
      "Pune puiul și legumele în tavă.",
      "Stoarce lămâia deasupra.",
      "Coace 40-45 minute.",
      "Taie puiul în bucăți mici pentru bebeluș.",
    ],
    allergens: [],
    relatedFoods: ["pui", "cartof", "morcov", "ulei-masline"],
    storage: "Se păstrează la frigider 3 zile.",
  },
  {
    id: "linte-rosie-morcov-12",
    name: "Supă cremă de linte roșie",
    emoji: "🍵",
    mealType: "cina",
    time: "30 min",
    age: "12+ luni",
    difficulty: "Ușor",
    servings: "4-5",
    ingredients: [
      "1 cană linte roșie",
      "2 morcovi",
      "1 ceapă",
      "2 căței usturoi",
      "½ linguriță chimion",
      "½ linguriță turmeric",
      "1 lingură ulei de măsline",
      "1 lămâie (sucul)",
    ],
    steps: [
      "Clătește lintea.",
      "Călește ceapa și usturoiul în ulei.",
      "Adaugă chimionul și turmericul, 30 secunde.",
      "Adaugă lintea, morcovii și 1.5L apă.",
      "Fierbe 20-25 minute.",
      "Pasează jumătate din supă pentru textură.",
      "Stoarce lămâia. Servește caldă.",
    ],
    allergens: [],
    relatedFoods: ["linte", "morcov", "usturoi", "ulei-masline"],
    storage: "Se păstrează la frigider 4 zile.",
  },
  {
    id: "tocana-vita-legume-12",
    name: "Tocăniță de vită cu legume",
    emoji: "🥩",
    mealType: "cina",
    time: "1h 30min",
    age: "12+ luni",
    difficulty: "Mediu",
    servings: "4-5",
    ingredients: [
      "400g carne vită (pulpă)",
      "2 morcovi",
      "2 cartofi",
      "1 ceapă",
      "1 roșie",
      "1 linguriță boia dulce",
      "2 linguri ulei",
    ],
    steps: [
      "Taie carnea în cuburi mici de 1 cm.",
      "Călește ceapa în ulei.",
      "Adaugă carnea, rumenește pe toate părțile.",
      "Adaugă roșia și boia. Gătește 5 minute.",
      "Acoperă cu apă. Fierbe 1 oră la foc mic.",
      "Adaugă morcovii și cartofii. Fierbe 30 minute.",
      "Carnea trebuie să fie foarte moale.",
    ],
    allergens: [],
    relatedFoods: ["vita", "morcov", "cartof", "rosii"],
    storage: "Se păstrează la frigider 3 zile sau congelator 2 luni.",
  },
  {
    id: "cus-cus-legume-12",
    name: "Cuscus cu legume mediteraneene",
    emoji: "🫙",
    mealType: "cina",
    time: "20 min",
    age: "12+ luni",
    difficulty: "Ușor",
    servings: "3-4",
    ingredients: [
      "1 cană cuscus",
      "1 cană apă fierbinte",
      "1 dovlecel",
      "1 roșie",
      "½ ardei gras",
      "1 linguriță ulei de măsline",
      "1 vârf mentă sau pătrunjel",
    ],
    steps: [
      "Toarnă apa fierbinte peste cuscus. Acoperă 5 minute.",
      "Aerisește cu furculița.",
      "Taie legumele cuburi mici.",
      "Sotează legumele în ulei 5-7 minute.",
      "Amestecă cuscusul cu legumele.",
      "Adaugă iarba aromată. Servește caldă sau rece.",
    ],
    allergens: ["Gluten"],
    relatedFoods: ["dovlecel", "ardei-gras", "rosii"],
    storage: "Se păstrează la frigider 3 zile.",
  },
  {
    id: "somon-legume-abur-12",
    name: "Somon la abur cu broccoli",
    emoji: "🐟",
    mealType: "cina",
    time: "20 min",
    age: "12+ luni",
    difficulty: "Ușor",
    servings: "2",
    ingredients: [
      "200g file somon",
      "1 căpățână broccoli",
      "1 lămâie (sucul)",
      "1 vârf mărar",
      "1 linguriță ulei de măsline",
    ],
    steps: [
      "Pune somonul și broccoli-ul în vaporizator sau pe o sită deasupra apei.",
      "Fierbe acoperit 12-15 minute.",
      "Verifică că somonul e complet gătit.",
      "Sfărâmă somonul cu furculița (verifică oasele!).",
      "Stoarce lămâia deasupra.",
      "Stropește cu ulei și presară mărar.",
    ],
    allergens: ["Pește"],
    relatedFoods: ["somon", "broccoli", "ulei-masline"],
    storage: "Se servește proaspăt. Max 1 zi frigider.",
  },
  {
    id: "mamaliga-branza-ou-12",
    name: "Mămăligă cu brânză și ou",
    emoji: "🌽",
    mealType: "cina",
    time: "25 min",
    age: "12+ luni",
    difficulty: "Mediu",
    servings: "3-4",
    ingredients: [
      "1 cană mălai",
      "3 căni apă",
      "100g brânză telemea (desărată prin înmuiere)",
      "2 ouă",
      "1 linguriță unt",
    ],
    steps: [
      "Fierbe apa. Adaugă mălaiul în ploaie amestecând.",
      "Gătește 20 minute la foc mic, amestecând des.",
      "Adaugă untul la final.",
      "Fierbe ouăle ochi sau fierte tari.",
      "Servește mămăliga cu brânza telemea desărată.",
      "Pune oul deasupra.",
      "Telemea pentru bebeluș: lasă 2h în apă rece să se desăreze.",
    ],
    allergens: ["Ou", "Lactoză"],
    relatedFoods: ["ou", "branza-vaci", "porumb"],
    storage: "Mămăliga se păstrează la frigider 2 zile.",
  },
  {
    id: "quiche-legume-12",
    name: "Quiche cu legume (fără coajă)",
    emoji: "🥧",
    mealType: "cina",
    time: "40 min",
    age: "12+ luni",
    difficulty: "Mediu",
    servings: "4-6",
    ingredients: [
      "4 ouă",
      "½ cană smântână",
      "½ cană lapte",
      "1 morcov ras",
      "½ cană spanac",
      "¼ cană brânză rasă",
      "1 linguriță unt pentru formă",
      "1 vârf nucșoară",
    ],
    steps: [
      "Preîncălzește cuptorul la 180°C.",
      "Bate ouăle cu smântâna și laptele.",
      "Adaugă morcovul, spanacul și brânza.",
      "Condimentează cu nucșoară.",
      "Unge o formă rotundă cu unt.",
      "Toarnă amestecul în formă.",
      "Coace 30-35 minute până e auriu și ferm.",
      "Taie pătrate sau triunghiuri.",
    ],
    allergens: ["Ou", "Lactoză"],
    relatedFoods: ["ou", "morcov", "spanac", "branza-vaci"],
    storage: "Se păstrează la frigider 4 zile.",
  },
  {
    id: "pilaf-legume-12",
    name: "Pilaf de legume cu ierburi",
    emoji: "🍛",
    mealType: "cina",
    time: "30 min",
    age: "12+ luni",
    difficulty: "Ușor",
    servings: "4",
    ingredients: [
      "1 cană orez",
      "1 morcov",
      "½ cană mazăre",
      "½ ardei gras",
      "1 ceapă",
      "2 linguri ulei",
      "2 căni supă de legume",
    ],
    steps: [
      "Taie ceapa, morcovul și ardeiul mărunt.",
      "Călește ceapa în ulei.",
      "Adaugă morcovul și ardeiul, 3 minute.",
      "Adaugă orezul, amestecă 1 minut.",
      "Toarnă supa. Fierbe acoperit 20 minute.",
      "Adaugă mazărea, 5 minute.",
      "Aerisește cu furculița înainte de servit.",
    ],
    allergens: [],
    relatedFoods: ["orez", "morcov", "mazare", "ardei-gras"],
    storage: "Se păstrează la frigider 3 zile.",
  },
  {
    id: "file-cod-cartofi-12",
    name: "File de cod cu cartofi fierți",
    emoji: "🐡",
    mealType: "cina",
    time: "30 min",
    age: "12+ luni",
    difficulty: "Ușor",
    servings: "2",
    ingredients: [
      "200g file de cod",
      "3 cartofi medii",
      "1 lămâie",
      "1 linguriță ulei de măsline",
      "1 vârf pătrunjel",
      "1 linguriță unt",
    ],
    steps: [
      "Fierbe cartofii 20 minute. Taie în rondele.",
      "Pune codul în tavă, stoarce lămâia.",
      "Coace la 180°C 15 minute.",
      "Verifică că e complet gătit — trebuie să se fărâmeze ușor.",
      "Sfărâmă cu furculița și verifică oasele!",
      "Servește cu cartofii și presară pătrunjel.",
    ],
    allergens: ["Pește"],
    relatedFoods: ["peste-alb", "cartof", "ulei-masline"],
    storage: "Se servește proaspăt. Max 1 zi frigider.",
  },
  {
    id: "supa-pui-taitei-12",
    name: "Supă de pui cu tăiței de casă",
    emoji: "🍜",
    mealType: "cina",
    time: "1h",
    age: "12+ luni",
    difficulty: "Mediu",
    servings: "6-8",
    ingredients: [
      "1 pulpă pui (cu os)",
      "2 morcovi",
      "1 păstârnac",
      "½ țelină",
      "1 ceapă",
      "½ cană tăiței de casă",
      "1 vârf leuștean și pătrunjel",
    ],
    steps: [
      "Pune puiul cu 2L apă la fiert cu ceapa.",
      "Spumează după primele 5 minute.",
      "Adaugă morcovii, păstârnacul, țelina.",
      "Fierbe 45 minute la foc mic.",
      "Scoate puiul. Dezosează și taie bucăți mici.",
      "Adaugă tăițeii. Fierbe 8 minute.",
      "Adaugă puiul înapoi. Presară verdeață.",
      "Servește caldă.",
    ],
    allergens: ["Gluten"],
    relatedFoods: ["pui", "morcov", "pastarnac"],
    storage: "Se păstrează la frigider 3 zile.",
  },
  {
    id: "dovlecel-umplut-12",
    name: "Dovlecel umplut cu carne și orez",
    emoji: "🥒",
    mealType: "cina",
    time: "50 min",
    age: "12+ luni",
    difficulty: "Mediu",
    servings: "4",
    ingredients: [
      "2 dovlecei medii",
      "200g carne tocată de pui sau vită",
      "½ cană orez fiert",
      "1 roșie",
      "1 ou",
      "1 vârf mărar",
      "1 linguriță ulei",
    ],
    steps: [
      "Taie dovleceii în jumătate pe lungime. Scobește miezul.",
      "Toacă miezul mărunt și amestecă cu carnea.",
      "Adaugă orezul fiert, oul și mărarul.",
      "Umple dovleceii cu amestecul.",
      "Pune în tavă cu puțină apă la fund.",
      "Pune roșia tocată deasupra fiecăruia.",
      "Coace la 180°C 35-40 minute.",
    ],
    allergens: ["Ou"],
    relatedFoods: ["dovlecel", "pui", "orez", "rosii"],
    storage: "Se păstrează la frigider 3 zile.",
  },
  {
    id: "naut-spanac-12",
    name: "Năut cu spanac și roșii",
    emoji: "🫘",
    mealType: "cina",
    time: "25 min",
    age: "12+ luni",
    difficulty: "Ușor",
    servings: "3-4",
    ingredients: [
      "1 conservă năut (400g)",
      "2 pumni spanac proaspăt",
      "1 cană roșii pasate",
      "2 căței usturoi",
      "½ linguriță turmeric",
      "1 linguriță ulei de măsline",
    ],
    steps: [
      "Spală și scurge năutul.",
      "Călește usturoiul în ulei 1 minut.",
      "Adaugă roșiile și turmericul. Fierbe 5 minute.",
      "Adaugă năutul. Fierbe 10 minute.",
      "Adaugă spanacul, amestecă până se înmoaie.",
      "Zdrobește ușor câteva boabe de năut pentru textură.",
    ],
    allergens: [],
    relatedFoods: ["naut", "spanac", "rosii", "usturoi"],
    storage: "Se păstrează la frigider 4 zile.",
  },
  {
    id: "biban-legume-hartie-12",
    name: "Biban la cuptor în hârtie cu legume",
    emoji: "🐟",
    mealType: "cina",
    time: "30 min",
    age: "12+ luni",
    difficulty: "Mediu",
    servings: "2",
    ingredients: [
      "2 file biban",
      "1 dovlecel",
      "1 morcov",
      "½ lămâie",
      "1 linguriță ulei de măsline",
      "1 vârf cimbru și pătrunjel",
    ],
    steps: [
      "Preîncălzește cuptorul la 200°C.",
      "Taie legumele julien (fâșii subțiri).",
      "Pune fiecare file pe hârtie de copt.",
      "Pune legumele alături.",
      "Stoarce lămâia, adaugă uleiul și cimbrul.",
      "Închide hârtia formând un pachet.",
      "Coace 20-25 minute.",
      "Verifică că peștele e complet gătit și fără oase!",
    ],
    allergens: ["Pește"],
    relatedFoods: ["peste-alb", "dovlecel", "morcov", "ulei-masline"],
    storage: "Se servește proaspăt.",
  },
];
