import type { RecipeCatalogItem } from "./recipesDatabase";

/** Cină 8+ luni — toate mealType: cina */
export const CINA_8PLUS_RECIPES: RecipeCatalogItem[] = [
  {
    id: "piure-morcov-pui-cina",
    name: "Piure de morcov cu pui sfărâmat",
    emoji: "🥕",
    mealType: "cina",
    time: "30 min",
    age: "8+ luni",
    difficulty: "Mediu",
    servings: "2-3",
    ingredients: [
      "3 morcovi medii",
      "100g piept de pui",
      "1 lingură unt nesărat",
      "½ cană apă de la fiert",
      "1 vârf cimbru (opțional)",
    ],
    steps: [
      "Fierbe pieptul de pui 25 minute. Sfărâmă fin cu 2 furculițe.",
      "Curăță morcovii, taie-i în rondele. Fierbe 15 minute.",
      "Pasează morcovii cu untul și puțină apă de la fiert.",
      "Pune piureul în castron, adaugă puiul sfărâmat deasupra.",
      "Presară cimbru. Servește călduț.",
    ],
    allergens: ["Lactoză"],
    relatedFoods: ["morcov", "pui"],
    storage: "Se păstrează la frigider 3 zile sau congelator 2 luni.",
  },
  {
    id: "supa-crema-conopida-cartof",
    name: "Supă cremă de conopidă cu cartof",
    emoji: "🥦",
    mealType: "cina",
    time: "25 min",
    age: "8+ luni",
    difficulty: "Ușor",
    servings: "3-4",
    ingredients: [
      "½ conopidă mică (buchețele)",
      "1 cartof mediu",
      "1 ceapă mică",
      "1 lingură ulei de măsline",
      "2 căni apă",
      "1 linguriță unt (opțional)",
      "1 vârf nucșoară",
    ],
    steps: [
      "Taie ceapa mărunt, curăță cartoful și taie-l în cuburi.",
      "Încălzește uleiul, călește ceapa 3 minute.",
      "Adaugă conopida, cartoful și apa.",
      "Fierbe, apoi foc mic 20 minute.",
      "Pasează cu blenderul vertical. Adaugă unt și nucșoară.",
      "Servește călduță cu o picătură de ulei deasupra.",
    ],
    allergens: ["Lactoză"],
    relatedFoods: ["conopida", "cartof"],
    storage: "Se păstrează la frigider 4 zile sau congelator 3 luni.",
  },
  {
    id: "orez-dovleac-branza-vaci",
    name: "Orez cremos cu dovleac și brânză de vaci",
    emoji: "🎃",
    mealType: "cina",
    time: "25 min",
    age: "8+ luni",
    difficulty: "Ușor",
    servings: "2-3",
    ingredients: [
      "½ cană orez rotund",
      "1 cană dovleac butternut cuburi",
      "1½ căni apă",
      "2 linguri brânză de vaci",
      "1 vârf scorțișoară (opțional)",
    ],
    steps: [
      "Clătește orezul. Pune-l cu dovleacul și apa la fiert.",
      "Când fierbe, scade focul, acoperă. Gătește 20 minute.",
      "Dovleacul se va desface singur — amestecă bine.",
      "Adaugă brânza de vaci și scorțișoara.",
      "Servește călduț.",
    ],
    allergens: ["Lactoză"],
    relatedFoods: ["orez", "dovleac-butternut", "branza-vaci", "scortisoara"],
    storage: "Se păstrează la frigider 2 zile.",
  },
  {
    id: "piure-mazare-cartof-curcan",
    name: "Piure de mazăre cu cartof și curcan",
    emoji: "🫛",
    mealType: "cina",
    time: "25 min",
    age: "8+ luni",
    difficulty: "Ușor",
    servings: "2-3",
    ingredients: [
      "1 cartof mediu",
      "1 cană mazăre congelată",
      "100g curcan tocat",
      "1 lingură ulei de măsline",
      "1 lingură unt",
      "¼ cană apă sau lapte",
    ],
    steps: [
      "Curăță cartoful, fierbe 15 minute. Scurge.",
      "Fierbe mazărea 5 minute. Scurge.",
      "Călește curcanul tocat în ulei 10 minute până e gătit complet.",
      "Pasează cartoful și mazărea cu untul și laptele.",
      "Amestecă piureul cu curcanul sfărâmat.",
      "Servește călduț.",
    ],
    allergens: ["Lactoză"],
    relatedFoods: ["mazare", "cartof", "curcan"],
    storage: "Se păstrează la frigider 3 zile.",
  },
  {
    id: "supa-linte-cocos-turmeric",
    name: "Supă de linte cu cocos și turmeric",
    emoji: "🥣",
    mealType: "cina",
    time: "25 min",
    age: "8+ luni",
    difficulty: "Ușor",
    servings: "4-6",
    ingredients: [
      "1 cană linte roșie",
      "1 morcov",
      "1 ceapă mică",
      "1 cățel usturoi",
      "1 lingură ulei",
      "3 căni apă",
      "½ cană lapte de cocos",
      "½ linguriță turmeric",
      "1 vârf ghimbir pudră",
    ],
    steps: [
      "Clătește lintea bine.",
      "Taie ceapa, morcovul și usturoiul mărunt.",
      "Călește ceapa în ulei 3 minute. Adaugă usturoiul.",
      "Adaugă morcovul, lintea, apa și condimentele.",
      "Fierbe, apoi foc mic 20 minute.",
      "Adaugă laptele de cocos. Pasează parțial.",
      "Servește călduță.",
    ],
    allergens: ["Nucă de cocos"],
    relatedFoods: ["linte", "morcov", "unt-cocos", "turmeric", "ghimbir"],
    storage: "Se păstrează la frigider 5 zile sau congelator 3 luni.",
  },
  {
    id: "paste-broccoli-ricotta-cina",
    name: "Paste cu broccoli și ricotta",
    emoji: "🥦",
    mealType: "cina",
    time: "15 min",
    age: "8+ luni",
    difficulty: "Ușor",
    servings: 1,
    ingredients: [
      "50g paste mici (stelline sau risoni)",
      "½ cană broccoli buchețele",
      "2 linguri ricotta",
      "1 linguriță ulei de măsline",
      "1 linguriță suc de lămâie",
    ],
    steps: [
      "Fierbe pastele conform instrucțiunilor. Cu 3 minute înainte de final adaugă broccoli.",
      "Scurge totul. Pune în castron.",
      "Adaugă ricotta, uleiul și sucul de lămâie.",
      "Amestecă bine — ricotta va deveni un sos cremos.",
      "Servește călduț.",
    ],
    allergens: ["Lactoză", "Gluten"],
    relatedFoods: ["paste", "broccoli", "branza-vaci"],
    storage: "Se păstrează la frigider 2 zile.",
  },
  {
    id: "piure-pastarnac-pere-pui",
    name: "Piure de păstârnac cu pere și pui",
    emoji: "🍐",
    mealType: "cina",
    time: "30 min",
    age: "8+ luni",
    difficulty: "Mediu",
    servings: "2-3",
    ingredients: [
      "2 păstârnaci",
      "1 pară",
      "100g piept de pui",
      "1 lingură unt",
      "¼ cană apă de la fiert",
    ],
    steps: [
      "Fierbe pieptul de pui 25 minute. Sfărâmă cu furculițele.",
      "Curăță păstârnacii și para. Taie în cuburi.",
      "Fierbe păstârnacii și para 15 minute.",
      "Pasează cu untul și puțină apă de la fiert.",
      "Adaugă puiul sfărâmat deasupra.",
    ],
    allergens: ["Lactoză"],
    relatedFoods: ["pastarnac", "pere", "pui"],
    storage: "Se păstrează la frigider 3 zile sau congelator 2 luni.",
  },
  {
    id: "risotto-morcov-linte",
    name: "Risotto de morcov cu linte roșie",
    emoji: "🥕",
    mealType: "cina",
    time: "30 min",
    age: "8+ luni",
    difficulty: "Mediu",
    servings: "2-3",
    ingredients: [
      "½ cană orez rotund",
      "¼ cană linte roșie",
      "1 morcov mare ras",
      "1 ceapă mică",
      "1 lingură ulei",
      "2½ căni apă caldă",
      "1 linguriță unt (opțional)",
    ],
    steps: [
      "Clătește orezul și lintea.",
      "Călește ceapa tocată în ulei 3 minute.",
      "Adaugă orezul și lintea, amestecă 1 minut.",
      "Adaugă morcovul ras.",
      "Toarnă apa treptat, câte un polonic, amestecând.",
      "Gătește ~25 minute până e cremos.",
      "Amestecă untul. Servește călduț.",
    ],
    allergens: ["Lactoză"],
    relatedFoods: ["orez", "linte", "morcov"],
    storage: "Se păstrează la frigider 2 zile.",
  },
  {
    id: "piure-cartof-spanac-somon",
    name: "Piure de cartof cu spanac și somon",
    emoji: "🐟",
    mealType: "cina",
    time: "30 min",
    age: "8+ luni",
    difficulty: "Mediu",
    servings: "2-3",
    ingredients: [
      "2 cartofi medii",
      "1 cană spanac proaspăt",
      "80g somon proaspăt fără oase",
      "1 lingură unt",
      "¼ cană lapte",
      "1 linguriță suc de lămâie",
    ],
    steps: [
      "Curăță cartofii, fierbe-i 20 minute. Pasează cu unt și lapte.",
      "Gătește somonul la abur 10 minute. VERIFICĂ OASELE! Sfărâmă.",
      "Ofilește spanacul 2 minute în puțină apă. Tocă mărunt.",
      "Amestecă spanacul în piure.",
      "Pune somonul sfărâmat deasupra. Stropește cu lămâie.",
    ],
    allergens: ["Pește", "Lactoză"],
    relatedFoods: ["cartof", "spanac", "somon"],
    storage: "Se păstrează la frigider 2 zile.",
  },
  {
    id: "dovlecel-umplut-quinoa",
    name: "Dovlecel umplut cu quinoa și legume",
    emoji: "🥒",
    mealType: "cina",
    time: "40 min",
    age: "8+ luni",
    difficulty: "Mediu",
    servings: "2-4",
    ingredients: [
      "2 dovlecei medii",
      "½ cană quinoa fiartă",
      "1 morcov mic ras",
      "¼ cană mazăre",
      "2 linguri ricotta",
      "1 lingură ulei",
      "1 vârf busuioc uscat",
    ],
    steps: [
      "Taie dovleceii în jumătăți pe lung. Scoate miezul cu lingurița.",
      "Tocă miezul mărunt.",
      "Călește miezul cu morcovul ras în ulei 5 minute.",
      "Adaugă mazărea, gătește 3 minute.",
      "Amestecă cu quinoa fiartă, ricotta și busuiocul.",
      "Umple dovleceii. Coace la 180°C, 25 minute.",
      "Lasă să se răcească. Servește tăiat felii.",
    ],
    allergens: ["Lactoză"],
    relatedFoods: ["dovlecel", "quinoa", "morcov", "mazare", "branza-vaci"],
    storage: "Se păstrează la frigider 3 zile.",
  },
  {
    id: "terci-ovaz-sarat-legume",
    name: "Terci sărat de ovăz cu legume",
    emoji: "🥣",
    mealType: "cina",
    time: "15 min",
    age: "8+ luni",
    difficulty: "Ușor",
    servings: 1,
    ingredients: [
      "¼ cană fulgi de ovăz",
      "½ cană apă",
      "¼ cană lapte",
      "1 morcov mic ras",
      "¼ cană spanac tocat",
      "1 linguriță unt",
      "1 vârf usturoi pudră",
    ],
    steps: [
      "Fierbe apa cu laptele.",
      "Adaugă fulgii de ovăz și morcovul ras.",
      "Gătește 5 minute amestecând.",
      "Adaugă spanacul tocat, gătește 2 minute.",
      "Amestecă untul și usturoiul pudră.",
      "Servește călduț — e ca o polenta cremoasă!",
    ],
    allergens: ["Lactoză", "Gluten"],
    relatedFoods: ["ovaz", "morcov", "spanac"],
    storage: "Se servește proaspăt.",
  },
  {
    id: "piure-sfecla-cartof-vita",
    name: "Piure roz de sfeclă cu cartof și vită",
    emoji: "🟣",
    mealType: "cina",
    time: "35 min",
    age: "8+ luni",
    difficulty: "Mediu",
    servings: "2-3",
    ingredients: [
      "1 sfeclă mică fiartă",
      "1 cartof mediu",
      "100g vită tocată",
      "1 lingură ulei",
      "1 lingură unt",
      "¼ cană lapte",
    ],
    steps: [
      "Curăță cartoful, fierbe-l 20 minute.",
      "Călește vita tocată în ulei 10 minute, sfărâmând bine.",
      "Pasează cartoful cu sfecla fiartă, untul și laptele.",
      "Va ieși un piure roz frumos!",
      "Pune vita sfărâmată deasupra.",
      "Servește călduț.",
    ],
    allergens: ["Lactoză"],
    relatedFoods: ["sfecla", "cartof", "vita"],
    storage: "Se păstrează la frigider 3 zile.",
  },
  {
    id: "supa-dovleac-cartof-dulce",
    name: "Supă cremă de dovleac cu cartof dulce",
    emoji: "🎃",
    mealType: "cina",
    time: "30 min",
    age: "8+ luni",
    difficulty: "Ușor",
    servings: "4-6",
    ingredients: [
      "300g dovleac cuburi",
      "1 cartof dulce mediu",
      "1 ceapă mică",
      "1 lingură ulei",
      "3 căni apă",
      "1 vârf scorțișoară și ghimbir",
      "1 linguriță unt (opțional)",
    ],
    steps: [
      "Curăță cartoful dulce, taie în cuburi.",
      "Călește ceapa în ulei 3 minute.",
      "Adaugă dovleacul, cartoful dulce și condimentele.",
      "Toarnă apa. Fierbe, apoi foc mic 25 minute.",
      "Pasează cu blenderul. Adaugă unt.",
      "Servește călduță.",
    ],
    allergens: ["Lactoză"],
    relatedFoods: ["dovleac", "cartof-dulce", "scortisoara", "ghimbir"],
    storage: "Se păstrează la frigider 5 zile sau congelator 3 luni.",
  },
  {
    id: "naut-piure-tahini-morcov",
    name: "Piure de năut cu tahini și morcov fiert",
    emoji: "🫘",
    mealType: "cina",
    time: "15 min",
    age: "8+ luni",
    difficulty: "Ușor",
    servings: "1-2",
    ingredients: [
      "½ cană năut fiert (clătit bine)",
      "1 lingură tahini",
      "1 linguriță suc de lămâie",
      "1 linguriță ulei de măsline",
      "1 morcov mediu fiert",
      "1 vârf chimion",
    ],
    steps: [
      "Pasează năutul cu tahini, sucul de lămâie, uleiul și chimionul.",
      "Adaugă 1-2 linguri apă pentru consistență cremoasă.",
      "Taie morcovul fiert în bețișoare.",
      "Pune piureul de năut în castron.",
      "Servește cu bețișoarele de morcov pe lângă.",
    ],
    allergens: ["Susan"],
    relatedFoods: ["naut", "morcov"],
    storage: "Se păstrează la frigider 4 zile.",
  },
  {
    id: "piure-brocoli-cartof-branza",
    name: "Piure de broccoli cu cartof și brânză",
    emoji: "🥦",
    mealType: "cina",
    time: "20 min",
    age: "8+ luni",
    difficulty: "Ușor",
    servings: "1-2",
    ingredients: [
      "1 cană broccoli buchețele",
      "1 cartof mediu",
      "2 linguri brânză de vaci",
      "1 lingură unt",
      "¼ cană lapte",
    ],
    steps: [
      "Curăță cartoful, taie în cuburi. Fierbe 15 minute.",
      "Adaugă broccoli în ultimele 5 minute de fierbere.",
      "Scurge. Pasează cu unt, lapte și brânză.",
      "Nu trebuie să fie perfect fin — un pic de textură e bine.",
      "Servește călduț.",
    ],
    allergens: ["Lactoză"],
    relatedFoods: ["broccoli", "cartof", "branza-vaci"],
    storage: "Se păstrează la frigider 3 zile.",
  },
  {
    id: "tocana-curcan-dovlecel-orez",
    name: "Tocăniță de curcan cu dovlecel pe pat de orez",
    emoji: "🦃",
    mealType: "cina",
    time: "30 min",
    age: "8+ luni",
    difficulty: "Mediu",
    servings: "3-4",
    ingredients: [
      "200g curcan tocat",
      "1 dovlecel mic",
      "1 morcov",
      "1 ceapă mică",
      "1 roșie",
      "1 lingură ulei",
      "1 cană apă",
      "½ cană orez",
    ],
    steps: [
      "Călește ceapa tocată în ulei 3 minute.",
      "Adaugă curcanul, sfărâmă bine. Gătește 8 minute.",
      "Rade dovlecelul și morcovul. Adaugă-le în oală.",
      "Adaugă roșia tocată și apa. Gătește 15 minute la foc mic.",
      "Fierbe orezul separat 15 minute.",
      "Pune orezul în castron, tocănița deasupra.",
    ],
    allergens: [],
    relatedFoods: ["curcan", "dovlecel", "morcov", "orez", "rosii"],
    storage: "Se păstrează la frigider 3 zile sau congelator 2 luni.",
  },
  {
    id: "cuscus-legume-naut",
    name: "Cuscus cu legume și năut",
    emoji: "🫘",
    mealType: "cina",
    time: "15 min",
    age: "8+ luni",
    difficulty: "Ușor",
    servings: "2-3",
    ingredients: [
      "½ cană cuscus",
      "½ cană apă fierbinte",
      "¼ cană năut fiert",
      "1 morcov mic ras",
      "¼ cană mazăre fiartă",
      "1 linguriță ulei de măsline",
      "1 linguriță suc de lămâie",
      "1 vârf chimion",
    ],
    steps: [
      "Pune cuscus într-un castron. Toarnă apa fierbinte.",
      "Acoperă 5 minute. Aerisește cu furculița.",
      "Clătește năutul. Pasează-l ușor pentru sub 12 luni.",
      "Amestecă cuscus cu năut, morcov, mazăre.",
      "Adaugă ulei, lămâie și chimion.",
      "Servește călduț sau la temperatura camerei.",
    ],
    allergens: ["Gluten"],
    relatedFoods: ["naut", "morcov", "mazare"],
    storage: "Se păstrează la frigider 3 zile.",
  },
  {
    id: "piure-dovleac-mere-scortisoara",
    name: "Piure de dovleac cu mere și scorțișoară",
    emoji: "🎃",
    mealType: "cina",
    time: "25 min",
    age: "8+ luni",
    difficulty: "Ușor",
    servings: "2-3",
    ingredients: [
      "1½ cană dovleac cuburi",
      "1 măr mare",
      "1 lingură unt",
      "¼ cană apă",
      "1 vârf scorțișoară",
    ],
    steps: [
      "Curăță dovleacul și mărul. Taie în cuburi.",
      "Pune-le într-o oală cu apa.",
      "Fierbe acoperit 20 minute la foc mic.",
      "Pasează cu unt și scorțișoară.",
      "Servește călduț — poate fi și desert!",
    ],
    allergens: ["Lactoză"],
    relatedFoods: ["dovleac", "mere", "scortisoara"],
    storage: "Se păstrează la frigider 5 zile sau congelator 2 luni.",
  },
  {
    id: "paste-tofu-sos-rosii",
    name: "Paste cu tofu în sos de roșii",
    emoji: "🍝",
    mealType: "cina",
    time: "20 min",
    age: "8+ luni",
    difficulty: "Ușor",
    servings: "1-2",
    ingredients: [
      "50g paste mici",
      "60g tofu ferm",
      "¼ cană sos de roșii fără sare",
      "1 linguriță ulei de măsline",
      "½ cană spanac (opțional)",
      "1 vârf busuioc uscat",
    ],
    steps: [
      "Fierbe pastele conform instrucțiunilor. Scurge.",
      "Taie tofu-ul în cuburi mici.",
      "Încălzește uleiul, prăjește tofu 3 minute pe fiecare parte.",
      "Adaugă sosul de roșii și busuiocul. Gătește 3 minute.",
      "Adaugă spanacul, gătește 2 minute.",
      "Combină cu pastele. Servește călduț.",
    ],
    allergens: ["Soia", "Gluten"],
    relatedFoods: ["paste", "tofu", "rosii", "spanac"],
    storage: "Se păstrează la frigider 2 zile.",
  },
  {
    id: "piure-varza-kale-cartof-pui",
    name: "Piure de varză kale cu cartof și pui",
    emoji: "🥬",
    mealType: "cina",
    time: "30 min",
    age: "8+ luni",
    difficulty: "Mediu",
    servings: "2-3",
    ingredients: [
      "1 cană varză kale curățată de cotor",
      "1 cartof mediu",
      "100g piept de pui",
      "1 lingură unt",
      "¼ cană lapte",
    ],
    steps: [
      "Fierbe pieptul de pui 25 minute. Sfărâmă.",
      "Curăță cartoful, fierbe 15 minute.",
      "Fierbe kale separat 8 minute.",
      "Pasează cartoful și kale cu unt și lapte.",
      "Adaugă puiul sfărâmat deasupra.",
    ],
    allergens: ["Lactoză"],
    relatedFoods: ["kale", "cartof", "pui"],
    storage: "Se păstrează la frigider 3 zile.",
  },
];

/** Cină 10+ luni — mealType: cina (lot suplimentar) */
export const CINA_10PLUS_DINNER_RECIPES: RecipeCatalogItem[] = [
  {
    id: "supa-pui-taitei-legume",
    name: "Supă de pui cu tăiței și legume",
    emoji: "🍜",
    mealType: "cina",
    time: "35 min",
    age: "10+ luni",
    difficulty: "Mediu",
    servings: "4-6",
    ingredients: [
      "1 piept de pui mic",
      "1 morcov",
      "½ țelină mică",
      "1 ceapă",
      "1 păstârnac",
      "4 căni apă",
      "50g tăiței subțiri",
      "1 legătură pătrunjel",
    ],
    steps: [
      "Pune pieptul de pui în apă rece. Fierbe 25 minute.",
      "Scoate puiul, sfărâmă-l. Strecură supa.",
      "Taie legumele mărunt. Fierbe-le în supă 15 minute.",
      "Adaugă tăițeii, gătește 5-7 minute.",
      "Pune puiul sfărâmat înapoi.",
      "Presară pătrunjel tocat. Servește călduță.",
    ],
    allergens: ["Gluten"],
    relatedFoods: ["pui", "morcov", "pastarnac", "paste"],
    storage:
      "Se păstrează la frigider 3 zile. Tăițeii se înmoaie la congelat.",
  },
  {
    id: "piure-linte-verde-morcov-vita",
    name: "Piure de linte verde cu morcov și vită",
    emoji: "🥩",
    mealType: "cina",
    time: "40 min",
    age: "10+ luni",
    difficulty: "Mediu",
    servings: "3-4",
    ingredients: [
      "½ cană linte verde",
      "2 morcovi",
      "1 ceapă mică",
      "150g vită tocată",
      "1 lingură ulei",
      "2 căni apă",
      "1 vârf chimion și coriandru",
    ],
    steps: [
      "Clătește lintea. Fierbe cu apa 25-30 minute.",
      "Curăță morcovii, fierbe-i 15 minute.",
      "Călește ceapa în ulei, adaugă vita. Gătește 10 minute.",
      "Pasează lintea cu morcovii.",
      "Adaugă condimentele și vita gătită deasupra.",
    ],
    allergens: [],
    relatedFoods: ["linte", "morcov", "vita"],
    storage: "Se păstrează la frigider 3 zile sau congelator 2 luni.",
  },
  {
    id: "paste-curcan-sos-dovleac",
    name: "Paste cu curcan și sos de dovleac",
    emoji: "🍝",
    mealType: "cina",
    time: "25 min",
    age: "10+ luni",
    difficulty: "Mediu",
    servings: "2-3",
    ingredients: [
      "80g paste fusilli mici",
      "150g curcan tocat",
      "½ cană piure de dovleac",
      "2 linguri ricotta",
      "1 linguriță ulei",
      "1 vârf nucșoară și salvie (opțional)",
    ],
    steps: [
      "Fierbe pastele. Scurge.",
      "Călește curcanul în ulei 10 minute.",
      "Amestecă piureul de dovleac cu ricotta și condimentele.",
      "Adaugă sosul peste curcan, gătește 3 minute.",
      "Combină cu pastele. Servește călduț.",
    ],
    allergens: ["Lactoză", "Gluten"],
    relatedFoods: ["paste", "curcan", "dovleac", "branza-vaci"],
    storage: "Se păstrează la frigider 2 zile.",
  },
  {
    id: "omleta-cuptor-ciuperci-branza",
    name: "Omletă la cuptor cu ciuperci și brânză",
    emoji: "🍄",
    mealType: "cina",
    time: "30 min",
    age: "10+ luni",
    difficulty: "Mediu",
    servings: "4-6",
    ingredients: [
      "6 ouă",
      "4 ciuperci champignon",
      "½ cană spanac",
      "1 ceapă mică",
      "50g brânză rasă",
      "1 lingură unt",
      "1 linguriță ulei",
    ],
    steps: [
      "Preîncălzește cuptorul la 180°C.",
      "Călește ceapa în ulei 3 min. Adaugă ciupercile tocate 5 min.",
      "Adaugă spanacul, gătește 2 minute.",
      "Bate ouăle, adaugă jumătate din brânză.",
      "Unge o tavă cu unt, toarnă ouăle, adaugă legumele.",
      "Presară restul de brânză deasupra.",
      "Coace 20 minute. Taie în pătrate.",
    ],
    allergens: ["Ou", "Lactoză"],
    relatedFoods: ["ou", "ciuperci", "spanac", "branza-vaci"],
    storage: "Se păstrează la frigider 4 zile sau congelator 2 luni.",
  },
  {
    id: "orez-vita-sfecla-iaurt",
    name: "Orez cu vită și sfeclă pe pat de iaurt",
    emoji: "🟣",
    mealType: "cina",
    time: "30 min",
    age: "10+ luni",
    difficulty: "Mediu",
    servings: "2-3",
    ingredients: [
      "½ cană orez",
      "150g vită tocată",
      "1 sfeclă mică fiartă",
      "1 lingură ulei",
      "1 vârf chimion",
      "½ cană iaurt natural",
    ],
    steps: [
      "Fierbe orezul 15 minute. Scurge.",
      "Călește vita în ulei 10 minute, sfărâmând bine.",
      "Rade sfecla fiartă pe răzătoare.",
      "Amestecă orezul cu sfecla rasă și chimionul.",
      "Pune iaurtul în castron, orezul roz deasupra, vita pe top.",
    ],
    allergens: ["Lactoză"],
    relatedFoods: ["orez", "vita", "sfecla", "iaurt"],
    storage: "Se păstrează la frigider 2 zile.",
  },
  {
    id: "supa-crema-sparanghel-cartof",
    name: "Supă cremă de sparanghel",
    emoji: "🥬",
    mealType: "cina",
    time: "25 min",
    age: "10+ luni",
    difficulty: "Ușor",
    servings: "3-4",
    ingredients: [
      "1 legătură sparanghel (200g)",
      "1 cartof mediu",
      "1 ceapă mică",
      "1 lingură unt",
      "2 căni apă",
      "2 linguri smântână sau iaurt",
    ],
    steps: [
      "Curăță sparanghelul — taie capetele lemnoase.",
      "Taie cartoful și ceapa mărunt.",
      "Topește untul, călește ceapa 3 minute.",
      "Adaugă sparanghelul, cartoful și apa.",
      "Fierbe 20 minute la foc mic.",
      "Pasează cu blenderul. Adaugă smântâna.",
    ],
    allergens: ["Lactoză"],
    relatedFoods: ["sparanghel", "cartof"],
    storage: "Se păstrează la frigider 4 zile sau congelator 2 luni.",
  },
  {
    id: "pilaf-pui-legume-cina",
    name: "Pilaf de pui cu legume",
    emoji: "🍚",
    mealType: "cina",
    time: "35 min",
    age: "10+ luni",
    difficulty: "Mediu",
    servings: "3-4",
    ingredients: [
      "1 cană orez",
      "150g piept de pui",
      "1 morcov",
      "½ cană mazăre",
      "1 ceapă mică",
      "2 linguri ulei",
      "2 căni apă caldă",
      "1 vârf turmeric (opțional)",
    ],
    steps: [
      "Fierbe pieptul de pui 25 minute. Taie în cuburi mici.",
      "Călește ceapa și morcovul ras în ulei 5 minute.",
      "Adaugă orezul clătit, amestecă 2 minute.",
      "Toarnă apa caldă, adaugă turmericul.",
      "Acoperă, foc mic, 15 minute.",
      "Adaugă mazărea și puiul, gătește 5 minute.",
      "Aerisește cu furculița.",
    ],
    allergens: [],
    relatedFoods: ["orez", "pui", "morcov", "mazare", "turmeric"],
    storage: "Se păstrează la frigider 2 zile.",
  },
  {
    id: "budinca-spanac-branza-cina",
    name: "Budincă de spanac cu brânză",
    emoji: "🥬",
    mealType: "cina",
    time: "35 min",
    age: "10+ luni",
    difficulty: "Mediu",
    servings: "4-6",
    ingredients: [
      "2 căni spanac proaspăt sau congelat",
      "3 ouă",
      "½ cană lapte",
      "½ cană brânză de vaci",
      "1 lingură unt pentru forma",
      "1 vârf nucșoară",
    ],
    steps: [
      "Gătește spanacul 3 minute. Stoarce bine de apă. Tocă.",
      "Bate ouăle cu laptele și nucșoara.",
      "Amestecă spanacul cu brânza de vaci.",
      "Adaugă compoziția de ouă. Amestecă bine.",
      "Unge forma cu unt, toarnă amestecul.",
      "Coace la 180°C, 20-25 minute.",
      "Taie în cuburi sau bețișoare.",
    ],
    allergens: ["Ou", "Lactoză"],
    relatedFoods: ["spanac", "ou", "branza-vaci"],
    storage: "Se păstrează la frigider 4 zile.",
  },
  {
    id: "peste-alb-piure-mazare",
    name: "Pește alb cu piure de mazăre",
    emoji: "🐟",
    mealType: "cina",
    time: "20 min",
    age: "10+ luni",
    difficulty: "Ușor",
    servings: "1-2",
    ingredients: [
      "100g cod sau pangasius",
      "1 cană mazăre congelată",
      "1 lingură unt",
      "1 linguriță suc de lămâie",
      "1 vârf mentă (opțional)",
    ],
    steps: [
      "Gătește peștele la abur 10 minute. VERIFICĂ OASELE!",
      "Sfărâmă peștele cu furculița.",
      "Fierbe mazărea 5 minute. Pasează cu untul.",
      "Adaugă menta tocată fin și sucul de lămâie.",
      "Pune piureul în castron, peștele deasupra.",
    ],
    allergens: ["Pește", "Lactoză"],
    relatedFoods: ["peste-alb", "mazare"],
    storage: "Se păstrează la frigider 2 zile.",
  },
  {
    id: "tocanita-naut-legume-cina",
    name: "Tocăniță de năut cu legume",
    emoji: "🫘",
    mealType: "cina",
    time: "30 min",
    age: "10+ luni",
    difficulty: "Mediu",
    servings: "3-4",
    ingredients: [
      "1 cană năut fiert",
      "1 dovlecel mic",
      "1 ardei gras",
      "1 roșie",
      "1 ceapă",
      "1 lingură ulei",
      "1 cană apă",
      "½ linguriță boia dulce și chimion",
    ],
    steps: [
      "Taie legumele în cuburi mici.",
      "Călește ceapa în ulei 3 minute.",
      "Adaugă ardeiul și dovlecelul, gătește 5 minute.",
      "Adaugă roșia, năutul, apa și condimentele.",
      "Gătește la foc mic 15 minute.",
      "Pasează ușor o parte pentru bebeluși mai mici.",
    ],
    allergens: [],
    relatedFoods: ["naut", "dovlecel", "ardei-gras", "rosii"],
    storage: "Se păstrează la frigider 4 zile sau congelator 2 luni.",
  },
  {
    id: "quinoa-broccoli-branza-cina",
    name: "Quinoa cu broccoli și brânză topită",
    emoji: "🥦",
    mealType: "cina",
    time: "20 min",
    age: "10+ luni",
    difficulty: "Ușor",
    servings: "1-2",
    ingredients: [
      "½ cană quinoa",
      "1 cană broccoli buchețele",
      "30g brânză rasă (cașcaval sau mozzarella)",
      "1 linguriță unt",
      "1 vârf usturoi pudră",
    ],
    steps: [
      "Fierbe quinoa 15 minute. Scurge.",
      "Fierbe broccoli la abur 8 minute. Tocă grosier.",
      "Amestecă quinoa caldă cu broccoli și brânza rasă.",
      "Brânza se va topi ușor. Adaugă unt și usturoi pudră.",
      "Servește călduț.",
    ],
    allergens: ["Lactoză"],
    relatedFoods: ["quinoa", "broccoli", "branza-vaci"],
    storage: "Se păstrează la frigider 2 zile.",
  },
  {
    id: "ciorba-burta-falsa-bebelusi",
    name: "Ciorbă ușoară de legume cu smântână",
    emoji: "🍲",
    mealType: "cina",
    time: "30 min",
    age: "10+ luni",
    difficulty: "Mediu",
    servings: "4-6",
    ingredients: [
      "1 morcov",
      "1 cartof",
      "½ țelină mică",
      "1 dovlecel mic",
      "1 ceapă",
      "1 lingură ulei",
      "4 căni apă",
      "2 linguri smântână",
      "1 linguriță suc de lămâie",
      "1 legătură mărar",
    ],
    steps: [
      "Taie toate legumele în cuburi mici.",
      "Călește ceapa în ulei 3 minute.",
      "Adaugă legumele și apa. Fierbe.",
      "Gătește la foc mic 20 minute.",
      "Adaugă smântâna și sucul de lămâie.",
      "Presară mărar tocat mărunt. Servește călduță.",
    ],
    allergens: ["Lactoză"],
    relatedFoods: ["morcov", "cartof", "dovlecel"],
    storage: "Se păstrează la frigider 3 zile.",
  },
  {
    id: "pui-sos-rosii-orez-cina",
    name: "Pui în sos de roșii cu orez",
    emoji: "🍗",
    mealType: "cina",
    time: "35 min",
    age: "10+ luni",
    difficulty: "Mediu",
    servings: "3-4",
    ingredients: [
      "200g piept de pui",
      "1 cană roșii pasate",
      "1 ceapă mică",
      "1 cățel usturoi",
      "1 lingură ulei",
      "½ cană apă",
      "1 vârf busuioc",
      "1 cană orez",
    ],
    steps: [
      "Taie puiul în cuburi mici.",
      "Călește ceapa și usturoiul în ulei 3 minute.",
      "Adaugă puiul, rumenește 5 minute.",
      "Adaugă roșiile, apa și busuiocul.",
      "Gătește la foc mic 15 minute.",
      "Fierbe orezul separat.",
      "Servește puiul în sos peste orez.",
    ],
    allergens: [],
    relatedFoods: ["pui", "rosii", "orez", "usturoi"],
    storage: "Se păstrează la frigider 3 zile sau congelator 2 luni.",
  },
  {
    id: "crochete-cartof-branza-cuptor",
    name: "Crochete de cartof cu brânză la cuptor",
    emoji: "🥔",
    mealType: "cina",
    time: "35 min",
    age: "10+ luni",
    difficulty: "Mediu",
    servings: "4-6",
    ingredients: [
      "3 cartofi medii",
      "½ cană brânză de vaci",
      "1 ou",
      "3 linguri făină",
      "1 lingură unt",
      "1 lingură ulei pentru tavă",
      "1 vârf mărar tocat",
    ],
    steps: [
      "Fierbe cartofii 20 minute. Pasează cu unt.",
      "Adaugă brânza, oul, 2 linguri făină și mărarul.",
      "Formează crochete mici (cilindre sau bile).",
      "Rostogolește prin restul de făină.",
      "Unge tava cu ulei.",
      "Coace la 200°C, 10 minute pe fiecare parte.",
      "Servește călduțe cu iaurt pe lângă.",
    ],
    allergens: ["Ou", "Lactoză", "Gluten"],
    relatedFoods: ["cartof", "branza-vaci", "ou", "iaurt"],
    storage: "Se păstrează la frigider 3 zile sau congelator 2 luni.",
  },
  {
    id: "mancare-spanac-ou",
    name: "Mâncare de spanac cu ou",
    emoji: "🥬",
    mealType: "cina",
    time: "20 min",
    age: "10+ luni",
    difficulty: "Ușor",
    servings: "2-3",
    ingredients: [
      "2 căni spanac proaspăt sau congelat",
      "1 ceapă mică",
      "1 lingură ulei",
      "1 lingură făină",
      "½ cană lapte",
      "2 ouă fierte tare",
      "1 vârf nucșoară",
    ],
    steps: [
      "Gătește spanacul 3 minute. Stoarce bine.",
      "Călește ceapa în ulei 3 minute.",
      "Adaugă făina, amestecă 1 minut.",
      "Toarnă laptele treptat. Gătește 3 minute.",
      "Adaugă spanacul stoarce și nucșoara.",
      "Fierbe ouăle 10 minute. Curăță și taie în sferturi.",
      "Servește spanacul cu ouăle deasupra.",
    ],
    allergens: ["Ou", "Lactoză", "Gluten"],
    relatedFoods: ["spanac", "ou"],
    storage: "Se păstrează la frigider 3 zile.",
  },
  {
    id: "mazare-morcov-pui-piure",
    name: "Piure de mazăre și morcov cu pui",
    emoji: "🫛",
    mealType: "cina",
    time: "30 min",
    age: "10+ luni",
    difficulty: "Mediu",
    servings: "2-3",
    ingredients: [
      "1 cană mazăre",
      "2 morcovi",
      "100g piept de pui",
      "1 lingură unt",
      "¼ cană apă de la fiert",
      "1 vârf mentă proaspătă (opțional)",
    ],
    steps: [
      "Fierbe pieptul de pui 25 minute. Sfărâmă fin.",
      "Fierbe morcovii 15 minute și mazărea 5 minute.",
      "Pasează legumele cu untul și puțină apă.",
      "Adaugă menta tocată fin.",
      "Pune piureul în castron, puiul deasupra.",
    ],
    allergens: ["Lactoză"],
    relatedFoods: ["mazare", "morcov", "pui"],
    storage: "Se păstrează la frigider 3 zile.",
  },
  {
    id: "paste-dovlecel-ras-unt",
    name: "Paste cu dovlecel ras și unt",
    emoji: "🥒",
    mealType: "cina",
    time: "15 min",
    age: "10+ luni",
    difficulty: "Ușor",
    servings: 1,
    ingredients: [
      "50g paste mici",
      "1 dovlecel mic ras",
      "1 lingură unt nesărat",
      "1 linguriță suc de lămâie",
      "1 vârf usturoi pudră",
      "1 linguriță brânză rasă (opțional)",
    ],
    steps: [
      "Fierbe pastele. Cu 2 minute înainte de final adaugă dovlecelul ras.",
      "Scurge, păstrând 2 linguri apă de la paste.",
      "Adaugă untul, apa păstrată, sucul de lămâie și usturoiul.",
      "Amestecă bine — untul și apa fac un sos cremos.",
      "Presară brânză rasă deasupra.",
    ],
    allergens: ["Lactoză", "Gluten"],
    relatedFoods: ["paste", "dovlecel"],
    storage: "Se servește proaspăt.",
  },
];
