export type FoodCategory =
  | "legume"
  | "fructe"
  | "proteine"
  | "cereale"
  | "grasimi"
  | "condimente";

export type AgeGroup = "6-7" | "7-8" | "8-10" | "10-12" | "6-8";

export interface Food {
  id: string;
  name: string;
  emoji: string;
  category: FoodCategory;
  ageGroup: AgeGroup;
  preparation: string;
  allergenInfo: string;
  nutrients: string[];
  relatedRecipes: string[];
}

// "100 de Alimente Înainte de 1 An" (în română), grupate pe categorie + grupă de vârstă.
// Notă: setul exact de mai jos este cel inclus în mesajul tău.
export const FOODS_DATABASE: Food[] = [
  // === LEGUME (Veggies) ===
  {
    id: "dovleac-butternut",
    name: "Dovleac plăcintar",
    emoji: "🎃",
    category: "legume",
    ageGroup: "6-8",
    preparation:
      "Curăță, taie cuburi, fierbe sau coace 20-25 min. Pasează fin.",
    allergenInfo: "Risc foarte scăzut de alergie.",
    nutrients: ["Vitamina A", "Vitamina C", "Potasiu"],
    relatedRecipes: ["supa-dovleac"],
  },
  {
    id: "kale",
    name: "Varză kale",
    emoji: "🥬",
    category: "legume",
    ageGroup: "6-8",
    preparation:
      "Îndepărtează nervurile, fierbe frunzele 10-15 min. Pasează cu alt legume.",
    allergenInfo: "Fără alergeni comuni.",
    nutrients: ["Fier", "Calciu", "Vitamina K"],
    relatedRecipes: [],
  },
  {
    id: "spanac",
    name: "Spanac",
    emoji: "🥬",
    category: "legume",
    ageGroup: "6-8",
    preparation: "Spală bine, fierbe 3-5 min. Pasează. Se combină bine cu cartof dulce.",
    allergenInfo: "Conține oxalați. Oferă în cantități moderate.",
    nutrients: ["Fier", "Vitamina K", "Acid folic"],
    relatedRecipes: [],
  },
  {
    id: "conopida",
    name: "Conopidă",
    emoji: "🥦",
    category: "legume",
    ageGroup: "6-8",
    preparation: "Spală, separă buchețelele, fierbe 12-15 min. Pasează fin.",
    allergenInfo: "Poate cauza gaze. Introduceți gradual.",
    nutrients: ["Vitamina C", "Vitamina K", "Fibre"],
    relatedRecipes: [],
  },
  {
    id: "cartof",
    name: "Cartof",
    emoji: "🥔",
    category: "legume",
    ageGroup: "6-8",
    preparation: "Curăță, taie cuburi, fierbe 15-20 min. Pasează cu lapte matern.",
    allergenInfo: "Risc foarte scăzut.",
    nutrients: ["Vitamina C", "Potasiu", "Vitamina B6"],
    relatedRecipes: [],
  },
  {
    id: "cartof-dulce",
    name: "Cartof dulce",
    emoji: "🍠",
    category: "legume",
    ageGroup: "6-8",
    preparation: "Curăță, taie, fierbe sau coace 25-30 min. Pasează — e natural dulce!",
    allergenInfo: "Risc foarte scăzut. Unul din primele alimente recomandate.",
    nutrients: ["Vitamina A", "Vitamina C", "Fibre"],
    relatedRecipes: ["piure-morcov"],
  },
  {
    id: "morcov",
    name: "Morcov",
    emoji: "🥕",
    category: "legume",
    ageGroup: "6-8",
    preparation: "Curăță, taie rondele, fierbe 15-20 min până e foarte moale. Pasează.",
    allergenInfo: "Risc scăzut. Rar poate cauza reacții ușoare.",
    nutrients: ["Vitamina A", "Vitamina K", "Fibre"],
    relatedRecipes: ["piure-morcov", "piure-pui"],
  },
  {
    id: "mazare",
    name: "Mazăre",
    emoji: "🫛",
    category: "legume",
    ageGroup: "6-8",
    preparation: "Fierbe mazărea 10 min. Pasează bine (cojile pot fi greu de digerat).",
    allergenInfo: "Leguminoasă — introduceți gradual.",
    nutrients: ["Proteine", "Fier", "Fibre"],
    relatedRecipes: [],
  },
  {
    id: "dovlecel",
    name: "Dovlecel",
    emoji: "🥒",
    category: "legume",
    ageGroup: "6-8",
    preparation: "Curăță, taie cuburi, fierbe 10-12 min. Pasează — e foarte ușor de digerat.",
    allergenInfo: "Unul dintre cele mai sigure alimente pentru debut.",
    nutrients: ["Vitamina C", "Potasiu", "Magneziu"],
    relatedRecipes: ["piure-dovlecel"],
  },
  {
    id: "ardei-gras",
    name: "Ardei gras",
    emoji: "🫑",
    category: "legume",
    ageGroup: "8-10",
    preparation: "Coace în cuptor 20 min, curăță coaja. Pasează sau taie mărunt.",
    allergenInfo: "Poate cauza gaze la unii bebeluși.",
    nutrients: ["Vitamina C", "Vitamina A", "Vitamina B6"],
    relatedRecipes: [],
  },
  {
    id: "vinete",
    name: "Vinete",
    emoji: "🍆",
    category: "legume",
    ageGroup: "8-10",
    preparation: "Coace în cuptor, scoate miezul, pasează cu puțin ulei de măsline.",
    allergenInfo: "Solanacee — unii bebeluși pot fi sensibili.",
    nutrients: ["Fibre", "Vitamina B1", "Potasiu"],
    relatedRecipes: [],
  },
  {
    id: "castravete",
    name: "Castravete",
    emoji: "🥒",
    category: "legume",
    ageGroup: "8-10",
    preparation:
      "Curăță, scoate semințele, rade pe răzătoare sau taie bețișoare subțiri.",
    allergenInfo: "Risc scăzut. Servește crud doar după 8 luni.",
    nutrients: ["Vitamina K", "Potasiu", "Hidratare"],
    relatedRecipes: [],
  },
  {
    id: "pastarnac",
    name: "Păstârnac",
    emoji: "🥕",
    category: "legume",
    ageGroup: "6-8",
    preparation: "Curăță, taie, fierbe 15-20 min. Pasează. Gust dulceag natural.",
    allergenInfo: "Risc scăzut.",
    nutrients: ["Fibre", "Vitamina C", "Acid folic"],
    relatedRecipes: [],
  },
  {
    id: "sparanghel",
    name: "Sparanghel",
    emoji: "🌿",
    category: "legume",
    ageGroup: "8-10",
    preparation: "Fierbe vârfurile 8-10 min. Pasează sau oferă ca finger food.",
    allergenInfo: "Risc scăzut.",
    nutrients: ["Acid folic", "Vitamina K", "Fibre"],
    relatedRecipes: [],
  },
  {
    id: "broccoli",
    name: "Broccoli",
    emoji: "🥦",
    category: "legume",
    ageGroup: "6-8",
    preparation: "Fierbe buchețelele 8-10 min la abur. Pasează sau oferă buchețele moi.",
    allergenInfo: "Poate cauza gaze. Introduceți gradual.",
    nutrients: ["Vitamina C", "Vitamina K", "Fier"],
    relatedRecipes: [],
  },
  {
    id: "rosii",
    name: "Roșii",
    emoji: "🍅",
    category: "legume",
    ageGroup: "8-10",
    preparation: "Opărește, curăță coaja, scoate semințele. Pasează sau taie mărunt.",
    allergenInfo: "Acid — poate irita. Introduceți după 8 luni.",
    nutrients: ["Vitamina C", "Licopen", "Vitamina A"],
    relatedRecipes: [],
  },
  {
    id: "fasole-verde",
    name: "Fasole verde",
    emoji: "🫘",
    category: "legume",
    ageGroup: "6-8",
    preparation: "Fierbe 12-15 min până e foarte moale. Pasează sau taie mărunt.",
    allergenInfo: "Risc scăzut.",
    nutrients: ["Fibre", "Vitamina C", "Vitamina K"],
    relatedRecipes: [],
  },
  {
    id: "usturoi",
    name: "Usturoi",
    emoji: "🧄",
    category: "legume",
    ageGroup: "8-10",
    preparation: "Adaugă un cățel în piureuri sau supe pentru aromă. Nu servi crud.",
    allergenInfo: "Risc scăzut. Cantități mici.",
    nutrients: ["Vitamina C", "Vitamina B6", "Mangan"],
    relatedRecipes: [],
  },
  {
    id: "sfecla",
    name: "Sfeclă",
    emoji: "🟣",
    category: "legume",
    ageGroup: "8-10",
    preparation: "Fierbe sau coace 45-60 min. Curăță și pasează. Colorează totul roz!",
    allergenInfo: "Conține nitrați. Oferă în cantități moderate.",
    nutrients: ["Acid folic", "Fier", "Fibre"],
    relatedRecipes: [],
  },
  {
    id: "porumb",
    name: "Porumb cremă",
    emoji: "🌽",
    category: "legume",
    ageGroup: "8-10",
    preparation: "Fierbe boabele, pasează foarte bine (cojile sunt greu de digerat).",
    allergenInfo: "Risc scăzut.",
    nutrients: ["Fibre", "Vitamina B", "Magneziu"],
    relatedRecipes: [],
  },
  {
    id: "ciuperci",
    name: "Ciuperci",
    emoji: "🍄",
    category: "legume",
    ageGroup: "10-12",
    preparation:
      "Gătește bine (nu servi crud). Taie mărunt sau pasează.",
    allergenInfo: "Introduceți după 10 luni. Doar ciuperci din comerț.",
    nutrients: ["Vitamina D", "Seleniu", "Vitamina B"],
    relatedRecipes: [],
  },

  // === FRUCTE ===
  {
    id: "banana",
    name: "Banană",
    emoji: "🍌",
    category: "fructe",
    ageGroup: "6-8",
    preparation:
      "Curăță și pasează cu furculița. Nu necesită gătire. Alege banane coapte.",
    allergenInfo: "Risc foarte scăzut. Ideal pentru început.",
    nutrients: ["Potasiu", "Vitamina B6", "Vitamina C"],
    relatedRecipes: ["piure-banana"],
  },
  {
    id: "ananas",
    name: "Ananas",
    emoji: "🍍",
    category: "fructe",
    ageGroup: "8-10",
    preparation:
      "Curăță, taie bucăți mici. Poți fierbe ușor pentru a reduce aciditatea.",
    allergenInfo: "Acid — poate irita pielea și gura.",
    nutrients: ["Vitamina C", "Mangan", "Bromelină"],
    relatedRecipes: [],
  },
  {
    id: "mere",
    name: "Mere",
    emoji: "🍎",
    category: "fructe",
    ageGroup: "6-8",
    preparation:
      "Curăță, taie, fierbe 10-12 min sau coace. Pasează. Nu servi crud la început.",
    allergenInfo: "Risc scăzut.",
    nutrients: ["Fibre", "Vitamina C", "Potasiu"],
    relatedRecipes: [],
  },
  {
    id: "pere",
    name: "Pere",
    emoji: "🍐",
    category: "fructe",
    ageGroup: "6-8",
    preparation: "Curăță, taie, fierbe 8-10 min. Pasează. Pere coapte pot fi și crude.",
    allergenInfo: "Unul dintre cele mai sigure fructe pentru debut.",
    nutrients: ["Fibre", "Vitamina C", "Vitamina K"],
    relatedRecipes: ["budinca-orez"],
  },
  {
    id: "curmale",
    name: "Curmale",
    emoji: "🫘",
    category: "fructe",
    ageGroup: "8-10",
    preparation:
      "Înmoaie în apă caldă 30 min, pasează. Foarte dulci natural.",
    allergenInfo: "Risc scăzut. Zahăr natural ridicat — cantități mici.",
    nutrients: ["Fier", "Potasiu", "Fibre"],
    relatedRecipes: [],
  },
  {
    id: "capsuni",
    name: "Căpșuni",
    emoji: "🍓",
    category: "fructe",
    ageGroup: "10-12",
    preparation: "Spală bine, taie în sferturi. Pasează pentru bebeluși mici.",
    allergenInfo: "Risc moderat de alergie. Monitorizează 3 zile.",
    nutrients: ["Vitamina C", "Mangan", "Acid folic"],
    relatedRecipes: [],
  },
  {
    id: "zmeura",
    name: "Zmeură",
    emoji: "🫐",
    category: "fructe",
    ageGroup: "8-10",
    preparation:
      "Spală, pasează prin sită pentru a elimina semințele.",
    allergenInfo: "Risc scăzut.",
    nutrients: ["Vitamina C", "Fibre", "Antioxidanți"],
    relatedRecipes: [],
  },
  {
    id: "kiwi",
    name: "Kiwi",
    emoji: "🥝",
    category: "fructe",
    ageGroup: "10-12",
    preparation: "Curăță, pasează sau taie cuburi mici. E acid — începe cu cantități mici.",
    allergenInfo: "Risc moderat. Poate cauza iritații ale gurii.",
    nutrients: ["Vitamina C", "Vitamina K", "Potasiu"],
    relatedRecipes: [],
  },
  {
    id: "afine",
    name: "Afine",
    emoji: "🫐",
    category: "fructe",
    ageGroup: "6-8",
    preparation: "Spală, pasează sau zdrobește. Nu oferi întregi (risc de sufocare).",
    allergenInfo: "Risc scăzut.",
    nutrients: ["Antioxidanți", "Vitamina C", "Vitamina K"],
    relatedRecipes: [],
  },
  {
    id: "grepfrut",
    name: "Grepfrut",
    emoji: "🍊",
    category: "fructe",
    ageGroup: "10-12",
    preparation: "Curăță complet de membrane. Oferă suc diluat sau bucăți mici.",
    allergenInfo: "Acid — poate irita. Introduceți târziu.",
    nutrients: ["Vitamina C", "Vitamina A", "Fibre"],
    relatedRecipes: [],
  },
  {
    id: "pepene-verde",
    name: "Pepene verde",
    emoji: "🍉",
    category: "fructe",
    ageGroup: "8-10",
    preparation: "Scoate toate semințele! Taie cuburi mici sau pasează.",
    allergenInfo: "Risc scăzut. Atenție la semințe.",
    nutrients: ["Vitamina C", "Vitamina A", "Hidratare"],
    relatedRecipes: [],
  },
  {
    id: "mango",
    name: "Mango",
    emoji: "🥭",
    category: "fructe",
    ageGroup: "6-8",
    preparation: "Curăță, taie de pe sâmbure, pasează. Foarte dulce natural.",
    allergenInfo: "Risc scăzut. Uneori reacție la pielea fructului.",
    nutrients: ["Vitamina A", "Vitamina C", "Acid folic"],
    relatedRecipes: [],
  },
  {
    id: "piersici",
    name: "Piersici",
    emoji: "🍑",
    category: "fructe",
    ageGroup: "6-8",
    preparation: "Opărește pentru a curăța coaja. Taie și pasează.",
    allergenInfo: "Risc scăzut-moderat.",
    nutrients: ["Vitamina C", "Vitamina A", "Potasiu"],
    relatedRecipes: [],
  },
  {
    id: "prune",
    name: "Prune",
    emoji: "🟣",
    category: "fructe",
    ageGroup: "6-8",
    preparation: "Fierbe prunele uscate 10 min, pasează. Excelent contra constipației.",
    allergenInfo: "Risc scăzut. Efect laxativ — cantități mici.",
    nutrients: ["Fibre", "Vitamina K", "Potasiu"],
    relatedRecipes: [],
  },
  {
    id: "portocale",
    name: "Portocale",
    emoji: "🍊",
    category: "fructe",
    ageGroup: "10-12",
    preparation: "Curăță complet de pielițe. Oferă felii sau suc diluat cu apă.",
    allergenInfo: "Citrice — risc moderat de iritație. Introduceți după 10 luni.",
    nutrients: ["Vitamina C", "Acid folic", "Potasiu"],
    relatedRecipes: [],
  },
  {
    id: "avocado",
    name: "Avocado",
    emoji: "🥑",
    category: "fructe",
    ageGroup: "6-8",
    preparation: "Taie în jumătate, scoate sâmburele, pasează cu furculița. Nu necesită gătire.",
    allergenInfo: "Risc foarte scăzut. Ideal pentru început — grăsimi sănătoase.",
    nutrients: ["Grăsimi sănătoase", "Vitamina K", "Potasiu"],
    relatedRecipes: ["piure-banana"],
  },
  {
    id: "struguri",
    name: "Struguri",
    emoji: "🍇",
    category: "fructe",
    ageGroup: "8-10",
    preparation: "ÎNTOTDEAUNA taie în jumătăți sau sferturi pe lungime. NICIODATĂ întregi!",
    allergenInfo: "Risc major de sufocare dacă sunt întregi! Taie obligatoriu.",
    nutrients: ["Vitamina C", "Vitamina K", "Antioxidanți"],
    relatedRecipes: [],
  },
  {
    id: "dovleac",
    name: "Dovleac",
    emoji: "🎃",
    category: "legume",
    ageGroup: "6-8",
    preparation: "Coace în cuptor 30-40 min sau fierbe cuburi 20 min. Pasează fin.",
    allergenInfo: "Risc foarte scăzut.",
    nutrients: ["Vitamina A", "Vitamina C", "Fibre"],
    relatedRecipes: ["supa-dovleac"],
  },

  // === PROTEINE ===
  {
    id: "pui",
    name: "Pui",
    emoji: "🍗",
    category: "proteine",
    ageGroup: "6-8",
    preparation: "Fierbe pieptul 25 min. Pasează foarte fin cu puțin bulion de legume.",
    allergenInfo: "Risc scăzut de alergie.",
    nutrients: ["Proteine", "Fier", "Zinc"],
    relatedRecipes: ["piure-pui"],
  },
  {
    id: "curcan",
    name: "Curcan",
    emoji: "🦃",
    category: "proteine",
    ageGroup: "6-8",
    preparation: "Fierbe sau coace. Pasează fin — carnea de curcan e mai uscată, adaugă lichid.",
    allergenInfo: "Risc scăzut.",
    nutrients: ["Proteine", "Fier", "Vitamina B12"],
    relatedRecipes: [],
  },
  {
    id: "vita",
    name: "Carne de vită",
    emoji: "🥩",
    category: "proteine",
    ageGroup: "8-10",
    preparation: "Fierbe bine, pasează sau rade pe răzătoare. Sursă excelentă de fier.",
    allergenInfo: "Risc scăzut.",
    nutrients: ["Fier hemic", "Zinc", "Vitamina B12"],
    relatedRecipes: [],
  },
  {
    id: "miel",
    name: "Miel",
    emoji: "🍖",
    category: "proteine",
    ageGroup: "10-12",
    preparation: "Fierbe sau coace fără grăsime vizibilă. Pasează sau taie foarte mărunt.",
    allergenInfo: "Risc scăzut.",
    nutrients: ["Fier", "Zinc", "Vitamina B12"],
    relatedRecipes: [],
  },
  {
    id: "ou",
    name: "Ou",
    emoji: "🥚",
    category: "proteine",
    ageGroup: "6-8",
    preparation: "6-8 luni: doar gălbenușul fiert tare. 10+ luni: ou întreg. Niciodată crud!",
    allergenInfo: "ALERGEN COMUN. Introduceți cu atenție, monitorizați 3-5 zile.",
    nutrients: ["Proteine", "Vitamina D", "Colină"],
    relatedRecipes: [],
  },
  {
    id: "peste-alb",
    name: "Pește alb",
    emoji: "🐟",
    category: "proteine",
    ageGroup: "6-8",
    preparation:
      "Fierbe sau coace la abur. Verifică TOATE oasele! Pasează sau sfărâmă.",
    allergenInfo: "ALERGEN COMUN. Introduceți cu atenție.",
    nutrients: ["Proteine", "Omega-3", "Vitamina D"],
    relatedRecipes: [],
  },
  {
    id: "somon",
    name: "Somon",
    emoji: "🐟",
    category: "proteine",
    ageGroup: "8-10",
    preparation: "Coace la abur fără sare. Sfărâmă și verifică oase. Excelent nutritiv!",
    allergenInfo: "ALERGEN COMUN (pește). Monitorizați.",
    nutrients: ["Omega-3 DHA", "Proteine", "Vitamina D"],
    relatedRecipes: [],
  },
  {
    id: "linte",
    name: "Linte",
    emoji: "🫘",
    category: "proteine",
    ageGroup: "6-8",
    preparation: "Fierbe lintea roșie 20-25 min (se desface singură). Perfectă pentru piureuri.",
    allergenInfo: "Leguminoasă — poate cauza gaze. Gradual.",
    nutrients: ["Fier", "Proteine", "Fibre"],
    relatedRecipes: [],
  },
  {
    id: "naut",
    name: "Năut (hummus)",
    emoji: "🫘",
    category: "proteine",
    ageGroup: "6-8",
    preparation: "Fierbe năutul 45 min sau folosește conservă (clătit bine). Pasează cu tahini.",
    allergenInfo: "Leguminoasă. Tahini conține susan — ALERGEN.",
    nutrients: ["Proteine", "Fier", "Fibre"],
    relatedRecipes: [],
  },
  {
    id: "branza-vaci",
    name: "Brânză de vaci",
    emoji: "🧀",
    category: "proteine",
    ageGroup: "8-10",
    preparation: "Servește ca atare sau amestecă în piureuri. Alege fără sare adăugată.",
    allergenInfo: "LACTOZĂ — monitorizați dacă există intoleranță.",
    nutrients: ["Calciu", "Proteine", "Vitamina B12"],
    relatedRecipes: [],
  },
  {
    id: "iaurt",
    name: "Iaurt natural",
    emoji: "🥛",
    category: "proteine",
    ageGroup: "6-8",
    preparation: "Iaurt natural fără zahăr. Poți amesteca cu piure de fructe.",
    allergenInfo: "LACTOZĂ — monitorizați. Iaurtul e mai ușor de digerat decât laptele.",
    nutrients: ["Calciu", "Probiotice", "Proteine"],
    relatedRecipes: [],
  },
  {
    id: "tofu",
    name: "Brânză de soia",
    emoji: "🧈",
    category: "proteine",
    ageGroup: "8-10",
    preparation: "Pasează sau taie cuburi moi. Se poate coace ușor.",
    allergenInfo: "SOIA — ALERGEN COMUN. Introduceți cu atenție.",
    nutrients: ["Proteine", "Calciu", "Fier"],
    relatedRecipes: [],
  },

  // === CEREALE (Grains) ===
  {
    id: "ovaz",
    name: "Fulgi de ovăz",
    emoji: "🥣",
    category: "cereale",
    ageGroup: "6-8",
    preparation: "Fierbe cu apă sau lapte matern 5 min. Pasează fin pentru primele porții.",
    allergenInfo: "Conține GLUTEN. Introduceți gradual, monitorizați.",
    nutrients: ["Fibre", "Fier", "Magneziu"],
    relatedRecipes: [],
  },
  {
    id: "quinoa",
    name: "Mei peruan",
    emoji: "🌾",
    category: "cereale",
    ageGroup: "6-8",
    preparation: "Clătește bine, fierbe 15 min. Pasează sau servește boabe (8+ luni).",
    allergenInfo: "Fără gluten. Risc scăzut.",
    nutrients: ["Proteine complete", "Fier", "Magneziu"],
    relatedRecipes: [],
  },
  {
    id: "orez",
    name: "Orez",
    emoji: "🍚",
    category: "cereale",
    ageGroup: "6-8",
    preparation: "Fierbe orezul foarte moale, pasează. Ideal ca primă cereală.",
    allergenInfo: "Fără gluten (orezul natural). Risc scăzut.",
    nutrients: ["Carbohidrați", "Vitamina B", "Fier"],
    relatedRecipes: ["budinca-orez"],
  },
  {
    id: "paste",
    name: "Paste mici",
    emoji: "🍝",
    category: "cereale",
    ageGroup: "8-10",
    preparation: "Fierbe paste mici foarte moi. Adaugă unt/ulei.",
    allergenInfo: "Conține GLUTEN. Există variante fără gluten.",
    nutrients: ["Carbohidrați", "Fier", "Vitamina B"],
    relatedRecipes: [],
  },
  {
    id: "paine",
    name: "Pâine moale pentru prăjit",
    emoji: "🍞",
    category: "cereale",
    ageGroup: "8-10",
    preparation: "Prăjește ușor, taie bețișoare subțiri. Ideal ca finger food.",
    allergenInfo: "Conține GLUTEN. Verifică ingredientele pentru alergeni.",
    nutrients: ["Carbohidrați", "Fibre", "Vitamine B"],
    relatedRecipes: [],
  },
  {
    id: "clatite",
    name: "Clătite moi",
    emoji: "🥞",
    category: "cereale",
    ageGroup: "10-12",
    preparation: "Fă din banană+ou+făină. Gătește pe foc mic. Taie în bețișoare.",
    allergenInfo: "Conține ou și posibil gluten.",
    nutrients: ["Carbohidrați", "Proteine", "Potasiu"],
    relatedRecipes: [],
  },

  // === GRĂSIMI (Fats) ===
  {
    id: "ulei-masline",
    name: "Ulei de măsline",
    emoji: "🫒",
    category: "grasimi",
    ageGroup: "6-8",
    preparation: "Adaugă 1 lingurița în piureuri. Nu încălzi la temperaturi mari.",
    allergenInfo: "Risc foarte scăzut.",
    nutrients: ["Grăsimi mono", "Vitamina E", "Antioxidanți"],
    relatedRecipes: ["piure-dovlecel"],
  },
  {
    id: "unt-cocos",
    name: "Unt de cocos",
    emoji: "🥥",
    category: "grasimi",
    ageGroup: "8-10",
    preparation: "Adaugă o linguriță în piureuri sau cereale.",
    allergenInfo: "NUCĂ DE COCOS — clasificat ca alergen arbori. Atenție.",
    nutrients: ["Grăsimi sănătoase", "Fier", "Fibre"],
    relatedRecipes: [],
  },
  {
    id: "nuci-macinate",
    name: "Nuci măcinate",
    emoji: "🥜",
    category: "grasimi",
    ageGroup: "6-8",
    preparation: "DOAR pudră/pastă fină! NICIODATĂ bucăți (risc sufocare). Amestecă în piureuri.",
    allergenInfo: "ALERGEN MAJOR. Introduceți foarte gradual, monitorizați atent.",
    nutrients: ["Omega-3", "Proteine", "Vitamina E"],
    relatedRecipes: [],
  },
  {
    id: "seminte-macinate",
    name: "Semințe măcinate",
    emoji: "🌻",
    category: "grasimi",
    ageGroup: "6-8",
    preparation: "Măcină semințe de chia/in/cânepă. Adaugă 1 linguriță în piureuri.",
    allergenInfo: "SESAM este alergen major. Chia/in sunt mai sigure.",
    nutrients: ["Omega-3", "Fibre", "Calciu"],
    relatedRecipes: [],
  },
  {
    id: "unt-arahide",
    name: "Unt de arahide",
    emoji: "🥜",
    category: "grasimi",
    ageGroup: "6-8",
    preparation: "Subțiază cu lapte matern. NICIODATĂ direct din linguriță (risc sufocare).",
    allergenInfo: "ALERGEN MAJOR. Studii recente recomandă introducerea timpurie sub supraveghere.",
    nutrients: ["Proteine", "Grăsimi sănătoase", "Vitamina E"],
    relatedRecipes: [],
  },
  {
    id: "unt-migdale",
    name: "Unt de migdale",
    emoji: "🌰",
    category: "grasimi",
    ageGroup: "6-8",
    preparation: "La fel ca untul de arahide — subțiază și amestecă în piureuri.",
    allergenInfo: "NUCI — ALERGEN MAJOR.",
    nutrients: ["Vitamina E", "Magneziu", "Calciu"],
    relatedRecipes: [],
  },

  // === CONDIMENTE (Herbs/Spices) — small amounts ===
  {
    id: "busuioc",
    name: "Busuioc",
    emoji: "🌿",
    category: "condimente",
    ageGroup: "6-8",
    preparation: "Adaugă câteva frunze proaspete tăiate fin în piureuri sau supe.",
    allergenInfo: "Risc foarte scăzut.",
    nutrients: ["Vitamina K", "Fier", "Calciu"],
    relatedRecipes: [],
  },
  {
    id: "scortisoara",
    name: "Scorțișoară",
    emoji: "🟤",
    category: "condimente",
    ageGroup: "8-10",
    preparation: "Un vârf de cuțit în piureuri de fructe sau cereale. Gust delicios!",
    allergenInfo: "Cantități foarte mici. Ceylon e mai bună decât Cassia.",
    nutrients: ["Antioxidanți", "Mangan", "Calciu"],
    relatedRecipes: [],
  },
  {
    id: "ghimbir",
    name: "Ghimbir",
    emoji: "🫚",
    category: "condimente",
    ageGroup: "8-10",
    preparation: "Rade o cantitate minusculă în supe sau piureuri.",
    allergenInfo: "Cantități foarte mici. Poate ajuta la digestie.",
    nutrients: ["Antioxidanți", "Gingerol", "Vitamina B6"],
    relatedRecipes: [],
  },
  {
    id: "turmeric",
    name: "Curcumă",
    emoji: "🟡",
    category: "condimente",
    ageGroup: "8-10",
    preparation: "Un vârf de cuțit în supe sau piureuri. Colorează totul galben!",
    allergenInfo: "Cantități foarte mici.",
    nutrients: ["Curcumină", "Antioxidanți", "Fier"],
    relatedRecipes: [],
  },
  {
    id: "chimion",
    name: "Chimion",
    emoji: "🌿",
    category: "condimente",
    ageGroup: "8-10",
    preparation: "Un vârf de cuțit în supe sau piureuri pentru aromă.",
    allergenInfo: "Cantități foarte mici.",
    nutrients: ["Antioxidanți"],
    relatedRecipes: [],
  },
  {
    id: "coriandru",
    name: "Coriandru",
    emoji: "🌿",
    category: "condimente",
    ageGroup: "8-10",
    preparation: "Un vârf de cuțit pentru aromă în mâncăruri pasate.",
    allergenInfo: "Cantități foarte mici.",
    nutrients: ["Antioxidanți"],
    relatedRecipes: [],
  },
  {
    id: "nucsoara",
    name: "Nucșoară",
    emoji: "🟤",
    category: "condimente",
    ageGroup: "10-12",
    preparation: "Doar un vârf de cuțit. Aromă intensă — folosește cantități mici.",
    allergenInfo: "Cantități foarte mici.",
    nutrients: ["Antioxidanți"],
    relatedRecipes: [],
  },
  {
    id: "boia-dulce",
    name: "Boia dulce",
    emoji: "🔴",
    category: "condimente",
    ageGroup: "8-10",
    preparation: "Un vârf de cuțit pentru aromă, în preparate pasate.",
    allergenInfo: "Cantități foarte mici.",
    nutrients: ["Antioxidanți"],
    relatedRecipes: [],
  },
  {
    id: "vanilie",
    name: "Vanilie",
    emoji: "🤎",
    category: "condimente",
    ageGroup: "6-8",
    preparation: "Un strop de aromă (foarte puțin) în piureuri dulci sau cereale.",
    allergenInfo: "Cantități foarte mici.",
    nutrients: ["Aromă"],
    relatedRecipes: [],
  },
  {
    id: "cardamom",
    name: "Cardamom",
    emoji: "🟢",
    category: "condimente",
    ageGroup: "10-12",
    preparation: "Doar un vârf de cuțit pentru aromă în preparate dulci sau sărate.",
    allergenInfo: "Cantități foarte mici.",
    nutrients: ["Antioxidanți"],
    relatedRecipes: [],
  },
  {
    id: "marar",
    name: "Mărar",
    emoji: "🌿",
    category: "condimente",
    ageGroup: "8-10",
    preparation: "Un praf mic în piureuri sau supe.",
    allergenInfo: "Cantități foarte mici.",
    nutrients: ["Aromă"],
    relatedRecipes: [],
  },
];

