import type { RecipeCatalogItem } from "./recipesDatabase";

export const GUSTARI_12PLUS_RECIPES: RecipeCatalogItem[] = [
  {
    id: "briose-cartof-dulce-mazare-12",
    name: "Brioșe cu cartof dulce și mazăre",
    emoji: "🧁",
    mealType: "gustare",
    time: "30 min",
    age: "12+ luni",
    difficulty: "Mediu",
    servings: "6-8",
    ingredients: [
      "150g cartof dulce fiert și pasat",
      "80g mazăre fiartă",
      "50g ou (1 ou)",
      "50g făină de speltă sau 60g făină de ovăz",
    ],
    steps: [
      "Amestecă toate ingredientele.",
      "Pune în forme de brioșe.",
      "Coace la 180°C, 20-25 minute.",
      "Răcește complet înainte de servit.",
    ],
    allergens: ["Ou", "Gluten"],
    relatedFoods: ["cartof-dulce", "mazare", "ou"],
    storage: "Se păstrează la frigider 3 zile sau congelator 2 luni.",
  },
  {
    id: "briose-dovleac-nuci-12",
    name: "Brioșe cu dovleac și nuci pecan",
    emoji: "🧁",
    mealType: "gustare",
    time: "30 min",
    age: "12+ luni",
    difficulty: "Mediu",
    servings: "6-8",
    ingredients: [
      "150g dovleac copt și pasat",
      "50g ou (1 ou)",
      "10g nuci pecan măcinate",
      "50g făină de speltă sau 60g făină de ovăz",
    ],
    steps: [
      "Amestecă ingredientele.",
      "Pune în forme. Coace la 180°C, 20-25 minute.",
    ],
    allergens: ["Ou", "Nuci", "Gluten"],
    relatedFoods: ["dovleac", "ou"],
    storage: "Se păstrează la frigider 3 zile sau congelator 2 luni.",
  },
  {
    id: "briose-sfecla-ou-12",
    name: "Brioșe cu sfeclă și ou",
    emoji: "🧁",
    mealType: "gustare",
    time: "30 min",
    age: "12+ luni",
    difficulty: "Mediu",
    servings: "6-8",
    ingredients: [
      "120g sfeclă fiartă și rasă",
      "50g ou (1 ou)",
      "50g făină de speltă sau 60g făină de ovăz",
    ],
    steps: [
      "Amestecă ingredientele.",
      "Pune în forme. Coace la 180°C, 20-25 minute.",
    ],
    allergens: ["Ou", "Gluten"],
    relatedFoods: ["sfecla", "ou"],
    storage: "Se păstrează la frigider 3 zile sau congelator 2 luni.",
  },
  {
    id: "biscuiti-banana-unt-arahide-12",
    name: "Biscuiți cu banană și unt de arahide",
    emoji: "🍪",
    mealType: "gustare",
    time: "25 min",
    age: "12+ luni",
    difficulty: "Ușor",
    servings: "10-12",
    ingredients: [
      "100g banană pasată",
      "20g unt de arahide 100%",
      "70g făină de speltă sau 80g făină de ovăz",
    ],
    steps: [
      "Amestecă ingredientele.",
      "Formează biscuiți. Coace la 180°C, 15-18 minute.",
      "Răcește complet.",
    ],
    allergens: ["Arahide", "Gluten"],
    relatedFoods: ["banana", "unt-arahide"],
    storage: "Se păstrează în cutie închisă 3 zile.",
  },
  {
    id: "biscuiti-mar-scortisoara-12",
    name: "Biscuiți cu măr și scorțișoară",
    emoji: "🍪",
    mealType: "gustare",
    time: "25 min",
    age: "12+ luni",
    difficulty: "Ușor",
    servings: "10-12",
    ingredients: [
      "120g măr ras",
      "1 linguriță scorțișoară",
      "70g făină de speltă sau 80g făină de ovăz",
    ],
    steps: [
      "Amestecă ingredientele.",
      "Formează biscuiți. Coace la 180°C, 15-18 minute.",
    ],
    allergens: ["Gluten"],
    relatedFoods: ["mere", "scortisoara"],
    storage: "Se păstrează în cutie închisă 3 zile.",
  },
  {
    id: "biscuiti-banana-ovaz-12",
    name: "Biscuiți cu banană și ovăz",
    emoji: "🍪",
    mealType: "gustare",
    time: "25 min",
    age: "12+ luni",
    difficulty: "Ușor",
    servings: "10-12",
    ingredients: [
      "100g banană pasată",
      "80g făină de ovăz",
    ],
    steps: [
      "Amestecă banana cu făina.",
      "Formează biscuiți. Coace la 180°C, 15-18 minute.",
    ],
    allergens: ["Gluten"],
    relatedFoods: ["banana", "ovaz"],
    storage: "Se păstrează în cutie închisă 3 zile.",
  },
  {
    id: "tarta-branza-piersici-12",
    name: "Tartă cu brânzică și piersici",
    emoji: "🥧",
    mealType: "gustare",
    time: "40 min",
    age: "12+ luni",
    difficulty: "Mediu",
    servings: "6-8",
    ingredients: [
      "100g brânzică de casă",
      "120g piersici feliate",
      "30g unt",
      "100g făină de speltă sau 110g făină de ovăz",
    ],
    steps: [
      "Amestecă făina cu untul și brânzica.",
      "Adaugă piersicile.",
      "Coace la 180°C, 30-35 minute.",
    ],
    allergens: ["Lactoză", "Gluten"],
    relatedFoods: ["branza-vaci", "piersici"],
    storage: "Se păstrează la frigider 3 zile.",
  },
  {
    id: "tarta-fructe-padure-12",
    name: "Tartă cu fructe de pădure",
    emoji: "🥧",
    mealType: "gustare",
    time: "40 min",
    age: "12+ luni",
    difficulty: "Mediu",
    servings: "6-8",
    ingredients: [
      "150g afine, zmeură, mure amestecate",
      "30g unt",
      "100g făină de speltă sau 110g făină de ovăz",
    ],
    steps: [
      "Amestecă făina cu untul.",
      "Adaugă fructele.",
      "Coace la 180°C, 30-35 minute.",
    ],
    allergens: ["Lactoză", "Gluten"],
    relatedFoods: ["afine", "zmeura"],
    storage: "Se păstrează la frigider 3 zile.",
  },
  {
    id: "chec-zmeura-banana-afine-12",
    name: "Chec cu zmeură, banană și afine",
    emoji: "🍰",
    mealType: "gustare",
    time: "45 min",
    age: "12+ luni",
    difficulty: "Mediu",
    servings: "8-10",
    ingredients: [
      "50g ou (1 ou)",
      "100g banană pasată",
      "60g zmeură",
      "60g afine",
      "120g făină de speltă sau 130g făină de ovăz",
    ],
    steps: [
      "Amestecă oul cu banana.",
      "Adaugă fructele și făina.",
      "Coace la 180°C, 35-40 minute.",
      "Verifică cu scobitoarea. Răcește complet.",
    ],
    allergens: ["Ou", "Gluten"],
    relatedFoods: ["banana", "zmeura", "afine", "ou"],
    storage: "Se păstrează la frigider 3 zile sau congelator 2 luni.",
  },
  {
    id: "chec-mango-caju-12",
    name: "Chec cu mango și caju",
    emoji: "🍰",
    mealType: "gustare",
    time: "45 min",
    age: "12+ luni",
    difficulty: "Mediu",
    servings: "8-10",
    ingredients: [
      "50g ou (1 ou)",
      "120g mango pasat",
      "20g nuci caju măcinate",
      "120g făină de speltă sau 130g făină de ovăz",
    ],
    steps: [
      "Amestecă oul cu mango pasat.",
      "Adaugă cajul și făina.",
      "Coace la 180°C, 35-40 minute.",
    ],
    allergens: ["Ou", "Nuci", "Gluten"],
    relatedFoods: ["mango", "ou"],
    storage: "Se păstrează la frigider 3 zile sau congelator 2 luni.",
  },
  {
    id: "chiftele-pui-broccoli-dovlecel-12",
    name: "Chifteluțe din piept de pui, broccoli și dovlecel",
    emoji: "🍗",
    mealType: "gustare",
    time: "35 min",
    age: "12+ luni",
    difficulty: "Mediu",
    servings: "8-10",
    ingredients: [
      "150g piept de pui fiert și tocat",
      "80g broccoli fiert",
      "80g dovlecel ras",
      "50g ou (1 ou)",
      "30g făină de speltă sau 40g făină de ovăz",
    ],
    steps: [
      "Combină toate ingredientele.",
      "Formează chifteluțe mici.",
      "Coace la 180°C, 25-30 minute.",
    ],
    allergens: ["Ou", "Gluten"],
    relatedFoods: ["pui", "broccoli", "dovlecel", "ou"],
    storage: "Se păstrează la frigider 3 zile sau congelator 2 luni.",
  },
  {
    id: "chiftele-somon-cartof-dulce-12",
    name: "Chifteluțe din somon cu cartof dulce și mărar",
    emoji: "🐟",
    mealType: "gustare",
    time: "35 min",
    age: "12+ luni",
    difficulty: "Mediu",
    servings: "8-10",
    ingredients: [
      "150g somon gătit",
      "120g cartof dulce fiert și pasat",
      "1 lingură mărar",
      "50g ou (1 ou)",
      "30g făină de speltă sau 40g făină de ovăz",
    ],
    steps: [
      "Verifică somonul de oase! Sfărâmă.",
      "Combină cu restul ingredientelor.",
      "Formează chifteluțe. Coace la 180°C, 25-30 minute.",
    ],
    allergens: ["Pește", "Ou", "Gluten"],
    relatedFoods: ["somon", "cartof-dulce", "ou"],
    storage: "Se păstrează la frigider 2 zile sau congelator 1 lună.",
  },
  {
    id: "biluze-zmeura-arahide-cocos-12",
    name: "Biluțe cu zmeură, unt de arahide și cocos",
    emoji: "🫐",
    mealType: "gustare",
    time: "10 min",
    age: "12+ luni",
    difficulty: "Ușor",
    servings: "8-10",
    ingredients: [
      "80g zmeură pasată",
      "30g unt de arahide 100%",
      "30g fulgi de cocos",
    ],
    steps: [
      "Amestecă ingredientele.",
      "Formează biluțe.",
      "Păstrează la frigider 2 zile sau congelator 1 lună.",
    ],
    allergens: ["Arahide", "Nucă de cocos"],
    relatedFoods: ["zmeura", "unt-arahide"],
    storage: "Frigider 2 zile sau congelator 1 lună.",
  },
  {
    id: "biluze-avocado-piersica-cocos-12",
    name: "Biluțe cu avocado, piersică și cocos",
    emoji: "🥑",
    mealType: "gustare",
    time: "10 min",
    age: "12+ luni",
    difficulty: "Ușor",
    servings: "6-8",
    ingredients: [
      "80g avocado pasat",
      "80g piersică pasată",
      "30g fulgi de cocos",
    ],
    steps: [
      "Amestecă avocado cu piersica și cocosul.",
      "Formează biluțe.",
      "Păstrează la rece.",
    ],
    allergens: ["Nucă de cocos"],
    relatedFoods: ["avocado", "piersici"],
    storage: "Frigider 1 zi (avocado se oxidează).",
  },
  {
    id: "biluze-mar-crema-branza-12",
    name: "Biluțe cu măr, cremă de brânză și scorțișoară",
    emoji: "🍎",
    mealType: "gustare",
    time: "10 min",
    age: "12+ luni",
    difficulty: "Ușor",
    servings: "6-8",
    ingredients: [
      "100g măr ras",
      "40g cremă de brânză",
      "un vârf scorțișoară",
    ],
    steps: [
      "Amestecă ingredientele.",
      "Formează biluțe.",
      "Păstrează la frigider.",
    ],
    allergens: ["Lactoză"],
    relatedFoods: ["mere", "branza-vaci", "scortisoara"],
    storage: "Frigider 2 zile.",
  },
  {
    id: "tarta-iaurt-zmeura-12",
    name: "Tartă cu iaurt și zmeură",
    emoji: "🥧",
    mealType: "gustare",
    time: "40 min",
    age: "12+ luni",
    difficulty: "Mediu",
    servings: "6-8",
    ingredients: [
      "120g iaurt grecesc 10%",
      "100g zmeură",
      "100g făină de speltă sau 110g făină de ovăz",
    ],
    steps: [
      "Amestecă iaurtul cu zmeura.",
      "Adaugă făina.",
      "Coace la 180°C, 30-35 minute.",
    ],
    allergens: ["Lactoză", "Gluten"],
    relatedFoods: ["iaurt", "zmeura"],
    storage: "Se păstrează la frigider 3 zile.",
  },
];
