import type { RecipeCatalogItem } from "./recipesDatabase";

/** Mic dejun 8+ — completare până la 20 (9 existente în MIC_DEJUN + 11 aici). */
export const MIC_DEJUN_8PLUS_EXTRA: RecipeCatalogItem[] = [
  {
    id: "terci-mei-banana-scortisoara",
    name: "Terci de mei cu banană și scorțișoară",
    emoji: "🌾",
    mealType: "mic-dejun",
    time: "20 min",
    age: "8+ luni",
    difficulty: "Ușor",
    servings: "1-2",
    ingredients: [
      "¼ cană mei",
      "¾ cană apă",
      "¼ cană lapte",
      "½ banană",
      "1 vârf scorțișoară",
      "1 linguriță unt (opțional)",
    ],
    steps: [
      "Clătește meiul bine sub jet de apă.",
      "Fierbe cu apa 15 minute la foc mic.",
      "Adaugă laptele, gătește 3 minute.",
      "Pasează banana și amestecă-o în terci.",
      "Adaugă scorțișoara și untul.",
    ],
    allergens: ["Lactoză"],
    relatedFoods: ["banana", "scortisoara"],
    storage: "Se păstrează la frigider 2 zile.",
  },
  {
    id: "clatite-ovaz-mar-8",
    name: "Clătite de ovăz cu măr ras",
    emoji: "🥞",
    mealType: "mic-dejun",
    time: "20 min",
    age: "8+ luni",
    difficulty: "Mediu",
    servings: "3-4",
    ingredients: [
      "1 cană fulgi de ovăz (măcinați)",
      "1 ou",
      "½ cană lapte",
      "1 măr ras",
      "1 vârf scorțișoară",
      "2 linguri ulei de cocos",
    ],
    steps: [
      "Mixează fulgii de ovăz fin (sau folosește făină de ovăz).",
      "Amestecă cu oul, laptele și scorțișoara.",
      "Rade mărul și adaugă-l în aluat.",
      "Încălzește uleiul la foc mediu.",
      "Pune câte 2 linguri de aluat, aplatizează.",
      "Gătește 2-3 minute pe fiecare parte.",
      "Servește călduțe.",
    ],
    allergens: ["Ou", "Lactoză", "Gluten"],
    relatedFoods: ["ovaz", "mere"],
    storage: "Se păstrează la frigider 2 zile sau congelator 2 luni.",
  },
  {
    id: "budinca-chia-piersici",
    name: "Budincă de chia cu piersici",
    emoji: "🍑",
    mealType: "mic-dejun",
    time: "5 min + peste noapte",
    age: "8+ luni",
    difficulty: "Ușor",
    servings: "2-3",
    ingredients: [
      "3 linguri semințe chia",
      "1 cană lapte",
      "½ piersică pasată",
      "1 vârf vanilie (opțional)",
      "1 vârf nuci măcinate (opțional)",
    ],
    steps: [
      "Amestecă semințele de chia cu laptele.",
      "Adaugă piersica pasată și vanilia.",
      "Pune la frigider peste noapte (minim 2 ore).",
      "Dimineața: amestecă bine.",
      "Presară nuci măcinate deasupra.",
    ],
    allergens: ["Lactoză", "Nuci"],
    relatedFoods: ["piersici", "seminte-macinate"],
    storage: "Se păstrează la frigider 3 zile.",
  },
  {
    id: "omleta-morcov-branza-8",
    name: "Omletă cu morcov ras și brânză",
    emoji: "🥕",
    mealType: "mic-dejun",
    time: "15 min",
    age: "8+ luni",
    difficulty: "Ușor",
    servings: 1,
    ingredients: [
      "2 ouă",
      "1 morcov mic ras",
      "2 linguri brânză de vaci",
      "1 linguriță ulei",
      "1 vârf mărar (opțional)",
    ],
    steps: [
      "Bate ouăle. Adaugă morcovul ras și brânza.",
      "Încălzește uleiul într-o tigaie mică.",
      "Toarnă amestecul, acoperă.",
      "Gătește la foc mic 5-7 minute.",
      "Taie în bețișoare. Presară mărar.",
    ],
    allergens: ["Ou", "Lactoză"],
    relatedFoods: ["ou", "morcov", "branza-vaci"],
    storage: "Se păstrează la frigider 2 zile.",
  },
  {
    id: "terci-quinoa-mango",
    name: "Terci de quinoa cu mango",
    emoji: "🥭",
    mealType: "mic-dejun",
    time: "20 min",
    age: "8+ luni",
    difficulty: "Ușor",
    servings: "1-2",
    ingredients: [
      "¼ cană quinoa",
      "½ cană apă",
      "¼ cană lapte",
      "½ mango copt",
      "1 vârf cardamom (opțional)",
    ],
    steps: [
      "Clătește quinoa. Fierbe cu apa 15 minute.",
      "Adaugă laptele, gătește 3 minute.",
      "Pasează mango și amestecă-l în terci.",
      "Adaugă cardamom. Servește călduț.",
    ],
    allergens: ["Lactoză"],
    relatedFoods: ["quinoa", "mango"],
    storage: "Se păstrează la frigider 2 zile.",
  },
  {
    id: "toast-ricotta-avocado-susan",
    name: "Toast cu ricotta, avocado și susan",
    emoji: "🥑",
    mealType: "mic-dejun",
    time: "5 min",
    age: "8+ luni",
    difficulty: "Ușor",
    servings: 1,
    ingredients: [
      "1 felie pâine toast",
      "2 linguri ricotta",
      "½ avocado",
      "1 vârf semințe de susan",
      "1 vârf suc de lămâie",
    ],
    steps: [
      "Prăjește pâinea ușor.",
      "Întinde ricotta pe toast.",
      "Pasează avocado cu sucul de lămâie, pune deasupra.",
      "Presară semințe de susan.",
      "Taie în bețișoare.",
    ],
    allergens: ["Lactoză", "Susan", "Gluten"],
    relatedFoods: ["avocado", "branza-vaci", "paine"],
    storage: "Se servește proaspăt.",
  },
  {
    id: "piure-prune-ovaz",
    name: "Terci de ovăz cu piure de prune",
    emoji: "🟣",
    mealType: "mic-dejun",
    time: "15 min",
    age: "8+ luni",
    difficulty: "Ușor",
    servings: 1,
    ingredients: [
      "¼ cană fulgi de ovăz",
      "½ cană apă",
      "¼ cană lapte",
      "3-4 prune uscate",
      "1 vârf scorțișoară",
    ],
    steps: [
      "Înmoaie prunele 10 minute în apă caldă. Pasează-le.",
      "Fierbe apa cu laptele, adaugă fulgii de ovăz.",
      "Gătește 5 minute. Acoperă 3 minute.",
      "Amestecă piureul de prune și scorțișoara.",
    ],
    allergens: ["Lactoză", "Gluten"],
    relatedFoods: ["ovaz", "prune"],
    storage: "Se păstrează la frigider 2 zile.",
  },
  {
    id: "scramble-ou-spanac-cartof",
    name: "Scramble de ou cu spanac și cartof dulce",
    emoji: "🍠",
    mealType: "mic-dejun",
    time: "20 min",
    age: "8+ luni",
    difficulty: "Mediu",
    servings: 1,
    ingredients: [
      "2 ouă",
      "¼ cană cartof dulce fiert și pasat",
      "¼ cană spanac tocat",
      "1 linguriță unt",
      "1 vârf turmeric (opțional)",
    ],
    steps: [
      "Fierbe cartoful dulce în cuburi 15 minute. Pasează.",
      "Topește untul la foc mic.",
      "Adaugă spanacul, gătește 2 minute.",
      "Bate ouăle cu turmericul, toarnă peste spanac.",
      "Amestecă des până sunt pufoase.",
      "Servește cu cartoful dulce pasat pe lângă.",
    ],
    allergens: ["Ou", "Lactoză"],
    relatedFoods: ["ou", "spanac", "cartof-dulce", "turmeric"],
    storage: "Se servește proaspăt.",
  },
  {
    id: "pere-fierte-ricotta",
    name: "Pere fierte cu ricotta și scorțișoară",
    emoji: "🍐",
    mealType: "mic-dejun",
    time: "15 min",
    age: "8+ luni",
    difficulty: "Ușor",
    servings: 1,
    ingredients: [
      "1 pară",
      "¼ cană ricotta",
      "1 vârf scorțișoară",
      "1 vârf nuci măcinate (opțional)",
    ],
    steps: [
      "Curăță para, taie în felii.",
      "Fierbe feliile în puțină apă 10 minute.",
      "Pune ricotta în castron.",
      "Adaugă perele fierte deasupra.",
      "Presară scorțișoară și nuci măcinate.",
    ],
    allergens: ["Lactoză", "Nuci"],
    relatedFoods: ["pere", "branza-vaci", "scortisoara", "nuci-macinate"],
    storage: "Se păstrează la frigider 2 zile.",
  },
  {
    id: "paste-mic-dejun-branza-ou",
    name: "Paste de mic dejun cu brânză și ou",
    emoji: "🍝",
    mealType: "mic-dejun",
    time: "15 min",
    age: "8+ luni",
    difficulty: "Ușor",
    servings: 1,
    ingredients: [
      "50g paste mici (stelline)",
      "1 ou",
      "2 linguri brânză de vaci",
      "1 linguriță unt",
      "1 vârf mărar tocat",
    ],
    steps: [
      "Fierbe pastele. Scurge.",
      "Bate oul, amestecă cu brânza.",
      "Pune pastele calde în castron.",
      "Adaugă amestecul de ou și brânză — căldura gătește oul.",
      "Amestecă cu unt și mărar.",
    ],
    allergens: ["Ou", "Lactoză", "Gluten"],
    relatedFoods: ["paste", "ou", "branza-vaci"],
    storage: "Se servește proaspăt.",
  },
  {
    id: "terci-orez-pere-8",
    name: "Terci de orez cu pere",
    emoji: "🍐",
    mealType: "mic-dejun",
    time: "20 min",
    age: "8+ luni",
    difficulty: "Ușor",
    servings: "1-2",
    ingredients: [
      "¼ cană orez rotund",
      "¾ cană apă",
      "¼ cană lapte",
      "½ pară",
      "1 vârf vanilie (opțional)",
    ],
    steps: [
      "Clătește orezul. Fierbe cu apa 15 minute la foc mic.",
      "Curăță para, taie cuburi mici.",
      "Adaugă para și laptele, gătește 5 minute.",
      "Pasează ușor sau lasă cu textură mică, după vârstă.",
      "Adaugă vanilia. Servește călduț.",
    ],
    allergens: ["Lactoză"],
    relatedFoods: ["orez", "pere"],
    storage: "Se păstrează la frigider 2 zile.",
  },
];

/** Mic dejun 10+ — 20 rețete noi (în plus față de cele existente în alte batch-uri). */
export const MIC_DEJUN_10PLUS_EXTRA: RecipeCatalogItem[] = [
  {
    id: "pancake-banane-ovaz-10",
    name: "Pancake cu banane și ovăz (fără făină)",
    emoji: "🥞",
    mealType: "mic-dejun",
    time: "15 min",
    age: "10+ luni",
    difficulty: "Ușor",
    servings: "2-3",
    ingredients: [
      "1 banană coaptă",
      "1 ou",
      "½ cană fulgi de ovăz",
      "1 vârf scorțișoară",
      "1 linguriță ulei de cocos",
    ],
    steps: [
      "Pasează banana. Amestecă cu oul și fulgii de ovăz.",
      "Adaugă scorțișoara. Lasă 5 minute.",
      "Încălzește uleiul la foc mediu.",
      "Pune câte 1 lingură de aluat.",
      "Gătește 2 minute pe fiecare parte.",
      "Servește călduțe cu iaurt pe lângă.",
    ],
    allergens: ["Ou", "Gluten"],
    relatedFoods: ["banana", "ovaz", "ou"],
    storage: "Se păstrează la frigider 2 zile sau congelator 2 luni.",
  },
  {
    id: "muffins-morcov-mere-10",
    name: "Mini muffins de morcov și mere",
    emoji: "🧁",
    mealType: "mic-dejun",
    time: "30 min",
    age: "10+ luni",
    difficulty: "Mediu",
    servings: "6-8",
    ingredients: [
      "1 cană făină integrală",
      "1 linguriță praf de copt",
      "1 ou",
      "¼ cană ulei",
      "½ cană iaurt natural",
      "1 morcov ras",
      "1 măr ras",
      "1 vârf scorțișoară",
    ],
    steps: [
      "Preîncălzește cuptorul la 180°C.",
      "Amestecă ingredientele uscate (făina, praful de copt, scorțișoara).",
      "Separat amestecă oul, uleiul și iaurtul.",
      "Combină uscatele cu umedele. Nu amesteca prea mult.",
      "Adaugă morcovul și mărul ras.",
      "Toarnă în forme de mini muffins.",
      "Coace 18-20 minute. Răcește complet.",
    ],
    allergens: ["Ou", "Lactoză", "Gluten"],
    relatedFoods: ["morcov", "mere", "ou", "iaurt"],
    storage: "Se păstrează la frigider 3 zile sau congelator 2 luni.",
  },
  {
    id: "gris-lapte-fructe-10",
    name: "Griș cu lapte și fructe de sezon",
    emoji: "🥣",
    mealType: "mic-dejun",
    time: "15 min",
    age: "10+ luni",
    difficulty: "Ușor",
    servings: "1-2",
    ingredients: [
      "3 linguri griș",
      "1 cană lapte",
      "½ banană sau alte fructe",
      "1 linguriță unt",
      "1 vârf vanilie (opțional)",
    ],
    steps: [
      "Fierbe laptele.",
      "Toarnă grișul în ploaie, amestecând continuu.",
      "Gătește 3-4 minute la foc mic amestecând.",
      "Adaugă untul și vanilia.",
      "Taie fructele și pune-le deasupra.",
    ],
    allergens: ["Lactoză", "Gluten"],
    relatedFoods: ["banana"],
    storage: "Se servește proaspăt.",
  },
  {
    id: "ou-fiert-soldati-toast",
    name: 'Ou fiert moale cu „soldăței" de toast',
    emoji: "🥚",
    mealType: "mic-dejun",
    time: "10 min",
    age: "10+ luni",
    difficulty: "Ușor",
    servings: 1,
    ingredients: [
      "1 ou",
      "1 felie pâine toast",
      "1 linguriță unt",
      "½ avocado (opțional)",
    ],
    steps: [
      "Fierbe oul 7-8 minute (gălbenușul să fie aproape fiert complet).",
      "Prăjește pâinea, unge cu unt.",
      "Taie toast-ul în bețișoare (soldăței).",
      "Pune oul într-un suport, decapitează-l.",
      "Bebelușul înmoaie soldățeii în ou!",
      "Servește cu avocado feliat pe lângă.",
    ],
    allergens: ["Ou", "Lactoză", "Gluten"],
    relatedFoods: ["ou", "paine", "avocado"],
    storage: "Se servește proaspăt.",
  },
  {
    id: "smoothie-bowl-fructe-10",
    name: "Smoothie bowl cu fructe și semințe",
    emoji: "🍓",
    mealType: "mic-dejun",
    time: "5 min",
    age: "10+ luni",
    difficulty: "Ușor",
    servings: 1,
    ingredients: [
      "½ banană congelată",
      "¼ cană afine",
      "½ cană iaurt natural",
      "1 linguriță unt de arahide",
      "1 vârf semințe de cânepă",
      "1 vârf fulgi de cocos",
    ],
    steps: [
      "Mixează banana congelată cu afinele și iaurtul.",
      "Trebuie să fie gros, nu lichid!",
      "Toarnă în castron.",
      "Adaugă untul de arahide deasupra.",
      "Presară semințe de cânepă și fulgi de cocos.",
    ],
    allergens: ["Lactoză", "Arahide", "Nucă de cocos"],
    relatedFoods: ["banana", "afine", "iaurt", "unt-arahide"],
    storage: "Se servește proaspăt.",
  },
  {
    id: "briose-dovleac-ovaz-10",
    name: "Brioșe de dovleac și ovăz",
    emoji: "🎃",
    mealType: "mic-dejun",
    time: "30 min",
    age: "10+ luni",
    difficulty: "Mediu",
    servings: "6-8",
    ingredients: [
      "1 cană fulgi de ovăz (măcinați)",
      "½ cană piure de dovleac",
      "1 ou",
      "¼ cană ulei",
      "¼ cană iaurt",
      "1 linguriță praf de copt",
      "1 vârf scorțișoară și nucșoară",
    ],
    steps: [
      "Preîncălzește cuptorul la 180°C.",
      "Amestecă fulgii de ovăz măcinați cu praful de copt și condimentele.",
      "Separat: ou, ulei, iaurt și piure de dovleac.",
      "Combină. Toarnă în forme de brioșe.",
      "Coace 20 minute.",
      "Răcește complet înainte de a servi.",
    ],
    allergens: ["Ou", "Lactoză", "Gluten"],
    relatedFoods: ["ovaz", "dovleac", "ou"],
    storage: "Se păstrează la frigider 3 zile sau congelator 2 luni.",
  },
  {
    id: "orez-lapte-mere-scortisoara-10",
    name: "Orez cu lapte și mere fierte",
    emoji: "🍚",
    mealType: "mic-dejun",
    time: "25 min",
    age: "10+ luni",
    difficulty: "Ușor",
    servings: "2-3",
    ingredients: [
      "½ cană orez rotund",
      "1½ căni lapte",
      "1 măr",
      "1 linguriță unt",
      "1 vârf scorțișoară",
      "1 vârf vanilie",
    ],
    steps: [
      "Fierbe orezul cu laptele la foc mic 20 minute, amestecând.",
      "Curăță mărul, taie în cuburi mici.",
      "Gătește mărul separat cu 2 linguri apă 10 minute.",
      "Amestecă orezul cu untul și vanilia.",
      "Pune merele fierte deasupra. Presară scorțișoară.",
    ],
    allergens: ["Lactoză"],
    relatedFoods: ["orez", "mere", "scortisoara"],
    storage: "Se păstrează la frigider 2 zile.",
  },
  {
    id: "tortita-cartof-dulce-ou-10",
    name: "Tortițe de cartof dulce cu ou",
    emoji: "🍠",
    mealType: "mic-dejun",
    time: "25 min",
    age: "10+ luni",
    difficulty: "Mediu",
    servings: "2-3",
    ingredients: [
      "1 cartof dulce mediu",
      "1 ou",
      "2 linguri făină",
      "1 vârf scorțișoară",
      "2 linguri ulei",
    ],
    steps: [
      "Fierbe cartoful dulce 15 minute. Pasează.",
      "Amestecă cu oul, făina și scorțișoara.",
      "Încălzește uleiul la foc mediu.",
      "Pune câte 2 linguri, aplatizează.",
      "Gătește 3 minute pe fiecare parte.",
      "Servește cu iaurt pe lângă.",
    ],
    allergens: ["Ou", "Gluten"],
    relatedFoods: ["cartof-dulce", "ou"],
    storage: "Se păstrează la frigider 2 zile sau congelator 2 luni.",
  },
  {
    id: "crema-banane-unt-arahide-10",
    name: "Cremă de banane cu unt de arahide",
    emoji: "🍌",
    mealType: "mic-dejun",
    time: "5 min",
    age: "10+ luni",
    difficulty: "Ușor",
    servings: 1,
    ingredients: [
      "1 banană coaptă",
      "1 lingură unt de arahide",
      "2 linguri iaurt natural",
      "1 vârf semințe de cânepă",
    ],
    steps: [
      "Pasează banana cu furculița.",
      "Amestecă cu untul de arahide până e omogen.",
      "Adaugă iaurtul.",
      "Presară semințe de cânepă deasupra.",
      "Se poate mânca și pe toast!",
    ],
    allergens: ["Arahide", "Lactoză"],
    relatedFoods: ["banana", "unt-arahide", "iaurt"],
    storage: "Se servește proaspăt.",
  },
  {
    id: "frittata-ardei-branza-10",
    name: "Mini frittata cu ardei și brânză",
    emoji: "🌶️",
    mealType: "mic-dejun",
    time: "25 min",
    age: "10+ luni",
    difficulty: "Mediu",
    servings: "4-6",
    ingredients: [
      "4 ouă",
      "½ ardei gras tocat",
      "½ cană spanac",
      "¼ cană brânză rasă",
      "1 linguriță unt pentru forme",
    ],
    steps: [
      "Preîncălzește cuptorul la 180°C.",
      "Bate ouăle. Adaugă ardeiul, spanacul și brânza.",
      "Unge formele de muffin cu unt.",
      "Toarnă amestecul în 6 forme.",
      "Coace 15-18 minute.",
      "Scoate din forme când s-au răcit puțin.",
    ],
    allergens: ["Ou", "Lactoză"],
    relatedFoods: ["ou", "ardei-gras", "spanac", "branza-vaci"],
    storage: "Se păstrează la frigider 4 zile sau congelator 2 luni.",
  },
  {
    id: "piure-avocado-banana-chia-10",
    name: "Piure de avocado cu banană și chia",
    emoji: "🥑",
    mealType: "mic-dejun",
    time: "5 min",
    age: "10+ luni",
    difficulty: "Ușor",
    servings: 1,
    ingredients: [
      "½ avocado",
      "½ banană",
      "1 linguriță semințe chia",
      "1 linguriță suc de lămâie",
      "1 felie toast (opțional)",
    ],
    steps: [
      "Pasează avocado și banana împreună.",
      "Adaugă semințele de chia și sucul de lămâie.",
      "Amestecă bine.",
      "Servește ca atare sau pe toast.",
    ],
    allergens: [],
    relatedFoods: ["avocado", "banana"],
    storage: "Se servește proaspăt.",
  },
  {
    id: "waffle-dovlecel-branza-10",
    name: "Waffle de dovlecel cu brânză",
    emoji: "🧇",
    mealType: "mic-dejun",
    time: "20 min",
    age: "10+ luni",
    difficulty: "Mediu",
    servings: "3-4",
    ingredients: [
      "1 dovlecel ras și stors",
      "2 ouă",
      "½ cană făină",
      "¼ cană brânză de vaci",
      "1 vârf mărar",
      "1 linguriță ulei pentru aparat",
    ],
    steps: [
      "Rade dovlecelul, stoarce bine apa.",
      "Amestecă cu ouăle, făina, brânza și mărarul.",
      "Încălzește aparatul de waffle, unge cu ulei.",
      "Pune 2-3 linguri de compoziție.",
      "Gătește 3-4 minute.",
      "Servește călduțe cu iaurt.",
    ],
    allergens: ["Ou", "Lactoză", "Gluten"],
    relatedFoods: ["dovlecel", "ou", "branza-vaci"],
    storage: "Se păstrează la frigider 2 zile sau congelator 2 luni.",
  },
  {
    id: "porridge-hrisca-capsuni-10",
    name: "Porridge de hrișcă cu căpșuni",
    emoji: "🍓",
    mealType: "mic-dejun",
    time: "15 min",
    age: "10+ luni",
    difficulty: "Ușor",
    servings: 1,
    ingredients: [
      "¼ cană hrișcă",
      "½ cană apă",
      "¼ cană lapte",
      "4-5 căpșuni",
      "1 vârf vanilie",
    ],
    steps: [
      "Clătește hrișca. Fierbe cu apa 10 minute.",
      "Adaugă laptele, gătește 3 minute.",
      "Spală căpșunile, taie-le mărunt.",
      "Pasează jumătate, lasă jumătate bucăți.",
      "Amestecă în porridge cu vanilia.",
    ],
    allergens: ["Lactoză"],
    relatedFoods: ["capsuni"],
    storage: "Se păstrează la frigider 2 zile.",
  },
  {
    id: "toast-french-ou-banane-10",
    name: "French toast cu banană",
    emoji: "🍞",
    mealType: "mic-dejun",
    time: "10 min",
    age: "10+ luni",
    difficulty: "Ușor",
    servings: 1,
    ingredients: [
      "1 felie pâine groasă",
      "1 ou",
      "2 linguri lapte",
      "1 vârf scorțișoară",
      "1 linguriță unt",
      "½ banană felii",
    ],
    steps: [
      "Bate oul cu laptele și scorțișoara.",
      "Înmoaie pâinea în amestec (pe ambele părți).",
      "Topește untul la foc mediu.",
      "Prăjește pâinea 2 minute pe fiecare parte.",
      "Servește cu felii de banană deasupra.",
      "Taie în bețișoare sau cuburi.",
    ],
    allergens: ["Ou", "Lactoză", "Gluten"],
    relatedFoods: ["ou", "paine", "banana"],
    storage: "Se servește proaspăt.",
  },
  {
    id: "budinca-gris-fructe-10",
    name: "Budincă de griș cu fructe",
    emoji: "🍮",
    mealType: "mic-dejun",
    time: "20 min",
    age: "10+ luni",
    difficulty: "Ușor",
    servings: "2-3",
    ingredients: [
      "3 linguri griș",
      "1 cană lapte",
      "1 ou",
      "¼ cană fructe tocate (căpșuni, piersici, etc.)",
      "1 linguriță unt pentru formă",
    ],
    steps: [
      "Fierbe grișul cu laptele 5 minute amestecând.",
      "Lasă să se răcească 5 minute.",
      "Amestecă oul bine. Adaugă fructele.",
      "Unge o formă mică cu unt.",
      "Toarnă compoziția. Coace la 180°C, 15 minute.",
      "Lasă să se răcească. Taie felii.",
    ],
    allergens: ["Ou", "Lactoză", "Gluten"],
    relatedFoods: ["ou", "capsuni"],
    storage: "Se păstrează la frigider 3 zile.",
  },
  {
    id: "tartine-branza-rosii-10",
    name: "Tartine cu brânză de vaci și roșii",
    emoji: "🍅",
    mealType: "mic-dejun",
    time: "5 min",
    age: "10+ luni",
    difficulty: "Ușor",
    servings: 1,
    ingredients: [
      "1 felie pâine toast",
      "2 linguri brânză de vaci",
      "½ roșie mică",
      "1 vârf busuioc uscat",
      "1 vârf ulei de măsline",
    ],
    steps: [
      "Prăjește ușor pâinea.",
      "Întinde brânza de vaci pe toast.",
      "Taie roșia în felii subțiri, pune deasupra.",
      "Stropește cu ulei și presară busuioc.",
      "Taie în bețișoare.",
    ],
    allergens: ["Lactoză", "Gluten"],
    relatedFoods: ["branza-vaci", "rosii", "paine"],
    storage: "Se servește proaspăt.",
  },
  {
    id: "clatite-spanac-branza-10",
    name: "Clătite verzi de spanac cu brânză",
    emoji: "🥬",
    mealType: "mic-dejun",
    time: "20 min",
    age: "10+ luni",
    difficulty: "Mediu",
    servings: "3-4",
    ingredients: [
      "1 cană spanac proaspăt",
      "1 ou",
      "½ cană făină",
      "½ cană lapte",
      "2 linguri brânză de vaci",
      "1 linguriță ulei",
    ],
    steps: [
      "Mixează spanacul cu laptele și oul.",
      "Adaugă făina treptat — aluatul devine verde!",
      "Încălzește uleiul la foc mediu.",
      "Pune o lingură de aluat, rotește tigaia.",
      "Gătește 1-2 minute pe fiecare parte.",
      "Pune brânza pe clătită, rulează.",
      "Taie rondele de 2-3 cm.",
    ],
    allergens: ["Ou", "Lactoză", "Gluten"],
    relatedFoods: ["spanac", "ou", "branza-vaci"],
    storage: "Se păstrează la frigider 2 zile.",
  },
  {
    id: "cereale-casa-nuci-fructe-10",
    name: "Cereale de casă cu nuci și fructe uscate",
    emoji: "🥣",
    mealType: "mic-dejun",
    time: "30 min",
    age: "10+ luni",
    difficulty: "Mediu",
    servings: "10-12",
    ingredients: [
      "2 căni fulgi de ovăz",
      "¼ cană nuci măcinate",
      "¼ cană semințe (floarea-soarelui, dovleac)",
      "2 linguri ulei de cocos",
      "1 vârf scorțișoară",
      "¼ cană curmale tocate",
    ],
    steps: [
      "Preîncălzește cuptorul la 150°C.",
      "Amestecă fulgii de ovăz cu nucile și semințele.",
      "Adaugă uleiul de cocos topit și scorțișoara.",
      "Întinde pe tavă tapetată.",
      "Coace 20-25 minute, amestecând la jumătate.",
      "Lasă să se răcească complet — se va întări.",
      "Adaugă curmalele tocate.",
      "Servește cu lapte sau iaurt.",
    ],
    allergens: ["Nuci", "Nucă de cocos", "Gluten"],
    relatedFoods: ["ovaz", "nuci-macinate", "seminte-macinate", "curmale"],
    storage: "Se păstrează în borcan închis 2 săptămâni.",
  },
  {
    id: "mini-quiche-legume-10",
    name: "Mini quiche cu legume",
    emoji: "🥧",
    mealType: "mic-dejun",
    time: "30 min",
    age: "10+ luni",
    difficulty: "Mediu",
    servings: "6",
    ingredients: [
      "4 ouă",
      "¼ cană lapte",
      "1 morcov mic ras",
      "¼ cană broccoli tocat",
      "¼ cană brânză rasă",
      "1 linguriță unt pentru forme",
      "1 vârf nucșoară",
    ],
    steps: [
      "Preîncălzește cuptorul la 180°C.",
      "Bate ouăle cu laptele și nucșoara.",
      "Adaugă morcovul, broccoli și brânza.",
      "Unge formele de muffin cu unt.",
      "Toarnă amestecul în 6 forme.",
      "Coace 18-20 minute.",
      "Scoate când s-au răcit puțin.",
    ],
    allergens: ["Ou", "Lactoză"],
    relatedFoods: ["ou", "morcov", "broccoli", "branza-vaci"],
    storage: "Se păstrează la frigider 4 zile sau congelator 2 luni.",
  },
  {
    id: "iaurt-ovaz-fructe-10",
    name: "Iaurt cu ovăz fin și fructe",
    emoji: "🥣",
    mealType: "mic-dejun",
    time: "5 min",
    age: "10+ luni",
    difficulty: "Ușor",
    servings: 1,
    ingredients: [
      "½ cană iaurt natural",
      "2 linguri fulgi de ovăz instant",
      "¼ cană fructe tocate (căpșuni, afine)",
      "1 vârf vanilie (opțional)",
    ],
    steps: [
      "Pune iaurtul în castron.",
      "Presară fulgii de ovăz și amestecă. Lasă 2 minute să se înmoaie.",
      "Adaugă fructele tocate și vanilia.",
      "Amestecă și servește.",
    ],
    allergens: ["Lactoză", "Gluten"],
    relatedFoods: ["iaurt", "ovaz", "capsuni", "afine"],
    storage: "Se servește proaspăt.",
  },
];

/** Mic dejun 12+ luni */
export const MIC_DEJUN_12PLUS_EXTRA: RecipeCatalogItem[] = [
  {
    id: "clatite-clasice-fructe-12",
    name: "Clătite clasice cu fructe proaspete",
    emoji: "🥞",
    mealType: "mic-dejun",
    time: "20 min",
    age: "12+ luni",
    difficulty: "Mediu",
    servings: "4-6",
    ingredients: [
      "1 cană făină",
      "1 ou",
      "1 cană lapte",
      "1 lingură ulei",
      "1 vârf vanilie",
      "Fructe proaspete la alegere (căpșuni, banane, afine)",
    ],
    steps: [
      "Amestecă făina cu oul, laptele, uleiul și vanilia.",
      "Lasă aluatul 10 minute.",
      "Încălzește o tigaie anti-aderentă la foc mediu.",
      "Toarnă o lingură de aluat, rotește tigaia.",
      "Gătește 1-2 minute pe fiecare parte.",
      "Taie fructele. Pune în clătită, rulează.",
      "Taie rondele de 2-3 cm pentru bebeluș.",
    ],
    allergens: ["Ou", "Lactoză", "Gluten"],
    relatedFoods: ["ou", "capsuni", "banana", "afine"],
    storage: "Se păstrează la frigider 2 zile sau congelator 2 luni.",
  },
  {
    id: "granola-casa-iaurt-12",
    name: "Granola de casă cu iaurt și fructe",
    emoji: "🥣",
    mealType: "mic-dejun",
    time: "35 min",
    age: "12+ luni",
    difficulty: "Mediu",
    servings: "10-15",
    ingredients: [
      "2 căni fulgi de ovăz",
      "½ cană nuci și semințe amestecate (măcinate)",
      "2 linguri ulei de cocos",
      "1 linguriță scorțișoară",
      "¼ cană curmale tocate",
      "1 cană iaurt natural per porție",
      "Fructe proaspete per porție",
    ],
    steps: [
      "Preîncălzește cuptorul la 150°C.",
      "Amestecă fulgii cu nucile, uleiul și scorțișoara.",
      "Întinde pe tavă. Coace 25 minute, amestecând la jumătate.",
      "Lasă să se răcească complet (se întărește).",
      "Adaugă curmalele tocate.",
      "Per porție: iaurt + 2-3 linguri granola + fructe.",
    ],
    allergens: ["Nuci", "Nucă de cocos", "Lactoză", "Gluten"],
    relatedFoods: ["ovaz", "nuci-macinate", "iaurt", "curmale"],
    storage: "Granola: borcan închis 2 săptămâni.",
  },
  {
    id: "sandwich-ou-branza-12",
    name: "Mini sandwich cu ou și brânză",
    emoji: "🥪",
    mealType: "mic-dejun",
    time: "10 min",
    age: "12+ luni",
    difficulty: "Ușor",
    servings: 1,
    ingredients: [
      "2 felii pâine toast",
      "1 ou fiert",
      "2 linguri brânză de vaci",
      "2 felii castravete",
      "1 vârf mărar",
    ],
    steps: [
      "Fierbe oul 10 minute. Curăță și taie felii.",
      "Prăjește ușor pâinea.",
      "Întinde brânza pe o felie.",
      "Pune oul feliat și castravetele deasupra.",
      "Presară mărar. Acoperă cu cealaltă felie.",
      "Taie în 4 pătrate mici.",
    ],
    allergens: ["Ou", "Lactoză", "Gluten"],
    relatedFoods: ["ou", "branza-vaci", "paine", "castravete"],
    storage: "Se servește proaspăt.",
  },
  {
    id: "omleta-rulata-legume-12",
    name: "Omletă rulată cu legume",
    emoji: "🥚",
    mealType: "mic-dejun",
    time: "15 min",
    age: "12+ luni",
    difficulty: "Mediu",
    servings: "1-2",
    ingredients: [
      "3 ouă",
      "¼ cană ardei gras tocat mărunt",
      "¼ cană spanac tocat",
      "2 linguri brânză rasă",
      "1 linguriță unt",
    ],
    steps: [
      "Bate ouăle.",
      "Topește untul într-o tigaie la foc mediu.",
      "Toarnă ouăle, lasă-le să se întindă uniform.",
      "Când sunt aproape gata, pune legumele și brânza pe o jumătate.",
      "Îndoaie omleta în două.",
      "Gătește 1 minut. Taie felii.",
    ],
    allergens: ["Ou", "Lactoză"],
    relatedFoods: ["ou", "ardei-gras", "spanac", "branza-vaci"],
    storage: "Se servește proaspăt.",
  },
  {
    id: "briose-banane-ciocolata-12",
    name: "Brioșe de banane (fără zahăr adăugat)",
    emoji: "🧁",
    mealType: "mic-dejun",
    time: "30 min",
    age: "12+ luni",
    difficulty: "Mediu",
    servings: "8-10",
    ingredients: [
      "2 banane coapte",
      "2 ouă",
      "½ cană ulei",
      "1½ cană făină integrală",
      "1 linguriță praf de copt",
      "1 linguriță scorțișoară",
      "¼ cană iaurt natural",
    ],
    steps: [
      "Preîncălzește cuptorul la 180°C.",
      "Pasează bananele. Amestecă cu ouăle, uleiul și iaurtul.",
      "Separat: făina, praful de copt, scorțișoara.",
      "Combină uscatele cu umedele.",
      "Toarnă în forme de brioșe.",
      "Coace 20-22 minute.",
      "Verifică cu o scobitoare — trebuie să iasă curată.",
    ],
    allergens: ["Ou", "Lactoză", "Gluten"],
    relatedFoods: ["banana", "ou"],
    storage: "Se păstrează la frigider 3 zile sau congelator 2 luni.",
  },
  {
    id: "toast-avocado-ou-rosie-12",
    name: "Toast cu avocado, ou și roșie",
    emoji: "🥑",
    mealType: "mic-dejun",
    time: "10 min",
    age: "12+ luni",
    difficulty: "Ușor",
    servings: 1,
    ingredients: [
      "1 felie pâine toast",
      "½ avocado",
      "1 ou fiert sau jumări",
      "2 felii roșie",
      "1 vârf semințe de susan",
    ],
    steps: [
      "Prăjește pâinea.",
      "Pasează avocado pe toast.",
      "Fierbe oul 10 minute sau fă-l jumări.",
      "Pune oul și roșia pe toast.",
      "Presară semințe de susan.",
      "Taie în bețișoare.",
    ],
    allergens: ["Ou", "Susan", "Gluten"],
    relatedFoods: ["avocado", "ou", "rosii", "paine"],
    storage: "Se servește proaspăt.",
  },
  {
    id: "crema-ovaz-overnight-12",
    name: "Overnight oats cu fructe (terci la rece)",
    emoji: "🫙",
    mealType: "mic-dejun",
    time: "5 min + peste noapte",
    age: "12+ luni",
    difficulty: "Ușor",
    servings: 1,
    ingredients: [
      "½ cană fulgi de ovăz",
      "½ cană lapte sau iaurt",
      "1 lingură semințe chia",
      "½ banană",
      "Fructe proaspete de sezon",
    ],
    steps: [
      "Pune fulgii de ovăz într-un borcan.",
      "Adaugă laptele/iaurtul și semințele de chia.",
      "Pasează banana și adaugă-o.",
      "Amestecă, închide borcanul.",
      "Pune la frigider peste noapte.",
      "Dimineața: adaugă fructe proaspete deasupra.",
    ],
    allergens: ["Lactoză", "Gluten"],
    relatedFoods: ["ovaz", "banana"],
    storage: "Se păstrează la frigider 3 zile.",
  },
  {
    id: "paine-perdue-fructe-12",
    name: "Pain perdu (pâine prăjită în ou) cu fructe",
    emoji: "🍞",
    mealType: "mic-dejun",
    time: "10 min",
    age: "12+ luni",
    difficulty: "Ușor",
    servings: "1-2",
    ingredients: [
      "2 felii pâine albă",
      "2 ouă",
      "3 linguri lapte",
      "1 linguriță scorțișoară",
      "1 lingură unt",
      "½ cană fructe (căpșuni, afine, banane)",
    ],
    steps: [
      "Bate ouăle cu laptele și scorțișoara.",
      "Înmoaie pâinea pe ambele părți.",
      "Topește untul la foc mediu.",
      "Prăjește pâinea 2 minute pe fiecare parte.",
      "Taie fructele. Pune deasupra.",
      "Taie în cuburi sau bețișoare.",
    ],
    allergens: ["Ou", "Lactoză", "Gluten"],
    relatedFoods: ["ou", "paine", "capsuni", "banana"],
    storage: "Se servește proaspăt.",
  },
  {
    id: "tortilla-mic-dejun-12",
    name: "Tortilla de mic dejun cu ou și legume",
    emoji: "🌯",
    mealType: "mic-dejun",
    time: "15 min",
    age: "12+ luni",
    difficulty: "Mediu",
    servings: "1-2",
    ingredients: [
      "1 tortilla mică",
      "2 ouă jumări",
      "¼ avocado",
      "2 linguri brânză rasă",
      "¼ cană spanac",
      "1 linguriță ulei",
    ],
    steps: [
      "Fă ouăle jumări cu spanacul în ulei.",
      "Încălzește tortilla 30 secunde pe fiecare parte.",
      "Pasează avocado pe tortilla.",
      "Adaugă ouăle cu spanac și brânza.",
      "Rulează strâns. Taie în rondele de 3 cm.",
    ],
    allergens: ["Ou", "Lactoză", "Gluten"],
    relatedFoods: ["ou", "avocado", "spanac", "branza-vaci"],
    storage: "Se servește proaspăt.",
  },
  {
    id: "porridge-amarant-zmeura-12",
    name: "Porridge de amarant cu zmeură",
    emoji: "🫐",
    mealType: "mic-dejun",
    time: "30 min",
    age: "12+ luni",
    difficulty: "Mediu",
    servings: "2-3",
    ingredients: [
      "⅓ cană amarant",
      "1 cană apă",
      "½ cană lapte",
      "1 vârf scorțișoară",
      "¼ cană zmeură",
      "1 linguriță unt",
    ],
    steps: [
      "Clătește amarantul.",
      "Fierbe cu apa 25 minute la foc mic amestecând ocazional.",
      "Adaugă laptele și scorțișoara. Gătește 5 minute.",
      "Adaugă untul. Pune în castron.",
      "Adaugă zmeura deasupra (zdrobită sau întreagă).",
    ],
    allergens: ["Lactoză"],
    relatedFoods: ["zmeura"],
    storage: "Se păstrează la frigider 2 zile.",
  },
  {
    id: "galuste-branza-dulci-12",
    name: "Găluște de brânză (papanași fără prăjit)",
    emoji: "🧀",
    mealType: "mic-dejun",
    time: "20 min",
    age: "12+ luni",
    difficulty: "Mediu",
    servings: "3-4",
    ingredients: [
      "250g brânză de vaci",
      "1 ou",
      "3 linguri griș",
      "2 linguri făină",
      "½ cană iaurt natural",
      "¼ cană fructe (afine, căpșuni)",
    ],
    steps: [
      "Amestecă brânza cu oul, grișul și făina.",
      "Lasă 10 minute să se hidrateze grișul.",
      "Fierbe apă într-o oală mare.",
      "Formează găluște cu mâinile umede (mărimea unei nuci).",
      "Pune-le în apă clocotită. Gătește 3-5 minute (plutesc când sunt gata).",
      "Scoate cu lingura. Servește cu iaurt și fructe.",
    ],
    allergens: ["Ou", "Lactoză", "Gluten"],
    relatedFoods: ["branza-vaci", "ou", "iaurt", "afine"],
    storage: "Se păstrează la frigider 2 zile.",
  },
  {
    id: "placinte-branza-cuptor-12",
    name: "Plăcințele cu brânză la cuptor",
    emoji: "🥧",
    mealType: "mic-dejun",
    time: "35 min",
    age: "12+ luni",
    difficulty: "Mediu",
    servings: "6-8",
    ingredients: [
      "1 foaie de aluat filo sau foietaj",
      "200g brânză de vaci",
      "1 ou",
      "1 lingură smântână",
      "1 vârf mărar",
      "1 lingură unt topit pentru uns",
    ],
    steps: [
      "Preîncălzește cuptorul la 190°C.",
      "Amestecă brânza cu oul, smântâna și mărarul.",
      "Taie foaia de aluat în pătrate de ~10cm.",
      "Pune 1 lingură de umplutură pe fiecare.",
      "Îndoaie în triunghi, apasă marginile cu furculița.",
      "Unge cu unt topit. Pune pe tavă.",
      "Coace 18-20 minute până sunt aurii.",
    ],
    allergens: ["Ou", "Lactoză", "Gluten"],
    relatedFoods: ["branza-vaci", "ou"],
    storage: "Se păstrează la frigider 3 zile sau congelator 2 luni.",
  },
  {
    id: "shakshuka-usoara-12",
    name: "Shakshuka ușoară (ouă în sos de roșii)",
    emoji: "🍳",
    mealType: "mic-dejun",
    time: "25 min",
    age: "12+ luni",
    difficulty: "Mediu",
    servings: "2-3",
    ingredients: [
      "1 ceapă mică",
      "1 ardei gras",
      "2 căței usturoi",
      "1 lingură ulei",
      "1 cană roșii pasate",
      "½ linguriță boia dulce și chimion",
      "3-4 ouă",
      "1 felie pâine per porție",
    ],
    steps: [
      "Taie ceapa, ardeiul și usturoiul mărunt.",
      "Călește ceapa și ardeiul în ulei 5 minute.",
      "Adaugă usturoiul și condimentele, 30 secunde.",
      "Adaugă roșiile. Gătește 10 minute la foc mic.",
      "Fă găuri în sos cu lingura. Sparge câte un ou în fiecare.",
      "Acoperă. Gătește 8-10 minute (oul trebuie fiert complet!).",
      "Servește cu pâine pe lângă.",
    ],
    allergens: ["Ou", "Gluten"],
    relatedFoods: ["ou", "rosii", "ardei-gras", "usturoi", "paine"],
    storage: "Se păstrează la frigider 3 zile.",
  },
  {
    id: "muffin-ou-sunca-12",
    name: "Muffins de ou cu legume",
    emoji: "🥚",
    mealType: "mic-dejun",
    time: "25 min",
    age: "12+ luni",
    difficulty: "Mediu",
    servings: "6",
    ingredients: [
      "5 ouă",
      "¼ cană lapte",
      "½ cană legume mixte tocate (broccoli, morcov, ardei)",
      "¼ cană brânză rasă",
      "1 linguriță unt pentru forme",
    ],
    steps: [
      "Preîncălzește cuptorul la 180°C.",
      "Bate ouăle cu laptele.",
      "Adaugă legumele tocate și brânza.",
      "Unge formele de muffin cu unt.",
      "Toarnă amestecul în 6 forme.",
      "Coace 18-20 minute.",
      "Perfect pentru batch cooking!",
    ],
    allergens: ["Ou", "Lactoză"],
    relatedFoods: ["ou", "broccoli", "morcov", "branza-vaci"],
    storage: "Se păstrează la frigider 4 zile sau congelator 2 luni.",
  },
  {
    id: "croissant-branza-rosii-12",
    name: "Mini croissant cu brânză și roșii",
    emoji: "🥐",
    mealType: "mic-dejun",
    time: "25 min",
    age: "12+ luni",
    difficulty: "Mediu",
    servings: "4-6",
    ingredients: [
      "1 foaie aluat de croissant",
      "100g brânză de vaci",
      "2 roșii cherry (sau ½ roșie normală)",
      "1 vârf busuioc",
      "1 ou bătut pentru uns",
    ],
    steps: [
      "Preîncălzește cuptorul la 190°C.",
      "Taie aluatul în triunghiuri.",
      "Pune brânza și roșia tocată pe fiecare.",
      "Presară busuioc.",
      "Rulează de la baza largă spre vârf.",
      "Unge cu ou bătut. Coace 15-18 minute.",
      "Răcește înainte de a servi.",
    ],
    allergens: ["Ou", "Lactoză", "Gluten"],
    relatedFoods: ["branza-vaci", "rosii"],
    storage: "Se păstrează la frigider 2 zile.",
  },
  {
    id: "bol-acai-fructe-12",
    name: "Bol de fructe cu iaurt și toppinguri",
    emoji: "🍇",
    mealType: "mic-dejun",
    time: "5 min",
    age: "12+ luni",
    difficulty: "Ușor",
    servings: 1,
    ingredients: [
      "½ cană iaurt natural gros",
      "¼ cană afine",
      "¼ cană căpșuni feliate",
      "½ banană feliată",
      "1 linguriță unt de arahide",
      "1 linguriță semințe de cânepă",
      "1 linguriță fulgi de cocos",
    ],
    steps: [
      "Pune iaurtul gros în castron.",
      "Aranjează fructele frumos deasupra.",
      "Adaugă untul de arahide.",
      "Presară semințe de cânepă și fulgi de cocos.",
      "Bebelușul alege ce vrea să mănânce!",
    ],
    allergens: ["Lactoză", "Arahide", "Nucă de cocos"],
    relatedFoods: ["iaurt", "afine", "capsuni", "banana", "unt-arahide"],
    storage: "Se servește proaspăt.",
  },
  {
    id: "turta-cartof-branza-12",
    name: "Turte de cartofi cu brânză",
    emoji: "🥔",
    mealType: "mic-dejun",
    time: "25 min",
    age: "12+ luni",
    difficulty: "Mediu",
    servings: "4-6",
    ingredients: [
      "2 cartofi medii fierți",
      "1 ou",
      "3 linguri făină",
      "½ cană brânză de vaci",
      "1 vârf mărar",
      "2 linguri ulei",
    ],
    steps: [
      "Pasează cartofii fierți.",
      "Amestecă cu oul, făina, brânza și mărarul.",
      "Formează turte plate.",
      "Încălzește uleiul la foc mediu.",
      "Prăjește 3 minute pe fiecare parte.",
      "Servește cu iaurt sau smântână pe lângă.",
    ],
    allergens: ["Ou", "Lactoză", "Gluten"],
    relatedFoods: ["cartof", "branza-vaci", "ou"],
    storage: "Se păstrează la frigider 3 zile.",
  },
  {
    id: "budinca-paine-fructe-12",
    name: "Budincă de pâine cu fructe",
    emoji: "🍮",
    mealType: "mic-dejun",
    time: "40 min",
    age: "12+ luni",
    difficulty: "Mediu",
    servings: "4-6",
    ingredients: [
      "4 felii pâine (de preferat de o zi)",
      "2 ouă",
      "1 cană lapte",
      "1 linguriță scorțișoară",
      "1 linguriță vanilie",
      "½ cană fructe mixte",
      "1 lingură unt pentru formă",
    ],
    steps: [
      "Preîncălzește cuptorul la 180°C.",
      "Rupe pâinea în bucăți mici.",
      "Bate ouăle cu laptele, scorțișoara și vanilia.",
      "Pune pâinea într-o formă unsă cu unt.",
      "Adaugă fructele printre bucățile de pâine.",
      "Toarnă amestecul de ouă deasupra.",
      "Lasă 10 minute să se absoarbă.",
      "Coace 25-30 minute. Taie pătrate.",
    ],
    allergens: ["Ou", "Lactoză", "Gluten"],
    relatedFoods: ["ou", "paine"],
    storage: "Se păstrează la frigider 3 zile.",
  },
  {
    id: "wrap-unt-arahide-banane-12",
    name: "Wrap cu unt de arahide și banană",
    emoji: "🌯",
    mealType: "mic-dejun",
    time: "5 min",
    age: "12+ luni",
    difficulty: "Ușor",
    servings: 1,
    ingredients: [
      "1 tortilla mică",
      "1 lingură unt de arahide",
      "1 banană",
      "1 vârf scorțișoară",
      "1 vârf semințe de chia",
    ],
    steps: [
      "Întinde untul de arahide pe tortilla.",
      "Pune banana întreagă pe margine (sau feliată).",
      "Presară scorțișoară și semințe de chia.",
      "Rulează strâns.",
      "Taie în rondele de 2-3 cm.",
    ],
    allergens: ["Arahide", "Gluten"],
    relatedFoods: ["unt-arahide", "banana"],
    storage: "Se servește proaspăt.",
  },
  {
    id: "terci-ovaz-migdale-mere-12",
    name: "Terci de ovăz cu migdale măcinate și măr",
    emoji: "🥣",
    mealType: "mic-dejun",
    time: "15 min",
    age: "12+ luni",
    difficulty: "Ușor",
    servings: "1-2",
    ingredients: [
      "½ cană fulgi de ovăz",
      "1 cană lapte",
      "1 măr ras",
      "1 lingură migdale măcinate",
      "1 vârf scorțișoară",
      "1 linguriță unt (opțional)",
    ],
    steps: [
      "Fierbe laptele, adaugă fulgii de ovăz.",
      "Gătește 5 minute la foc mic, amestecând.",
      "Adaugă mărul ras și gătește 3 minute.",
      "Amestecă migdalele măcinate și scorțișoara.",
      "Adaugă untul. Servește călduț.",
    ],
    allergens: ["Lactoză", "Gluten", "Nuci (migdale)"],
    relatedFoods: ["ovaz", "mere", "unt-migdale", "scortisoara"],
    storage: "Se păstrează la frigider 2 zile.",
  },
];
