import type { RecipeCatalogItem } from "./recipesDatabase";

export const PRANZ_12PLUS_RECIPES: RecipeCatalogItem[] = [
  {
    id: "ciorba-perisoare-pui-12",
    name: "Ciorbă de perișoare din pui",
    emoji: "🍲",
    mealType: "pranz",
    time: "40 min",
    age: "12+ luni",
    difficulty: "Mediu",
    servings: "4-6",
    ingredients: [
      "120g piept de pui tocat",
      "20g orez",
      "5g pătrunjel",
      "60g morcov",
      "50g gulie",
      "50g mazăre",
      "40g țelină",
      "80g cartof",
      "1 lingură leuștean măcinat",
      "800ml apă",
    ],
    steps: [
      "Amestecă puiul tocat cu orezul și pătrunjelul. Formează perișoare mici.",
      "Fierbe legumele tăiate cuburi 15 minute.",
      "Adaugă perișoarele și fierbe încă 15-20 minute.",
      "Adaugă leușteanul la final.",
      "Taie perișoarele în jumătate pentru bebeluș dacă sunt prea mari.",
    ],
    allergens: [],
    relatedFoods: ["pui", "morcov", "mazare", "cartof", "orez"],
    storage: "Se păstrează la frigider 3 zile sau congelator 2 luni.",
  },
  {
    id: "ciorba-perisoare-vita-12",
    name: "Ciorbă de perișoare din vită",
    emoji: "🍲",
    mealType: "pranz",
    time: "45 min",
    age: "12+ luni",
    difficulty: "Mediu",
    servings: "4-6",
    ingredients: [
      "120g mușchiuleț de vită tocat",
      "50g ou (1 ou)",
      "20g orez",
      "60g morcov",
      "50g păstârnac",
      "40g țelină",
      "80g cartof dulce",
      "40g ardei roșu",
      "1 lingură leuștean măcinat",
      "900ml apă",
    ],
    steps: [
      "Amestecă vita cu oul și orezul. Formează perișoare.",
      "Fierbe legumele 15 minute.",
      "Adaugă perișoarele, fierbe 20-25 minute.",
      "Leușteanul se adaugă la final.",
    ],
    allergens: ["Ou"],
    relatedFoods: ["vita", "morcov", "cartof-dulce", "orez", "ou"],
    storage: "Se păstrează la frigider 3 zile sau congelator 2 luni.",
  },
  {
    id: "ciorba-curcan-legume-12",
    name: "Ciorbă din pulpă de curcan cu legume",
    emoji: "🍲",
    mealType: "pranz",
    time: "45 min",
    age: "12+ luni",
    difficulty: "Mediu",
    servings: "4-6",
    ingredients: [
      "150g pulpă de curcan",
      "40g ceapă",
      "40g ardei roșu",
      "50g păstârnac",
      "60g morcov",
      "1 lingură leuștean",
      "1 lingură pătrunjel",
      "900ml apă",
    ],
    steps: [
      "Fierbe carnea 20 minute.",
      "Adaugă legumele tocate. Fierbe 20 minute.",
      "Verdeața se adaugă la final.",
      "Taie carnea în bucăți mici înainte de servit.",
    ],
    allergens: [],
    relatedFoods: ["curcan", "morcov", "pastarnac", "ardei-gras"],
    storage: "Se păstrează la frigider 3 zile.",
  },
  {
    id: "ciorba-radauteana-baby-12",
    name: "Ciorbă rădăuțeană baby-friendly",
    emoji: "🍲",
    mealType: "pranz",
    time: "40 min",
    age: "12+ luni",
    difficulty: "Mediu",
    servings: "4-6",
    ingredients: [
      "150g piept de pui",
      "80g fasole verde",
      "60g morcov",
      "40g ceapă albă",
      "40g țelină",
      "40g ardei roșu",
      "80g smântână min. 3,5%",
      "900ml apă",
    ],
    steps: [
      "Fierbe puiul și legumele 30-35 minute.",
      "Ia 2 polonice de ciorbă fierbinte și amestecă cu smântâna.",
      "Toarnă înapoi și mai fierbe 3 minute.",
      "Taie puiul mărunt înainte de servit.",
    ],
    allergens: ["Lactoză"],
    relatedFoods: ["pui", "fasole-verde", "morcov"],
    storage: "Se păstrează la frigider 2 zile.",
  },
  {
    id: "supa-crema-dovlecel-morcov-12",
    name: "Supă cremă de dovlecel, morcov și ceapă",
    emoji: "🥣",
    mealType: "pranz",
    time: "30 min",
    age: "12+ luni",
    difficulty: "Ușor",
    servings: "3-4",
    ingredients: [
      "200g dovlecel",
      "100g morcov",
      "40g ceapă",
      "10g semințe de dovleac măcinate",
      "20g crutoane",
      "600ml apă",
    ],
    steps: [
      "Fierbe legumele 20-25 minute.",
      "Blenduiește până devine cremă.",
      "Servește cu semințe măcinate și crutoane.",
    ],
    allergens: [],
    relatedFoods: ["dovlecel", "morcov"],
    storage: "Se păstrează la frigider 3 zile sau congelator 2 luni.",
  },
  {
    id: "supa-crema-broccoli-12",
    name: "Supă cremă de broccoli",
    emoji: "🥣",
    mealType: "pranz",
    time: "30 min",
    age: "12+ luni",
    difficulty: "Ușor",
    servings: "3-4",
    ingredients: [
      "200g broccoli",
      "80g morcov",
      "1 cățel usturoi",
      "600ml apă",
    ],
    steps: [
      "Fierbe legumele 20-25 minute.",
      "Blenduiește fin.",
      "Servește cu crutoane.",
    ],
    allergens: [],
    relatedFoods: ["broccoli", "morcov", "usturoi"],
    storage: "Se păstrează la frigider 3 zile sau congelator 2 luni.",
  },
  {
    id: "supa-crema-mazare-12",
    name: "Supă cremă de mazăre",
    emoji: "🥣",
    mealType: "pranz",
    time: "30 min",
    age: "12+ luni",
    difficulty: "Ușor",
    servings: "3-4",
    ingredients: [
      "250g mazăre",
      "50g ceapă",
      "80g morcov",
      "50g ardei roșu",
      "600ml apă",
    ],
    steps: [
      "Fierbe toate legumele 20-25 minute.",
      "Blenduiește fin.",
      "Servește caldă.",
    ],
    allergens: [],
    relatedFoods: ["mazare", "morcov", "ardei-gras"],
    storage: "Se păstrează la frigider 3 zile sau congelator 2 luni.",
  },
  {
    id: "piept-pui-pane-piure-12",
    name: "Piept de pui pane cu piure de cartofi",
    emoji: "🍗",
    mealType: "pranz",
    time: "35 min",
    age: "12+ luni",
    difficulty: "Mediu",
    servings: "2-3",
    ingredients: [
      "120g piept de pui",
      "50g ou (1 ou)",
      "20g făină de speltă",
      "200g cartofi",
      "150g roșii decojite",
      "un vârf boia dulce",
      "un vârf usturoi pudră",
    ],
    steps: [
      "Taie pieptul fâșii. Trece prin ou și făină.",
      "Coace la 180°C, 18-20 minute (airfryer 170°C, 15-18 minute).",
      "Fierbe cartofii 20-25 minute și pasează.",
      "Fierbe roșiile 20 minute pentru sos.",
      "Taie puiul în bucăți mici înainte de servit.",
    ],
    allergens: ["Ou", "Gluten"],
    relatedFoods: ["pui", "cartof", "rosii", "ou"],
    storage: "Se păstrează la frigider 2 zile.",
  },
  {
    id: "piept-pui-cuptor-cous-cous-12",
    name: "Piept de pui la cuptor cu cous cous și legume",
    emoji: "🍗",
    mealType: "pranz",
    time: "35 min",
    age: "12+ luni",
    difficulty: "Mediu",
    servings: "2-3",
    ingredients: [
      "120g piept de pui",
      "40g cous cous",
      "80ml apă fierbinte",
      "50g ardei roșu",
      "60g morcov",
      "un vârf boia dulce",
      "un vârf ceapă granulată",
    ],
    steps: [
      "Condimentează pieptul și gătește la 180°C, 20-22 minute.",
      "Fierbe cous cous-ul 5-10 minute.",
      "Fierbe legumele 15-18 minute.",
      "Taie puiul cuburi mici și combină cu cous cous și legume.",
    ],
    allergens: ["Gluten"],
    relatedFoods: ["pui", "morcov", "ardei-gras"],
    storage: "Se păstrează la frigider 2 zile.",
  },
  {
    id: "tocanita-pui-dovlecel-12",
    name: "Tocăniță din piept de pui cu dovlecel și legume",
    emoji: "🍗",
    mealType: "pranz",
    time: "40 min",
    age: "12+ luni",
    difficulty: "Mediu",
    servings: "3-4",
    ingredients: [
      "120g piept de pui",
      "80g dovlecel",
      "30g ceapă verde",
      "100g cartof alb",
      "80g dovleac plăcintar",
      "un vârf boia dulce",
      "150ml apă",
    ],
    steps: [
      "Fierbe carnea 15 minute.",
      "Adaugă legumele și condimentele.",
      "Fierbe 20-25 minute până scade apa.",
      "Taie carnea cuburi mici înainte de servit.",
    ],
    allergens: [],
    relatedFoods: ["pui", "dovlecel", "cartof", "dovleac"],
    storage: "Se păstrează la frigider 3 zile sau congelator 2 luni.",
  },
  {
    id: "tocanita-pui-mazare-12",
    name: "Tocăniță din piept de pui cu mazăre",
    emoji: "🍗",
    mealType: "pranz",
    time: "40 min",
    age: "12+ luni",
    difficulty: "Mediu",
    servings: "3-4",
    ingredients: [
      "120g piept de pui",
      "120g mazăre",
      "50g ardei roșu",
      "40g ceapă albă",
      "1 lingură pătrunjel măcinat",
      "150ml apă",
    ],
    steps: [
      "Fierbe puiul 15 minute.",
      "Adaugă legumele. Fierbe 20-25 minute.",
      "Pătrunjelul se adaugă la final.",
    ],
    allergens: [],
    relatedFoods: ["pui", "mazare", "ardei-gras"],
    storage: "Se păstrează la frigider 3 zile.",
  },
  {
    id: "ficatel-pui-piure-cartofi-12",
    name: "Ficățel de pui cu piure de cartofi",
    emoji: "🍗",
    mealType: "pranz",
    time: "40 min",
    age: "12+ luni",
    difficulty: "Mediu",
    servings: "2-3",
    ingredients: [
      "120g ficățel de pui tăiat bucăți",
      "40g ceapă albă tocată",
      "60g morcov cubulețe",
      "60g mazăre",
      "200g cartof alb",
      "10g unt",
      "un vârf pătrunjel",
    ],
    steps: [
      "Fierbe ficățelul, ceapa, morcovul și mazărea 20-25 minute.",
      "Fierbe cartofii 25 minute și pasează cu unt.",
      "Pătrunjelul se adaugă opțional la final.",
    ],
    allergens: ["Lactoză"],
    relatedFoods: ["pui", "morcov", "mazare", "cartof"],
    storage: "Se păstrează la frigider 2 zile.",
  },
  {
    id: "piept-curcan-sos-ardei-12",
    name: "Piept de curcan în sos de ardei și roșii cu cartofi copți",
    emoji: "🦃",
    mealType: "pranz",
    time: "40 min",
    age: "12+ luni",
    difficulty: "Mediu",
    servings: "2-3",
    ingredients: [
      "150g piept de curcan",
      "80g ardei roșu",
      "120g roșii decojite",
      "200g cartofi",
      "20g iaurt grecesc",
      "1 lingură mărar măcinat",
      "un vârf boia dulce",
    ],
    steps: [
      "Condimentează pieptul și coace la 180°C, 25-30 minute.",
      "Fierbe ardeiul și roșiile 20 minute și pasează.",
      "Coace cartofii la 180°C, 30-35 minute.",
      "Servește cu iaurt și mărar.",
    ],
    allergens: ["Lactoză"],
    relatedFoods: ["curcan", "ardei-gras", "rosii", "cartof"],
    storage: "Se păstrează la frigider 2 zile.",
  },
  {
    id: "tocanita-curcan-spanac-quinoa-12",
    name: "Tocăniță din piept de curcan cu spanac și quinoa",
    emoji: "🦃",
    mealType: "pranz",
    time: "40 min",
    age: "12+ luni",
    difficulty: "Mediu",
    servings: "3-4",
    ingredients: [
      "150g piept de curcan",
      "80g spanac proaspăt",
      "30g ceapă verde",
      "60g morcov",
      "30g quinoa",
      "1 lingură pătrunjel măcinat",
    ],
    steps: [
      "Spală quinoa bine și fierbe separat 12-15 minute.",
      "Fierbe carnea 15 minute. Adaugă legumele și fierbe 15 minute.",
      "Amestecă cu quinoa.",
    ],
    allergens: [],
    relatedFoods: ["curcan", "spanac", "quinoa", "morcov"],
    storage: "Se păstrează la frigider 2 zile.",
  },
  {
    id: "muschiulet-vita-piure-12",
    name: "Mușchiuleț de vită slow cooked cu piure de cartofi",
    emoji: "🥩",
    mealType: "pranz",
    time: "2h",
    age: "12+ luni",
    difficulty: "Mediu",
    servings: "3-4",
    ingredients: [
      "160g mușchiuleț de vită",
      "150g cartof alb",
      "60g țelină",
      "60g păstârnac",
      "un vârf boia dulce",
    ],
    steps: [
      "Acoperă carnea și gătește la 150°C, 90-120 minute.",
      "Fierbe legumele 20-25 minute și pasează.",
      "Taie carnea în bucăți foarte mici înainte de servit.",
    ],
    allergens: [],
    relatedFoods: ["vita", "cartof", "pastarnac"],
    storage: "Se păstrează la frigider 3 zile sau congelator 2 luni.",
  },
  {
    id: "tocana-vita-orez-legume-12",
    name: "Tocană de vită cu orez și legume",
    emoji: "🥩",
    mealType: "pranz",
    time: "1h",
    age: "12+ luni",
    difficulty: "Mediu",
    servings: "3-4",
    ingredients: [
      "160g carne de vită",
      "30g orez",
      "1 cățel usturoi fiert",
      "80g sfeclă",
      "80g dovleac plăcintar",
      "80g conopidă",
      "un vârf boia dulce",
    ],
    steps: [
      "Fierbe carnea 40-45 minute. Adaugă legumele și fierbe 20 minute.",
      "Fierbe orezul separat 15-18 minute.",
      "Taie carnea cuburi mici înainte de servit.",
    ],
    allergens: [],
    relatedFoods: ["vita", "orez", "sfecla", "conopida"],
    storage: "Se păstrează la frigider 3 zile sau congelator 2 luni.",
  },
  {
    id: "file-somon-legume-orez-12",
    name: "File de somon cu legume și orez",
    emoji: "🐟",
    mealType: "pranz",
    time: "30 min",
    age: "12+ luni",
    difficulty: "Mediu",
    servings: "2",
    ingredients: [
      "160g file de somon",
      "120g cartof dulce",
      "100g broccoli",
      "60g ardei roșu",
      "30g ceapă albă",
      "30g orez",
    ],
    steps: [
      "Coace somonul la 180°C, 15-18 minute.",
      "Fierbe legumele 20 minute.",
      "Fierbe orezul 15-18 minute.",
      "Verifică somonul de oase! Sfărâmă înainte de servit.",
    ],
    allergens: ["Pește"],
    relatedFoods: ["somon", "broccoli", "cartof-dulce", "orez"],
    storage: "Se servește proaspăt. Max 1 zi frigider.",
  },
  {
    id: "file-salau-spanac-mei-12",
    name: "File de șalău cu spanac, broccoli și mei",
    emoji: "🐟",
    mealType: "pranz",
    time: "30 min",
    age: "12+ luni",
    difficulty: "Mediu",
    servings: "2",
    ingredients: [
      "150g file de șalău",
      "80g spanac proaspăt",
      "80g broccoli",
      "30g mei",
      "un vârf pătrunjel măcinat",
    ],
    steps: [
      "Fierbe șalăul la foc mic 10-12 minute.",
      "Fierbe spanacul și broccoli 5-7 minute.",
      "Fierbe meiul separat 15-18 minute.",
      "Verifică peștele de oase! Combină toate.",
    ],
    allergens: ["Pește"],
    relatedFoods: ["peste-alb", "spanac", "broccoli"],
    storage: "Se servește proaspăt.",
  },
  {
    id: "paste-sos-ardei-curcan-12",
    name: "Paste cu sos de ardei și curcan",
    emoji: "🍝",
    mealType: "pranz",
    time: "35 min",
    age: "12+ luni",
    difficulty: "Mediu",
    servings: "2-3",
    ingredients: [
      "50g paste",
      "120g piept de curcan",
      "80g ardei roșu",
      "80g roșii decojite",
      "un vârf boia dulce",
    ],
    steps: [
      "Fierbe pastele 8-10 minute.",
      "Fierbe curcanul 20-25 minute și toacă mărunt.",
      "Fierbe ardeiul și roșiile 20 minute și pasează.",
      "Combină pastele cu sosul și curcanul.",
    ],
    allergens: ["Gluten"],
    relatedFoods: ["paste", "curcan", "ardei-gras", "rosii"],
    storage: "Se păstrează la frigider 2 zile.",
  },
  {
    id: "macaroane-branza-12",
    name: "Macaroane cu brânză",
    emoji: "🍝",
    mealType: "pranz",
    time: "20 min",
    age: "12+ luni",
    difficulty: "Ușor",
    servings: "2",
    ingredients: [
      "50g macaroane",
      "60g brânză de vaci sau caș dulce",
      "20g smântână min. 3,5%",
    ],
    steps: [
      "Fierbe pastele 8-10 minute.",
      "Amestecă la cald cu brânza și smântâna.",
      "Servește imediat.",
    ],
    allergens: ["Lactoză", "Gluten"],
    relatedFoods: ["paste", "branza-vaci"],
    storage: "Se servește proaspăt.",
  },
  {
    id: "paste-cuptor-ou-branza-12",
    name: "Paste la cuptor cu ou și brânză",
    emoji: "🍝",
    mealType: "pranz",
    time: "40 min",
    age: "12+ luni",
    difficulty: "Mediu",
    servings: "3-4",
    ingredients: [
      "50g paste",
      "50g ou (1 ou)",
      "60g brânză rasă",
      "30g smântână",
    ],
    steps: [
      "Fierbe pastele 8-10 minute.",
      "Amestecă cu oul bătut, brânza și smântâna.",
      "Coace la 180°C, 25-30 minute.",
      "Lasă să se răcească. Taie cuburi.",
    ],
    allergens: ["Ou", "Lactoză", "Gluten"],
    relatedFoods: ["paste", "ou", "branza-vaci"],
    storage: "Se păstrează la frigider 3 zile.",
  },
  {
    id: "paste-somon-avocado-12",
    name: "Paste cu somon, avocado și roșii",
    emoji: "🍝",
    mealType: "pranz",
    time: "25 min",
    age: "12+ luni",
    difficulty: "Mediu",
    servings: "2",
    ingredients: [
      "60g paste",
      "100g somon",
      "80g avocado",
      "100g roșii",
      "40g brânzică de casă",
    ],
    steps: [
      "Coace somonul 15 minute. Verifică oasele! Sfărâmă.",
      "Fierbe pastele 8-10 minute.",
      "Pasează avocado.",
      "Combină pastele cu somonul, avocado și roșia tăiată.",
      "Adaugă brânzica la final.",
    ],
    allergens: ["Pește", "Lactoză", "Gluten"],
    relatedFoods: ["paste", "somon", "avocado", "rosii"],
    storage: "Se servește proaspăt.",
  },
  {
    id: "chiftele-dovlecel-branza-12",
    name: "Chiftele din dovlecel cu brânză și piure de cartofi",
    emoji: "🥒",
    mealType: "pranz",
    time: "45 min",
    age: "12+ luni",
    difficulty: "Mediu",
    servings: "3-4",
    ingredients: [
      "200g dovlecel ras și stors",
      "40g brânză rasă",
      "50g ou (1 ou)",
      "20g făină de speltă",
      "1 lingură mărar măcinat",
      "200g cartofi",
      "150g roșii decojite",
    ],
    steps: [
      "Amestecă dovlecelul, brânza, oul, făina și mărarul.",
      "Formează chiftele. Coace la 180°C, 25-30 minute.",
      "Fierbe cartofii și pasează.",
      "Fierbe roșiile pentru sos.",
    ],
    allergens: ["Ou", "Lactoză", "Gluten"],
    relatedFoods: ["dovlecel", "ou", "branza-vaci", "cartof", "rosii"],
    storage: "Se păstrează la frigider 3 zile sau congelator 2 luni.",
  },
  {
    id: "tocanita-linte-cartof-dulce-12",
    name: "Tocăniță din linte cu cartof dulce și legume",
    emoji: "🫘",
    mealType: "pranz",
    time: "35 min",
    age: "12+ luni",
    difficulty: "Ușor",
    servings: "3-4",
    ingredients: [
      "40g linte roșie",
      "120g cartof dulce",
      "40g ceapă albă",
      "1 cățel usturoi fiert",
      "60g ardei roșu",
      "80g dovlecel",
    ],
    steps: [
      "Fierbe lintea 12-15 minute.",
      "Adaugă legumele și fierbe 20 minute.",
    ],
    allergens: [],
    relatedFoods: ["linte", "cartof-dulce", "ardei-gras", "dovlecel"],
    storage: "Se păstrează la frigider 3 zile sau congelator 2 luni.",
  },
  {
    id: "lasagna-spanac-curcan-12",
    name: "Lasagna cu spanac și carne tocată de curcan",
    emoji: "🍝",
    mealType: "pranz",
    time: "50 min",
    age: "12+ luni",
    difficulty: "Mediu",
    servings: "4-6",
    ingredients: [
      "60g foi de lasagna",
      "150g carne tocată de curcan",
      "120g spanac",
      "40g ceapă albă",
      "150g bulion bio",
    ],
    steps: [
      "Gătește carnea cu ceapa și bulionul 15-20 minute.",
      "Opărește spanacul 3 minute.",
      "Asamblează straturile și coace la 180°C, 30-35 minute.",
      "Lasă să se răcească. Taie porții mici.",
    ],
    allergens: ["Gluten"],
    relatedFoods: ["paste", "curcan", "spanac", "rosii"],
    storage: "Se păstrează la frigider 3 zile sau congelator 2 luni.",
  },
];
