import type { RecipeCatalogItem } from "./recipesDatabase";

/**
 * Rețete PRÂNZ 6-8 luni — 15 rețete noi
 * Textură: piure fin → semi-pasat, fără bucăți mari
 * Porții: ~65-80g per bebeluș
 */
export const PRANZ_6_8_RECIPES: RecipeCatalogItem[] = [
  {
    id: "piure-dovlecel-linte",
    name: "Piure de dovlecel cu linte roșie",
    emoji: "🥒",
    mealType: "pranz",
    time: "20 min",
    age: "6+ luni",
    difficulty: "Ușor",
    servings: "2-3",
    ingredients: [
      "1 dovlecel mic (150g)",
      "¼ cană linte roșie",
      "1 lingură ulei de măsline",
      "½ cană apă de la fiert",
    ],
    steps: [
      "Clătește lintea. Fierbe în apă 15 minute până se desface complet.",
      "Taie dovlecelul cuburi mici. Fierbe separat 10 minute.",
      "Pasează lintea și dovlecelul împreună cu uleiul.",
      "Adaugă apă de la fiert pentru consistența dorită.",
      "Servește călduț — trebuie să fie un piure fin.",
    ],
    allergens: [],
    relatedFoods: ["dovlecel", "linte"],
    storage: "Se păstrează la frigider 2 zile sau congelator 1 lună.",
    totalYieldGrams: 280,
    babyPortionGramsByAgeBand: { "4-6": 40, "6-8": 70, "8-10": 100, "10-12": 120 },
  },
  {
    id: "piure-morcov-fasole-verde",
    name: "Piure de morcov cu fasole verde",
    emoji: "🥕",
    mealType: "pranz",
    time: "20 min",
    age: "6+ luni",
    difficulty: "Ușor",
    servings: "2-3",
    ingredients: [
      "2 morcovi medii",
      "100g fasole verde",
      "1 linguriță unt nesărat",
      "¼ cană lapte matern sau formulă",
    ],
    steps: [
      "Curăță morcovii și taie-i rondele. Fierbe 15 minute.",
      "Taie fasolea verde bucăți mici. Fierbe separat 12 minute.",
      "Scurge ambele. Pasează împreună cu untul și laptele.",
      "Textura trebuie să fie fin omogenă, fără fibre.",
      "Servește imediat sau păstrează la frigider.",
    ],
    allergens: ["Lactoză"],
    relatedFoods: ["morcov", "fasole-verde"],
    storage: "Se păstrează la frigider 2 zile.",
    totalYieldGrams: 260,
    babyPortionGramsByAgeBand: { "4-6": 40, "6-8": 70, "8-10": 95, "10-12": 115 },
  },
  {
    id: "piure-mazare-cartof-dulce",
    name: "Piure de mazăre cu cartof dulce",
    emoji: "🍠",
    mealType: "pranz",
    time: "20 min",
    age: "4+ luni",
    difficulty: "Ușor",
    servings: "2-3",
    ingredients: [
      "1 cartof dulce mic (150g)",
      "¾ cană mazăre (proaspătă sau congelată)",
      "1 linguriță ulei de cocos",
      "50ml apă de la fiert",
    ],
    steps: [
      "Curăță cartoful dulce, taie cuburi. Fierbe 15-20 minute.",
      "Fierbe mazărea 10 minute. Scurge bine.",
      "Pasează cartoful. Adaugă mazărea și pasează din nou fin.",
      "Adaugă uleiul de cocos și apa pentru consistență.",
      "Piureul trebuie să fie moale și omogen — fără coji de mazăre.",
    ],
    allergens: [],
    relatedFoods: ["cartof-dulce", "mazare"],
    storage: "Se păstrează la frigider 2 zile sau congelator 1 lună.",
    totalYieldGrams: 300,
    babyPortionGramsByAgeBand: { "4-6": 45, "6-8": 70, "8-10": 100, "10-12": 120 },
  },
  {
    id: "piure-conopida-pui-6",
    name: "Piure de conopidă cu pui",
    emoji: "🥦",
    mealType: "pranz",
    time: "25 min",
    age: "6+ luni",
    difficulty: "Ușor",
    servings: "2-3",
    ingredients: [
      "½ conopidă mică (200g buchețele)",
      "80g piept de pui",
      "1 linguriță ulei de măsline",
      "50ml apă de la fiert",
    ],
    steps: [
      "Fierbe pieptul de pui 20-25 minute. Scurge și lasă să se răcească.",
      "Fierbe conopida la abur sau în apă 12-15 minute până e moale.",
      "Pune conopida și puiul în blender.",
      "Adaugă uleiul și apa. Pasează fin.",
      "Verifică textura — trebuie să fie ca un piure cremos.",
    ],
    allergens: [],
    relatedFoods: ["conopida", "pui"],
    storage: "Se păstrează la frigider 2 zile.",
    totalYieldGrams: 260,
    babyPortionGramsByAgeBand: { "6-8": 70, "8-10": 100, "10-12": 120 },
  },
  {
    id: "piure-broccoli-cartof-6",
    name: "Piure de broccoli cu cartof",
    emoji: "🥦",
    mealType: "pranz",
    time: "20 min",
    age: "6+ luni",
    difficulty: "Ușor",
    servings: "2-3",
    ingredients: [
      "1 cană broccoli buchețele",
      "1 cartof mediu",
      "1 linguriță unt",
      "¼ cană lapte matern sau formulă",
    ],
    steps: [
      "Curăță cartoful, taie cuburi. Fierbe 15 minute.",
      "Adaugă broccoli în ultimele 8 minute de fiert.",
      "Scurge. Pasează cu untul și laptele.",
      "Piureul va fi verde-deschis și cremos.",
      "Lasă să se răcească. Servește la temperatura camerei.",
    ],
    allergens: ["Lactoză"],
    relatedFoods: ["broccoli", "cartof"],
    storage: "Se păstrează la frigider 2 zile.",
    totalYieldGrams: 280,
    babyPortionGramsByAgeBand: { "6-8": 70, "8-10": 95, "10-12": 115 },
  },
  {
    id: "piure-pastarnac-pui-6",
    name: "Piure de păstârnac cu pui și morcov",
    emoji: "🥕",
    mealType: "pranz",
    time: "25 min",
    age: "6+ luni",
    difficulty: "Ușor",
    servings: "2-3",
    ingredients: [
      "2 păstârnaci",
      "1 morcov",
      "80g piept de pui",
      "1 lingură ulei de măsline",
    ],
    steps: [
      "Fierbe puiul 20 minute. Sfărâmă cu furculița.",
      "Curăță și taie păstârnacii și morcovul. Fierbe 15 minute.",
      "Pasează legumele cu uleiul.",
      "Adaugă puiul sfărâmat și pasează din nou.",
      "Textura fină — fără bucăți la 6 luni.",
    ],
    allergens: [],
    relatedFoods: ["pastarnac", "morcov", "pui"],
    storage: "Se păstrează la frigider 2 zile sau congelator 1 lună.",
    totalYieldGrams: 270,
    babyPortionGramsByAgeBand: { "6-8": 70, "8-10": 100, "10-12": 120 },
  },
  {
    id: "orez-cremos-morcov-6",
    name: "Orez cremos cu morcov",
    emoji: "🍚",
    mealType: "pranz",
    time: "25 min",
    age: "6+ luni",
    difficulty: "Ușor",
    servings: "2-3",
    ingredients: [
      "¼ cană orez rotund",
      "1 morcov mare",
      "1½ căni apă",
      "1 linguriță unt",
    ],
    steps: [
      "Curăță morcovul, taie cuburi mici.",
      "Pune orezul cu morcovul și apa la fiert.",
      "Gătește 20-25 minute la foc mic, acoperit, amestecând rar.",
      "Adaugă untul. Pasează parțial pentru textură cremă.",
      "La 6 luni pasează fin. La 8+ luni poți lăsa semi-pasat.",
    ],
    allergens: ["Lactoză"],
    relatedFoods: ["orez", "morcov"],
    storage: "Se păstrează la frigider 2 zile.",
    totalYieldGrams: 300,
    babyPortionGramsByAgeBand: { "6-8": 70, "8-10": 100, "10-12": 120 },
  },
  {
    id: "piure-spanac-cartof-ou-6",
    name: "Piure de spanac cu cartof și gălbenuș",
    emoji: "🥬",
    mealType: "pranz",
    time: "20 min",
    age: "6+ luni",
    difficulty: "Ușor",
    servings: "1-2",
    ingredients: [
      "1 cartof mediu",
      "1 cană spanac proaspăt",
      "1 gălbenuș de ou fiert",
      "1 linguriță ulei de măsline",
    ],
    steps: [
      "Fierbe cartoful 15-20 minute. Pasează.",
      "Opărește spanacul 3 minute. Scurge bine, stoarce apa.",
      "Fierbe oul 10 minute. Scoate gălbenușul.",
      "Pasează spanacul cu uleiul.",
      "Amestecă piureul de cartof, spanacul și gălbenușul.",
    ],
    allergens: ["Ou"],
    relatedFoods: ["spanac", "cartof", "ou"],
    storage: "Se păstrează la frigider 1 zi (conține ou).",
    totalYieldGrams: 220,
    babyPortionGramsByAgeBand: { "6-8": 65, "8-10": 90, "10-12": 110 },
  },
  {
    id: "piure-telina-morcov-pui",
    name: "Piure de țelină cu morcov și pui",
    emoji: "🥕",
    mealType: "pranz",
    time: "25 min",
    age: "6+ luni",
    difficulty: "Ușor",
    servings: "2-3",
    ingredients: [
      "¼ țelină mică",
      "2 morcovi",
      "80g piept de pui",
      "1 linguriță ulei de măsline",
      "50ml apă de la fiert",
    ],
    steps: [
      "Fierbe pieptul de pui 20 minute. Scurge, lasă să se răcească.",
      "Curăță țelina și morcovii, taie cuburi. Fierbe 15 minute.",
      "Pasează legumele cu uleiul și apa.",
      "Adaugă puiul și pasează din nou fin.",
      "Servește călduț.",
    ],
    allergens: [],
    relatedFoods: ["morcov", "pui"],
    storage: "Se păstrează la frigider 2 zile.",
    totalYieldGrams: 260,
    babyPortionGramsByAgeBand: { "6-8": 70, "8-10": 100, "10-12": 120 },
  },
  {
    id: "piure-cartof-somon-6",
    name: "Piure de cartof cu somon",
    emoji: "🐟",
    mealType: "pranz",
    time: "25 min",
    age: "6+ luni",
    difficulty: "Mediu",
    servings: "2",
    ingredients: [
      "2 cartofi medii",
      "80g somon proaspăt fără oase",
      "1 linguriță unt",
      "¼ cană lapte matern sau formulă",
      "1 linguriță suc de lămâie",
    ],
    steps: [
      "Fierbe cartofii 20 minute. Pasează cu unt și lapte.",
      "Gătește somonul la abur 10 minute. VERIFICĂ OASELE!",
      "Sfărâmă somonul foarte fin cu furculița.",
      "Amestecă piureul cu somonul și sucul de lămâie.",
      "Textura trebuie să fie fină — fără bucăți de pește.",
    ],
    allergens: ["Lactoză", "Pește"],
    relatedFoods: ["cartof", "somon"],
    storage: "Se păstrează la frigider 1 zi (pește proaspăt).",
    totalYieldGrams: 250,
    babyPortionGramsByAgeBand: { "6-8": 70, "8-10": 95, "10-12": 115 },
  },
  {
    id: "piure-dovleac-linte-6",
    name: "Piure de dovleac cu linte și turmeric",
    emoji: "🎃",
    mealType: "pranz",
    time: "25 min",
    age: "6+ luni",
    difficulty: "Ușor",
    servings: "3-4",
    ingredients: [
      "300g dovleac curățat",
      "¼ cană linte roșie",
      "½ linguriță turmeric",
      "1 lingură ulei de cocos",
      "1 cană apă",
    ],
    steps: [
      "Clătește lintea. Fierbe în apă cu turmericul 15 minute.",
      "Taie dovleacul cuburi. Fierbe sau coace 20 minute.",
      "Pasează dovleacul și lintea împreună cu uleiul de cocos.",
      "Adaugă apă dacă e prea dens.",
      "Culoarea galbenă strălucitoare e semn că turmericul e activ!",
    ],
    allergens: [],
    relatedFoods: ["dovleac-butternut", "linte", "turmeric"],
    storage: "Se păstrează la frigider 3 zile sau congelator 2 luni.",
    totalYieldGrams: 380,
    babyPortionGramsByAgeBand: { "4-6": 45, "6-8": 70, "8-10": 100, "10-12": 120 },
  },
  {
    id: "piure-fasole-verde-cartof-6",
    name: "Piure de fasole verde cu cartof și unt",
    emoji: "🫘",
    mealType: "pranz",
    time: "20 min",
    age: "6+ luni",
    difficulty: "Ușor",
    servings: "2-3",
    ingredients: [
      "150g fasole verde",
      "1 cartof mic",
      "1 linguriță unt",
      "50ml apă de la fiert",
    ],
    steps: [
      "Fierbe fasolea verde 12-15 minute. Scurge bine.",
      "Fierbe cartoful cuburi 15 minute. Scurge.",
      "Pasează ambele cu untul și apa.",
      "Trece printr-o sită dacă mai rămân fibre.",
      "Servește la temperatura camerei.",
    ],
    allergens: ["Lactoză"],
    relatedFoods: ["fasole-verde", "cartof"],
    storage: "Se păstrează la frigider 2 zile.",
    totalYieldGrams: 250,
    babyPortionGramsByAgeBand: { "6-8": 65, "8-10": 90, "10-12": 110 },
  },
  {
    id: "piure-kale-cartof-dulce",
    name: "Piure de kale cu cartof dulce",
    emoji: "🥬",
    mealType: "pranz",
    time: "20 min",
    age: "6+ luni",
    difficulty: "Ușor",
    servings: "2-3",
    ingredients: [
      "1 cartof dulce mediu",
      "3-4 frunze kale (fără nervuri)",
      "1 linguriță ulei de măsline",
      "50ml lapte matern sau formulă",
    ],
    steps: [
      "Curăță cartoful dulce, taie cuburi. Fierbe 20 minute.",
      "Îndepărtează nervurile din kale. Fierbe frunzele 8-10 minute.",
      "Pasează cartoful dulce cu laptele.",
      "Pasează kale separat, adaugă în piure.",
      "Amestecă cu ulei. Textura trebuie să fie fin omogenă.",
    ],
    allergens: ["Lactoză"],
    relatedFoods: ["cartof-dulce", "kale"],
    storage: "Se păstrează la frigider 2 zile.",
    totalYieldGrams: 280,
    babyPortionGramsByAgeBand: { "6-8": 70, "8-10": 95, "10-12": 115 },
  },
  {
    id: "piure-morcov-naut-6",
    name: "Piure de morcov cu năut",
    emoji: "🥕",
    mealType: "pranz",
    time: "20 min",
    age: "6+ luni",
    difficulty: "Ușor",
    servings: "3-4",
    ingredients: [
      "2 morcovi mari",
      "½ cană năut fiert (din conservă, clătit)",
      "1 lingură tahini (pastă susan)",
      "1 linguriță suc de lămâie",
      "1 lingură ulei de măsline",
    ],
    steps: [
      "Fierbe morcovii 15-20 minute.",
      "Pune morcovii, năutul, tahini, lămâia și uleiul în blender.",
      "Pasează fin — adaugă apă dacă e prea dens.",
      "Verifică textura: trebuie să fie ca un hummus moale.",
      "Servește răcit sau la temperatura camerei.",
    ],
    allergens: ["Susan"],
    relatedFoods: ["morcov", "naut"],
    storage: "Se păstrează la frigider 3 zile.",
    totalYieldGrams: 320,
    babyPortionGramsByAgeBand: { "6-8": 65, "8-10": 90, "10-12": 110 },
  },
  {
    id: "piure-curcan-morcov-6",
    name: "Piure de curcan cu morcov și cartof",
    emoji: "🍗",
    mealType: "pranz",
    time: "30 min",
    age: "6+ luni",
    difficulty: "Mediu",
    servings: "2-3",
    ingredients: [
      "100g carne de curcan (piept)",
      "2 morcovi",
      "1 cartof mic",
      "1 linguriță ulei de măsline",
      "50ml apă de la fiert",
    ],
    steps: [
      "Fierbe curcanul 25 minute. Scurge, lasă să se răcească.",
      "Fierbe morcovii și cartoful cuburi 15 minute.",
      "Pasează legumele cu uleiul.",
      "Adaugă curcanul și pasează împreună fin.",
      "Adaugă apă pentru consistența dorită.",
    ],
    allergens: [],
    relatedFoods: ["curcan", "morcov", "cartof"],
    storage: "Se păstrează la frigider 2 zile sau congelator 1 lună.",
    totalYieldGrams: 270,
    babyPortionGramsByAgeBand: { "6-8": 70, "8-10": 100, "10-12": 120 },
  },
];

/**
 * Rețete PRÂNZ 8-10 luni — 15 rețete noi
 * Textură: semi-pasat, bucățele moi de max 1cm
 * Porții: ~90-110g per bebeluș
 */
export const PRANZ_8_10_RECIPES: RecipeCatalogItem[] = [
  {
    id: "orez-pui-broccoli-8",
    name: "Orez moale cu pui și broccoli",
    emoji: "🍚",
    mealType: "pranz",
    time: "30 min",
    age: "8+ luni",
    difficulty: "Mediu",
    servings: "2-3",
    ingredients: [
      "½ cană orez rotund",
      "100g piept de pui",
      "1 cană broccoli buchețele",
      "1 lingură ulei de măsline",
      "1½ căni apă sau supă de legume",
    ],
    steps: [
      "Fierbe puiul 20 minute. Taie cuburi mici de 0.5cm.",
      "Fierbe orezul în supă 20 minute — trebuie să fie moale, aproape lipicios.",
      "Fierbe broccoli la abur 8 minute. Taie buchețelele mărunt.",
      "Amestecă orezul, puiul și broccoli.",
      "Stropește cu ulei. Textura: moale, se zdrobește ușor.",
    ],
    allergens: [],
    relatedFoods: ["orez", "pui", "broccoli"],
    storage: "Se păstrează la frigider 2 zile.",
    totalYieldGrams: 350,
    babyPortionGramsByAgeBand: { "8-10": 100, "10-12": 130 },
  },
  {
    id: "paste-mici-legume-8",
    name: "Paste mici cu legume și brânză",
    emoji: "🍝",
    mealType: "pranz",
    time: "20 min",
    age: "8+ luni",
    difficulty: "Ușor",
    servings: "2",
    ingredients: [
      "60g paste mici (stelline sau risoni)",
      "1 morcov mic ras",
      "¼ cană mazăre",
      "2 linguri brânză de vaci",
      "1 linguriță unt",
    ],
    steps: [
      "Fierbe pastele conform instrucțiunilor + 2 minute extra (să fie moi).",
      "În ultimele 3 minute adaugă mazărea.",
      "Scurge. Pune înapoi în oală.",
      "Adaugă morcovul ras, untul și brânza de vaci.",
      "Amestecă — brânza face un sos cremos. Servește imediat.",
    ],
    allergens: ["Lactoză", "Gluten"],
    relatedFoods: ["paste", "morcov", "mazare", "branza-vaci"],
    storage: "Se servește proaspăt.",
    totalYieldGrams: 280,
    babyPortionGramsByAgeBand: { "8-10": 95, "10-12": 125 },
  },
  {
    id: "linte-rosie-morcov-pranz-8",
    name: "Linte roșie cu morcov și ghimbir",
    emoji: "🍵",
    mealType: "pranz",
    time: "25 min",
    age: "8+ luni",
    difficulty: "Ușor",
    servings: "3-4",
    ingredients: [
      "½ cană linte roșie",
      "2 morcovi",
      "1 linguriță ulei de măsline",
      "½ linguriță ghimbir pudră",
      "1½ căni apă",
    ],
    steps: [
      "Clătește lintea. Pune cu morcovul tăiat cuburi și apa.",
      "Fierbe 20 minute la foc mic. Lintea trebuie să se desfacă.",
      "Adaugă ghimbirul și uleiul.",
      "Pasează parțial — lasă câteva bucăți de morcov moi.",
      "Servește caldă. Textura: grosieră dar fără bucăți tari.",
    ],
    allergens: [],
    relatedFoods: ["linte", "morcov", "ghimbir"],
    storage: "Se păstrează la frigider 4 zile sau congelator 2 luni.",
    totalYieldGrams: 380,
    babyPortionGramsByAgeBand: { "8-10": 100, "10-12": 130 },
  },
  {
    id: "naut-morcov-paste-8",
    name: "Năut pasat cu morcov și paste mici",
    emoji: "🫘",
    mealType: "pranz",
    time: "20 min",
    age: "8+ luni",
    difficulty: "Ușor",
    servings: "2-3",
    ingredients: [
      "½ cană năut fiert (conservă, clătit)",
      "1 morcov",
      "50g paste mici",
      "1 lingură ulei de măsline",
      "½ linguriță suc de lămâie",
    ],
    steps: [
      "Fierbe morcovul cuburi 15 minute. Scurge.",
      "Fierbe pastele bine. Scurge.",
      "Zdrobește năutul cu furculița (nu piure complet — lasă bucățele).",
      "Amestecă năutul, morcovul și pastele.",
      "Stropește cu ulei și lămâie.",
    ],
    allergens: ["Gluten"],
    relatedFoods: ["naut", "morcov", "paste"],
    storage: "Se păstrează la frigider 2 zile.",
    totalYieldGrams: 310,
    babyPortionGramsByAgeBand: { "8-10": 95, "10-12": 125 },
  },
  {
    id: "pui-quinoa-legume-8",
    name: "Pui cu quinoa și legume colorate",
    emoji: "🍗",
    mealType: "pranz",
    time: "30 min",
    age: "8+ luni",
    difficulty: "Mediu",
    servings: "2-3",
    ingredients: [
      "100g piept de pui",
      "¼ cană quinoa",
      "1 morcov mic",
      "¼ cană mazăre",
      "1 linguriță ulei de măsline",
    ],
    steps: [
      "Fierbe puiul 20 minute. Taie foarte mărunt (0.5cm).",
      "Fierbe quinoa cu ½ cană apă 15 minute.",
      "Fierbe morcovul cuburi mici și mazărea 10 minute.",
      "Amestecă quinoa, puiul și legumele.",
      "Stropește cu ulei. Textura variată e bună la 8+ luni.",
    ],
    allergens: [],
    relatedFoods: ["pui", "quinoa", "morcov", "mazare"],
    storage: "Se păstrează la frigider 2 zile.",
    totalYieldGrams: 310,
    babyPortionGramsByAgeBand: { "8-10": 100, "10-12": 130 },
  },
  {
    id: "tofu-morcov-orez-8",
    name: "Tofu moale cu morcov ras și orez",
    emoji: "🍚",
    mealType: "pranz",
    time: "25 min",
    age: "8+ luni",
    difficulty: "Ușor",
    servings: "2",
    ingredients: [
      "100g tofu moale (silken)",
      "1 morcov mic ras",
      "½ cană orez fiert",
      "1 lingură ulei de susan (sau măsline)",
      "½ linguriță turmeric",
    ],
    steps: [
      "Fierbe orezul moale 20-25 minute.",
      "Toacă tofuul în cuburi mici de 0.5cm.",
      "Călește ușor tofuul cu turmericul în ulei 3 minute.",
      "Adaugă morcovul ras. Gătește 2 minute.",
      "Pune orezul în castron, tofuul deasupra.",
    ],
    allergens: ["Soia"],
    relatedFoods: ["tofu", "morcov", "orez", "turmeric"],
    storage: "Se păstrează la frigider 1 zi.",
    totalYieldGrams: 280,
    babyPortionGramsByAgeBand: { "8-10": 95, "10-12": 120 },
  },
  {
    id: "vita-tocata-morcov-orez-8",
    name: "Vită tocată cu morcov și orez",
    emoji: "🥩",
    mealType: "pranz",
    time: "25 min",
    age: "8+ luni",
    difficulty: "Mediu",
    servings: "2-3",
    ingredients: [
      "100g carne tocată de vită (slabă)",
      "1 morcov ras",
      "½ cană orez fiert",
      "1 lingură ulei",
      "½ linguriță boia dulce",
    ],
    steps: [
      "Gătește carnea tocată în ulei, sfărâmând fin. 10 minute.",
      "Adaugă morcovul ras și boia. Gătește 5 minute.",
      "Adaugă orezul fiert. Amestecă.",
      "Carnea trebuie sfărâmată fin — fără bucăți mari.",
      "Servește călduț.",
    ],
    allergens: [],
    relatedFoods: ["vita", "morcov", "orez"],
    storage: "Se păstrează la frigider 2 zile.",
    totalYieldGrams: 320,
    babyPortionGramsByAgeBand: { "8-10": 100, "10-12": 130 },
  },
  {
    id: "somon-orez-dovlecel-8",
    name: "Somon sfărâmat cu orez și dovlecel",
    emoji: "🐟",
    mealType: "pranz",
    time: "25 min",
    age: "8+ luni",
    difficulty: "Mediu",
    servings: "2",
    ingredients: [
      "80g somon proaspăt fără oase",
      "½ cană orez",
      "1 dovlecel mic",
      "1 linguriță unt",
      "1 linguriță suc de lămâie",
    ],
    steps: [
      "Fierbe orezul moale. Scurge.",
      "Gătește somonul la abur 10 minute. VERIFICĂ OASELE!",
      "Taie dovlecelul cuburi mici. Fierbe 8 minute.",
      "Sfărâmă somonul cu furculița.",
      "Amestecă orezul, dovlecelul și somonul. Stropește cu lămâie.",
    ],
    allergens: ["Pește", "Lactoză"],
    relatedFoods: ["somon", "orez", "dovlecel"],
    storage: "Se păstrează la frigider 1 zi.",
    totalYieldGrams: 290,
    babyPortionGramsByAgeBand: { "8-10": 95, "10-12": 120 },
  },
  {
    id: "fasole-naut-legume-8",
    name: "Fasole verde cu năut și cartof",
    emoji: "🫘",
    mealType: "pranz",
    time: "25 min",
    age: "8+ luni",
    difficulty: "Ușor",
    servings: "3-4",
    ingredients: [
      "150g fasole verde",
      "½ cană năut fiert",
      "1 cartof mic",
      "1 linguriță ulei de măsline",
      "½ linguriță suc de lămâie",
    ],
    steps: [
      "Fierbe fasolea verde 12 minute. Taie bucățele de 1cm.",
      "Fierbe cartoful cuburi 15 minute.",
      "Zdrobește năutul cu furculița.",
      "Amestecă totul cu uleiul și lămâia.",
      "Textura grosieră e perfectă la 8+ luni.",
    ],
    allergens: [],
    relatedFoods: ["fasole-verde", "naut", "cartof"],
    storage: "Se păstrează la frigider 3 zile.",
    totalYieldGrams: 350,
    babyPortionGramsByAgeBand: { "8-10": 100, "10-12": 130 },
  },
  {
    id: "omletă-legume-8",
    name: "Omletă moale cu legume",
    emoji: "🥚",
    mealType: "pranz",
    time: "15 min",
    age: "8+ luni",
    difficulty: "Ușor",
    servings: "1",
    ingredients: [
      "2 ouă",
      "1 morcov mic ras",
      "¼ cană mazăre",
      "1 linguriță unt",
      "1 lingură lapte",
    ],
    steps: [
      "Fierbe mazărea 5 minute. Scurge.",
      "Bate ouăle cu laptele.",
      "Topește untul în tigaie la foc mic.",
      "Toarnă ouăle. Adaugă morcovul și mazărea.",
      "Gătește acoperit 5-7 minute. Taie în bețișoare moi.",
    ],
    allergens: ["Ou", "Lactoză"],
    relatedFoods: ["ou", "morcov", "mazare"],
    storage: "Se servește proaspăt.",
    totalYieldGrams: 180,
    babyPortionGramsByAgeBand: { "8-10": 90, "10-12": 120 },
  },
  {
    id: "conopida-pui-orez-8",
    name: "Conopidă cu pui și orez cremos",
    emoji: "🥦",
    mealType: "pranz",
    time: "30 min",
    age: "8+ luni",
    difficulty: "Mediu",
    servings: "2-3",
    ingredients: [
      "1 cană conopidă buchețele",
      "100g piept de pui",
      "½ cană orez rotund",
      "1 lingură unt",
      "1½ căni apă",
    ],
    steps: [
      "Fierbe orezul cu apa 20 minute la foc mic.",
      "Fierbe puiul 20 minute. Taie cuburi mici de 0.5cm.",
      "Fierbe conopida la abur 10 minute. Taie mărunt.",
      "Adaugă untul în orez. Amestecă cu puiul și conopida.",
      "Textura: cremoasă cu bucățele moi.",
    ],
    allergens: ["Lactoză"],
    relatedFoods: ["conopida", "pui", "orez"],
    storage: "Se păstrează la frigider 2 zile.",
    totalYieldGrams: 340,
    babyPortionGramsByAgeBand: { "8-10": 100, "10-12": 130 },
  },
  {
    id: "sfecla-rosie-linte-8",
    name: "Sfeclă cu linte roșie și morcov",
    emoji: "🟣",
    mealType: "pranz",
    time: "30 min",
    age: "8+ luni",
    difficulty: "Mediu",
    servings: "3-4",
    ingredients: [
      "1 sfeclă mică (150g, crudă)",
      "¼ cană linte roșie",
      "1 morcov",
      "1 lingură ulei de măsline",
      "½ linguriță suc de lămâie",
    ],
    steps: [
      "Fierbe sfecla 40-45 minute sau coace la 200°C 1 oră. Curăță.",
      "Fierbe lintea cu morcovul 20 minute.",
      "Taie sfecla cuburi mici de 0.5cm.",
      "Amestecă lintea, morcovul și sfecla.",
      "Stropește cu ulei și lămâie. Atenție: colorează tot violet!",
    ],
    allergens: [],
    relatedFoods: ["sfecla", "linte", "morcov"],
    storage: "Se păstrează la frigider 3 zile.",
    totalYieldGrams: 360,
    babyPortionGramsByAgeBand: { "8-10": 95, "10-12": 120 },
  },
  {
    id: "pui-avocado-orez-8",
    name: "Pui cu avocado și orez",
    emoji: "🥑",
    mealType: "pranz",
    time: "25 min",
    age: "8+ luni",
    difficulty: "Ușor",
    servings: "2",
    ingredients: [
      "100g piept de pui fiert",
      "½ avocado copt",
      "½ cană orez fiert moale",
      "1 linguriță suc de lămâie",
    ],
    steps: [
      "Fierbe puiul 20 minute. Taie cuburi mici.",
      "Fierbe orezul moale. Scurge.",
      "Pasează avocado cu sucul de lămâie.",
      "Pune orezul în castron. Adaugă avocado.",
      "Pune puiul deasupra. Amestecă ușor înainte de servit.",
    ],
    allergens: [],
    relatedFoods: ["pui", "avocado", "orez"],
    storage: "Se servește imediat (avocado se oxidează).",
    totalYieldGrams: 280,
    babyPortionGramsByAgeBand: { "8-10": 95, "10-12": 120 },
  },
  {
    id: "curcan-mazare-piure-8",
    name: "Curcan cu piure de mazăre",
    emoji: "🍗",
    mealType: "pranz",
    time: "25 min",
    age: "8+ luni",
    difficulty: "Mediu",
    servings: "2-3",
    ingredients: [
      "100g carne tocată de curcan",
      "1 cană mazăre congelată",
      "1 linguriță ulei",
      "1 linguriță unt",
      "¼ cană apă",
    ],
    steps: [
      "Gătește curcanul tocat în ulei, sfărâmând fin. 10 minute.",
      "Fierbe mazărea 8 minute. Pasează cu untul și apa.",
      "Lasă câteva mazăre întregi pentru textură.",
      "Pune piureul în castron. Curcanul deasupra.",
      "Amestecă înainte de servit.",
    ],
    allergens: ["Lactoză"],
    relatedFoods: ["curcan", "mazare"],
    storage: "Se păstrează la frigider 2 zile.",
    totalYieldGrams: 290,
    babyPortionGramsByAgeBand: { "8-10": 95, "10-12": 125 },
  },
  {
    id: "broccoli-ou-orez-8",
    name: "Broccoli cu ou fiert și orez",
    emoji: "🥦",
    mealType: "pranz",
    time: "20 min",
    age: "8+ luni",
    difficulty: "Ușor",
    servings: "1-2",
    ingredients: [
      "1 cană broccoli buchețele",
      "2 ouă",
      "½ cană orez fiert moale",
      "1 linguriță ulei de măsline",
    ],
    steps: [
      "Fierbe ouăle 10 minute. Curăță. Taie mărunt.",
      "Fierbe broccoli la abur 8 minute. Taie bucățele mici.",
      "Pune orezul în castron.",
      "Adaugă broccoli și oul tocat.",
      "Stropește cu ulei. Amestecă.",
    ],
    allergens: ["Ou"],
    relatedFoods: ["broccoli", "ou", "orez"],
    storage: "Se servește proaspăt.",
    totalYieldGrams: 260,
    babyPortionGramsByAgeBand: { "8-10": 90, "10-12": 120 },
  },
];

/**
 * Rețete GUSTARE 7-12 luni — 8 rețete
 * Gustările sunt mici, ~30-50g
 * Se servesc între mese principale
 */
export const GUSTARE_RECIPES: RecipeCatalogItem[] = [
  {
    id: "banana-iaurt-scortisoara",
    name: "Banană cu iaurt și scorțișoară",
    emoji: "🍌",
    mealType: "gustare",
    time: "5 min",
    age: "7+ luni",
    difficulty: "Ușor",
    servings: "1",
    ingredients: [
      "½ banană coaptă",
      "2 linguri iaurt natural integral",
      "1 vârf scorțișoară",
    ],
    steps: [
      "Pasează banana cu furculița.",
      "Pune iaurtul în castron mic.",
      "Adaugă banana și amestecă.",
      "Presară scorțișoară.",
      "Servește imediat — banana se oxidează.",
    ],
    allergens: ["Lactoză"],
    relatedFoods: ["banana", "iaurt", "scortisoara"],
    storage: "Consum imediat.",
    totalYieldGrams: 100,
    babyPortionGramsByAgeBand: { "6-8": 40, "8-10": 55, "10-12": 70 },
  },
  {
    id: "mar-fiert-scortisoara",
    name: "Măr fiert cu scorțișoară",
    emoji: "🍎",
    mealType: "gustare",
    time: "15 min",
    age: "6+ luni",
    difficulty: "Ușor",
    servings: "2-3",
    ingredients: [
      "2 mere",
      "½ linguriță scorțișoară",
      "2 linguri apă",
    ],
    steps: [
      "Curăță merele, taie cuburi.",
      "Pune cu apa și scorțișoara într-o crăticioară.",
      "Fierbe acoperit 10-12 minute.",
      "Pasează fin (6 luni) sau lasă cuburi moi (8+ luni).",
      "Servește călduț sau rece.",
    ],
    allergens: [],
    relatedFoods: ["mere", "scortisoara"],
    storage: "Se păstrează la frigider 3 zile.",
    totalYieldGrams: 200,
    babyPortionGramsByAgeBand: { "4-6": 35, "6-8": 45, "8-10": 60, "10-12": 75 },
  },
  {
    id: "avocado-suc-lamaie",
    name: "Avocado pasat cu lămâie",
    emoji: "🥑",
    mealType: "gustare",
    time: "3 min",
    age: "6+ luni",
    difficulty: "Ușor",
    servings: "1",
    ingredients: [
      "½ avocado copt",
      "½ linguriță suc de lămâie",
    ],
    steps: [
      "Taie avocado în jumătate. Scoate sâmburele.",
      "Scoate miezul cu o lingură.",
      "Pasează cu furculița.",
      "Adaugă sucul de lămâie și amestecă.",
      "Servește imediat — nu se păstrează.",
    ],
    allergens: [],
    relatedFoods: ["avocado"],
    storage: "Consum imediat.",
    totalYieldGrams: 80,
    babyPortionGramsByAgeBand: { "4-6": 30, "6-8": 40, "8-10": 55, "10-12": 65 },
  },
  {
    id: "pere-iaurt-ghimbir",
    name: "Compot de pere cu iaurt",
    emoji: "🍐",
    mealType: "gustare",
    time: "15 min",
    age: "7+ luni",
    difficulty: "Ușor",
    servings: "2",
    ingredients: [
      "2 pere coapte",
      "2 linguri iaurt natural",
      "1 vârf ghimbir pudră (opțional)",
    ],
    steps: [
      "Curăță perele, taie cuburi.",
      "Fierbe cu 2 linguri apă 10 minute.",
      "Lasă să se răcească.",
      "Pune iaurtul în castron, perele deasupra.",
      "Presară ghimbir dacă bebelușul îl tolerează.",
    ],
    allergens: ["Lactoză"],
    relatedFoods: ["pere", "iaurt"],
    storage: "Se păstrează la frigider 2 zile.",
    totalYieldGrams: 200,
    babyPortionGramsByAgeBand: { "6-8": 45, "8-10": 60, "10-12": 80 },
  },
  {
    id: "piure-pruna-iaurt",
    name: "Prune coapte cu iaurt",
    emoji: "🫐",
    mealType: "gustare",
    time: "10 min",
    age: "7+ luni",
    difficulty: "Ușor",
    servings: "2",
    ingredients: [
      "3 prune coapte (sau 4-5 prune uscate înmuiate)",
      "3 linguri iaurt natural",
    ],
    steps: [
      "Fierbe prunele proaspete 8 minute sau înmoaie cele uscate 15 minute.",
      "Scoate sâmburii. Pasează prunele.",
      "Pune iaurtul în castron.",
      "Adaugă piureul de prune deasupra.",
      "Bun și pentru constipație!",
    ],
    allergens: ["Lactoză"],
    relatedFoods: ["prune", "iaurt"],
    storage: "Se păstrează la frigider 2 zile.",
    totalYieldGrams: 150,
    babyPortionGramsByAgeBand: { "6-8": 40, "8-10": 55, "10-12": 70 },
  },
  {
    id: "cartof-dulce-copt-gustare",
    name: "Cartof dulce copt cu scorțișoară",
    emoji: "🍠",
    mealType: "gustare",
    time: "30 min",
    age: "6+ luni",
    difficulty: "Ușor",
    servings: "2-3",
    ingredients: [
      "1 cartof dulce mic",
      "1 linguriță unt",
      "1 vârf scorțișoară",
    ],
    steps: [
      "Coace cartoful dulce întreg la 200°C, 30-35 minute.",
      "Verifică cu furculița — trebuie să fie moale complet.",
      "Taie în jumătate. Scoate miezul cu lingura.",
      "Adaugă untul și scorțișoara.",
      "Amestecă. Servește în cupe sau bețișoare moi.",
    ],
    allergens: ["Lactoză"],
    relatedFoods: ["cartof-dulce", "scortisoara"],
    storage: "Se păstrează la frigider 2 zile.",
    totalYieldGrams: 180,
    babyPortionGramsByAgeBand: { "4-6": 35, "6-8": 50, "8-10": 65, "10-12": 80 },
  },
  {
    id: "branza-vaci-afine-8",
    name: "Brânză de vaci cu afine",
    emoji: "🫐",
    mealType: "gustare",
    time: "5 min",
    age: "8+ luni",
    difficulty: "Ușor",
    servings: "1",
    ingredients: [
      "3 linguri brânză de vaci",
      "¼ cană afine proaspete sau congelate (decongelate)",
      "1 vârf vanilie (opțional)",
    ],
    steps: [
      "Dacă folosești afine congelate, dezgheață-le.",
      "Zdrobește ușor afinele cu furculița.",
      "Pune brânza de vaci în castron.",
      "Adaugă afinele zdrobite deasupra.",
      "Amestecă ușor sau lasă stratificate.",
    ],
    allergens: ["Lactoză"],
    relatedFoods: ["branza-vaci", "afine"],
    storage: "Se păstrează la frigider 1 zi.",
    totalYieldGrams: 130,
    babyPortionGramsByAgeBand: { "8-10": 50, "10-12": 70 },
  },
  {
    id: "capsuni-banane-iaurt-10",
    name: "Căpșuni cu banană și iaurt grecesc",
    emoji: "🍓",
    mealType: "gustare",
    time: "5 min",
    age: "10+ luni",
    difficulty: "Ușor",
    servings: "1",
    ingredients: [
      "3-4 căpșuni coapte",
      "½ banană",
      "2 linguri iaurt grecesc natural",
    ],
    steps: [
      "Spală și toacă căpșunile mărunt.",
      "Feliază banana.",
      "Pune iaurtul în castron.",
      "Adaugă fructele deasupra.",
      "La 10 luni poți lăsa bucăți — finger food!",
    ],
    allergens: ["Lactoză"],
    relatedFoods: ["capsuni", "banana", "iaurt"],
    storage: "Se servește proaspăt.",
    totalYieldGrams: 150,
    babyPortionGramsByAgeBand: { "10-12": 65 },
  },
];