import { CINA_12PLUS_DINNER_RECIPES } from "./cina12PlusDinnerRecipes";
import {
  CINA_10PLUS_DINNER_RECIPES,
  CINA_8PLUS_RECIPES,
} from "./cinaDinnerRecipes";
import {
  MIC_DEJUN_10PLUS_EXTRA,
  MIC_DEJUN_12PLUS_EXTRA,
  MIC_DEJUN_8PLUS_EXTRA,
} from "./micDejunExtraRecipes";
import {
  PRANZ_6_8_RECIPES,
  PRANZ_8_10_RECIPES,
  GUSTARE_RECIPES,
} from "./pranzSiGustariNoi";
import { PRANZ_12PLUS_RECIPES } from "./pranz12PlusRecipes";
import { GUSTARI_12PLUS_RECIPES } from "./gustari12PlusRecipes";

export type MealType = "mic-dejun" | "pranz" | "cina" | "gustare";

/** Benzi de vârstă pentru porții recomandate (luni). */
export type AgeBandId = "6-7" | "7-8" | "8-10" | "10-12";
type LegacyAgeBandId = "6-8";

export type RecipeCatalogItem = {
  id: string;
  name: string;
  emoji: string;
  mealType: MealType;
  time: string;
  age: string;
  difficulty: "Ușor" | "Mediu";
  /** Reținut pentru compatibilitate; poate reflecta porții „familie” sau un batch. */
  servings: number | string;
  ingredients: string[];
  steps: string[];
  relatedFoods: string[];
  allergens: string[];
  storage: string;
  /**
   * Greutate aproximativă a preparatului gata (tot bolul / tava), în g.
   * Folosit pentru a calcula câte porții pentru bebe ies din rețetă.
   */
  totalYieldGrams?: number;
  /**
   * Porție recomandată (g preparat) per bandă, pentru bebeluș.
   * Lipsă = se folosesc valorile implicite din `recipePortions.ts`.
   */
  babyPortionGramsByAgeBand?: Partial<Record<AgeBandId | LegacyAgeBandId, number>>;
  /** Notă scurtă despre textură per bandă (opțional). */
  textureNoteByAgeBand?: Partial<Record<AgeBandId | LegacyAgeBandId, string>>;
};

const LEGACY_RECIPES: RecipeCatalogItem[] = [
  {
    id: "piure-dovlecel",
    name: "Piure de dovlecel",
    emoji: "🥒",
    mealType: "pranz",
    time: "15 min",
    age: "6+ luni",
    difficulty: "Ușor",
    servings: 1,
    ingredients: [
      "1 dovlecel mic (150g)",
      "1 linguriță ulei de măsline extravirgin",
      "50ml apă de la fiert sau lapte matern",
    ],
    steps: [
      "Spală bine dovlecelul și curăță-l de coajă",
      "Taie-l în cuburi mici de ~2cm",
      "Pune cuburile într-o crăticioară cu apă care le acoperă",
      "Fierbe la foc mic 10-12 minute până se înmoaie complet",
      "Scurge apa (păstrează puțină pentru consistență)",
      "Pasează cu blenderul vertical până obții un piure fin",
      "Adaugă uleiul de măsline și amestecă",
      "Lasă să se răcească la temperatura camerei înainte de servire",
    ],
    relatedFoods: ["dovlecel"],
    allergens: [],
    storage: "Se păstrează la frigider în recipient închis până la 2 zile.",
    totalYieldGrams: 220,
    babyPortionGramsByAgeBand: {
      "6-8": 65,
      "8-10": 95,
      "10-12": 115,
    },
  },
  {
    id: "piure-morcov",
    name: "Piure morcov & cartof dulce",
    emoji: "🥕",
    mealType: "pranz",
    time: "20 min",
    age: "6+ luni",
    difficulty: "Ușor",
    servings: 1,
    ingredients: [
      "2 morcovi medii (200g)",
      "1 cartof dulce mic (100g)",
      "1 linguriță unt nesărat",
      "50ml lapte matern sau formulă",
    ],
    steps: [
      "Curăță morcovii și cartoful dulce",
      "Taie-le în rondele subțiri pentru fierbere uniformă",
      "Pune într-o crăticioară cu apă rece și adu la fierbere",
      "Fierbe 15-20 minute până sunt foarte moi (testează cu furculița)",
      "Scurge apa",
      "Adaugă untul și laptele",
      "Pasează cu blenderul până obții consistența dorită",
      "Servește călduț, nu fierbinte",
    ],
    relatedFoods: ["morcov", "cartof-dulce"],
    allergens: ["Lactoză"],
    storage: "Se păstrează la frigider până la 2 zile.",
  },
  {
    id: "piure-banana",
    name: "Piure de banană & avocado",
    emoji: "🍌",
    mealType: "mic-dejun",
    time: "5 min",
    age: "6+ luni",
    difficulty: "Ușor",
    servings: 1,
    ingredients: [
      "1 banană coaptă (cu pete maronii pe coajă)",
      "½ avocado copt",
      "2 linguri lapte matern sau formulă",
      "Un vârf de cuțit de scorțișoară (opțional, 8+ luni)",
    ],
    steps: [
      "Curăță banana și scoate miezul de avocado",
      "Pune într-un castron",
      "Pasează cu furculița până devine cremos (nu e nevoie de blender)",
      "Adaugă laptele matern pentru consistență mai fină",
      "Amestecă bine",
      "Servește imediat — nu se păstrează, se oxidează repede",
    ],
    relatedFoods: ["banana", "avocado"],
    allergens: ["Lactoză"],
    storage: "Consum imediat după preparare.",
  },
  {
    id: "supa-dovleac",
    name: "Supă cremă de dovleac",
    emoji: "🎃",
    mealType: "cina",
    time: "25 min",
    age: "6+ luni",
    difficulty: "Mediu",
    servings: "2-3",
    ingredients: [
      "300g dovleac curățat",
      "1 cartof mic",
      "1 morcov",
      "1 ceapă mică",
      "1 lingură ulei de măsline",
      "400ml apă sau supă de legume",
      "1 lingură smântână (opțional, 8+ luni)",
    ],
    steps: [
      "Curăță și taie toate legumele în cuburi",
      "Încălzește uleiul într-o oală și călește ceapa 2 minute",
      "Adaugă restul legumelor și amestecă",
      "Toarnă apa/supa și adu la fierbere",
      "Fierbe la foc mic 20-25 minute până toate legumele sunt moi",
      "Pasează cu blenderul vertical direct în oală",
      "Adaugă smântâna dacă bebelușul are peste 8 luni",
      "Servește călduță",
    ],
    relatedFoods: ["dovleac", "cartof", "morcov"],
    allergens: ["Lactoză"],
    storage: "Se păstrează la frigider până la 3 zile sau se congelează 2 luni.",
  },
  {
    id: "piure-pui",
    name: "Piure de pui cu legume",
    emoji: "🍗",
    mealType: "pranz",
    time: "30 min",
    age: "6+ luni",
    difficulty: "Mediu",
    servings: "1-2",
    ingredients: [
      "100g piept de pui",
      "1 dovlecel mic",
      "1 morcov",
      "1 cartof mic",
      "1 linguriță ulei de măsline",
    ],
    steps: [
      "Fierbe pieptul de pui în apă fără sare 20-25 minute",
      "Separat, fierbe legumele tăiate cuburi 15 minute",
      "Scurge apa de la ambele",
      "Pune totul în blender",
      "Adaugă uleiul de măsline și puțină apă de la fiert",
      "Pasează până obții consistența potrivită vârstei",
      "Pentru 6 luni: piure foarte fin. Pentru 8+ luni: poți lăsa bucățele mici",
    ],
    relatedFoods: ["pui", "dovlecel", "morcov", "cartof"],
    allergens: [],
    storage: "Se păstrează la frigider până la 2 zile.",
  },
  {
    id: "budinca-orez",
    name: "Budincă de orez cu pere",
    emoji: "🍐",
    mealType: "gustare",
    time: "35 min",
    age: "7+ luni",
    difficulty: "Mediu",
    servings: 1,
    ingredients: [
      "50g orez rotund",
      "1 pară coaptă",
      "200ml lapte (matern sau formulă)",
      "100ml apă",
      "1 linguriță unt nesărat",
    ],
    steps: [
      "Spală orezul de 2-3 ori sub jet de apă",
      "Pune orezul cu apa într-o crăticioară la foc mic",
      "Când apa scade, adaugă laptele treptat, amestecând",
      "Gătește 20-25 minute amestecând des (ca un risotto)",
      "Curăță para și rade-o pe răzătoare",
      "Adaugă para rasă și untul în ultimele 5 minute",
      "Amestecă bine și lasă să se răcească",
      "Servește călduță — consistența trebuie să fie cremoasă",
    ],
    relatedFoods: ["orez", "pere"],
    allergens: ["Lactoză"],
    storage: "Se păstrează la frigider până la 2 zile.",
  },
];

const MIC_DEJUN_RECIPES: RecipeCatalogItem[] = [
  {
    id: "iaurt-unt-migdale",
    name: "Iaurt cu unt de migdale",
    emoji: "🥣",
    mealType: "mic-dejun",
    time: "5 min",
    age: "6+ luni",
    difficulty: "Ușor",
    servings: 1,
    ingredients: [
      "1 cană iaurt natural integral fără zahăr",
      "1 lingură unt de migdale fin (fără bucăți)",
      "1 măr mic (opțional)",
      "1 vârf scorțișoară (opțional)",
    ],
    steps: [
      "Amestecă iaurtul cu untul de migdale într-un castron până e omogen. Nu trebuie să rămână bucăți de unt.",
      "Spală, curăță și rade mărul pe răzătoarea fină.",
      "Pune mărul ras peste iaurt.",
      "Presară un vârf de scorțișoară deasupra.",
      "Servește și lasă bebelușul să mănânce singur cu mâinile sau cu lingurița pre-încărcată.",
    ],
    allergens: ["Lactoză", "Nuci (migdale)"],
    relatedFoods: ["iaurt", "unt-migdale", "mere"],
    storage: "Se păstrează la frigider în recipient închis 3 zile.",
  },
  {
    id: "toast-avocado",
    name: "Pâine moale cu avocado",
    emoji: "🥑",
    mealType: "mic-dejun",
    time: "5 min",
    age: "8+ luni",
    difficulty: "Ușor",
    servings: 1,
    ingredients: [
      "1 felie pâine moale",
      "½ avocado copt",
      "¼ linguriță suc de lămâie",
      "¼ linguriță ulei de măsline",
      "1 vârf semințe de susan (opțional)",
    ],
    steps: [
      "Taie pâinea moale în bucăți potrivite pentru bebeluș.",
      "Curăță avocado și scoate sâmburele.",
      "Pasează jumătate din avocado și întinde pe pâinea moale.",
      "Taie cealaltă jumătate în bețișoare subțiri.",
      "Taie pâinea moale în bețișoare groase cât 2 degete.",
      "Stropește cu ulei de măsline și suc de lămâie.",
      "Presară semințe de susan deasupra.",
    ],
    allergens: ["Gluten", "Susan"],
    relatedFoods: ["avocado", "paine", "ulei-masline"],
    storage: "Avocado tăiat se păstrează în coaja lui la frigider 3 zile.",
  },
  {
    id: "bol-fasole-neagra",
    name: "Bol de fasole neagră cu avocado",
    emoji: "🫘",
    mealType: "mic-dejun",
    time: "5 min",
    age: "6+ luni",
    difficulty: "Ușor",
    servings: 1,
    ingredients: [
      "½ cană fasole neagră fiartă (din conservă clătită bine)",
      "1 avocado copt",
      "1 vârf semințe de cânepă",
    ],
    steps: [
      "Clătește fasolea pentru a elimina excesul de sodiu.",
      "Pasează fasolea în castronul bebelușului până e aproape omogenă.",
      "Curăță avocado, pasează o jumătate și amestecă cu fasolea.",
      "Taie cealaltă jumătate în bețișoare și rostogolește prin semințe de cânepă.",
      "Lasă bebelușul să mănânce singur cu mâinile.",
    ],
    allergens: [],
    relatedFoods: ["avocado"],
    storage: "Fasolea deschisă se păstrează la frigider 4 zile.",
  },
  {
    id: "polenta-afine",
    name: "Mămăligă cu afine",
    emoji: "🫐",
    mealType: "mic-dejun",
    time: "15 min",
    age: "6+ luni",
    difficulty: "Ușor",
    servings: 1,
    ingredients: [
      "¼ cană afine proaspete sau congelate",
      "¾ cană apă",
      "¼ cană lapte (matern sau formulă)",
      "¼ cană mălai instant",
      "2-3 căpșuni (opțional)",
    ],
    steps: [
      "Spală afinele și pasează-le cu furculița.",
      "Fierbe apa cu laptele.",
      "Scade focul și adaugă treptat mălaiul și afinele pasate, amestecând continuu.",
      "Gătește 5 minute la foc mic, amestecând des.",
      "Acoperă și lasă să se îngroașe 5 minute.",
      "Răcește la temperatura camerei înainte de servire.",
      "Taie căpșunile în bucăți potrivite vârstei și servește pe lângă.",
    ],
    allergens: ["Lactoză"],
    relatedFoods: ["afine", "capsuni", "porumb"],
    storage: "Se păstrează la frigider în recipient închis 3 zile.",
  },
  {
    id: "salata-ou-avocado",
    name: "Salată de ou cu avocado",
    emoji: "🥚",
    mealType: "mic-dejun",
    time: "15 min",
    age: "6+ luni",
    difficulty: "Ușor",
    servings: 1,
    ingredients: [
      "3 ouă",
      "1 avocado copt",
      "1 vârf pudră de ceapă (opțional)",
      "1 linguriță semințe de cânepă (opțional)",
    ],
    steps: [
      "Fierbe ouăle tare: pune-le în apă clocotită, acoperă, gătește 13 minute.",
      "Transferă ouăle în apă cu gheață. Curăță când s-au răcit.",
      "Taie ouăle în sferturi.",
      "Curăță avocado și pasează o jumătate cu ouăle și pudra de ceapă.",
      "Taie cealaltă jumătate în bețișoare și rostogolește prin semințe de cânepă.",
      "Pune salata în castronul bebelușului.",
    ],
    allergens: ["Ou"],
    relatedFoods: ["ou", "avocado"],
    storage: "Salata de ou se păstrează la frigider 5 zile.",
  },
  {
    id: "scramble-ou-dovlecel",
    name: "Omletă de dovlecel",
    emoji: "🥒",
    mealType: "mic-dejun",
    time: "15 min",
    age: "6+ luni",
    difficulty: "Ușor",
    servings: 1,
    ingredients: [
      "½ dovlecel mic",
      "2 ouă",
      "1 linguriță ulei de măsline",
      "1 vârf semințe de susan (opțional)",
      "1 roșie (opțional)",
    ],
    steps: [
      "Spală și rade dovlecelul pe răzătoare.",
      "Bate ouăle într-un castron.",
      "Încălzește uleiul într-o tigaie la foc mediu.",
      "Adaugă dovlecelul ras și gătește 5 minute amestecând.",
      "Toarnă ouăle peste dovlecel și amestecă continuu.",
      "Gătește până ouăle sunt pufoase și complet fierte, ~5 minute.",
      "Răcește la temperatura camerei. Presară susan.",
      "Taie roșia în bucăți potrivite vârstei și servește pe lângă.",
    ],
    allergens: ["Ou", "Susan"],
    relatedFoods: ["dovlecel", "ou", "rosii", "ulei-masline"],
    storage: "Se păstrează la frigider 3 zile.",
  },
  {
    id: "iaurt-unt-arahide",
    name: "Iaurt cu unt de arahide și banană",
    emoji: "🥜",
    mealType: "mic-dejun",
    time: "5 min",
    age: "6+ luni",
    difficulty: "Ușor",
    servings: 1,
    ingredients: [
      "1 cană iaurt natural integral",
      "1 lingură unt de arahide fin (fără bucăți)",
      "1 banană coaptă (opțional)",
      "1 vârf arahide măcinate (opțional)",
    ],
    steps: [
      "Amestecă iaurtul cu untul de arahide până e complet omogen.",
      "Adaugă mai mult iaurt dacă e prea dens.",
      "Taie banana în bețișoare și rostogolește prin arahide măcinate.",
      "Servește iaurtul cu bețișoarele de banană pe lângă.",
    ],
    allergens: ["Lactoză", "Arahide"],
    relatedFoods: ["iaurt", "unt-arahide", "banana"],
    storage: "Se păstrează la frigider 3 zile.",
  },
  {
    id: "budinca-chia-cocos",
    name: "Budincă de chia cu cocos și mango",
    emoji: "🥥",
    mealType: "mic-dejun",
    time: "5 min + peste noapte",
    age: "6+ luni",
    difficulty: "Ușor",
    servings: "2-4",
    ingredients: [
      "1 banană coaptă",
      "¾ cană lapte de cocos integral",
      "3 linguri semințe de chia",
      "¼ linguriță scorțișoară (opțional)",
      "1 vârf nuci pecan măcinate (opțional)",
      "1 mango copt (opțional)",
    ],
    steps: [
      "Pregătește seara dinainte!",
      "Curăță și pasează banana într-un borcan de sticlă.",
      "Adaugă laptele de cocos, semințele de chia și scorțișoara.",
      "Închide borcanul și agită bine.",
      "Pune la frigider peste noapte (minim 1 oră).",
      "Dimineața: pune budinca în castronul bebelușului.",
      "Curăță mango și taie în bețișoare.",
      "Presară nuci pecan măcinate deasupra.",
    ],
    allergens: ["Nucă de cocos", "Nuci (pecan)"],
    relatedFoods: ["banana", "mango", "seminte-macinate", "unt-cocos"],
    storage: "Se păstrează la frigider 1 săptămână.",
  },
  {
    id: "orez-cu-ou-curry",
    name: "Orez cu cocos, curry și ou",
    emoji: "🍚",
    mealType: "mic-dejun",
    time: "30 min",
    age: "8+ luni",
    difficulty: "Mediu",
    servings: "2-3",
    ingredients: [
      "½ cană orez basmati",
      "½ cană lapte de cocos integral",
      "½ cană apă",
      "½ linguriță curry dulce",
      "1 ou",
      "1 linguriță ulei de măsline",
      "½ cană iaurt natural (opțional)",
      "½ linguriță arahide măcinate (opțional)",
    ],
    steps: [
      "Clătește orezul bine.",
      "Pune orezul, laptele de cocos, apa și curry-ul la fiert.",
      "Când fierbe, scade focul și acoperă. Gătește 15 minute.",
      "Lasă acoperit 10 minute, apoi aerisește cu furculița.",
      "Separat, bate oul și fă-l jumări în ulei de măsline.",
      "Pune iaurtul în castron, adaugă orezul și oul deasupra.",
      "Presară arahide măcinate.",
    ],
    allergens: ["Lactoză", "Nucă de cocos", "Ou", "Arahide"],
    relatedFoods: ["orez", "ou", "iaurt", "unt-cocos", "unt-arahide"],
    storage: "Orezul se păstrează la frigider 2 zile.",
  },
  {
    id: "omleta-legume-curcubeu",
    name: "Omletă curcubeu cu legume",
    emoji: "🌈",
    mealType: "mic-dejun",
    time: "30 min",
    age: "8+ luni",
    difficulty: "Mediu",
    servings: "1-2",
    ingredients: [
      "¼ cană dovleac plăcintar cuburi",
      "¼ cană broccoli buchețele",
      "1 ardei gras roșu mic",
      "2 lingurițe ulei de măsline",
      "3 ouă",
      "2 linguri ricotta sau brânză de vaci (opțional)",
      "1 vârf semințe de susan (opțional)",
    ],
    steps: [
      "Spală și taie mărunt dovleacul și broccoli. Fierbe la abur până sunt moi.",
      "Spală ardeiul, scoate semințele, taie mărunt.",
      "Încălzește uleiul, călește ardeiul 5 minute.",
      "Bate ouăle și adaugă dovleacul și broccoli fiert.",
      "Toarnă amestecul de ouă peste ardei în tigaie.",
      "Acoperă, gătește la foc mic 5 minute.",
      "Adaugă ricotta deasupra, acoperă încă 3 minute.",
      "Taie în bețișoare. Răcește și presară susan.",
    ],
    allergens: ["Ou", "Lactoză", "Susan"],
    relatedFoods: ["ou", "broccoli", "ardei-gras", "dovleac-butternut", "branza-vaci"],
    storage: "Se păstrează la frigider 4 zile sau congelator 2 luni.",
  },
  {
    id: "terci-ovaz-piersici",
    name: "Terci de ovăz cu piersici",
    emoji: "🍑",
    mealType: "mic-dejun",
    time: "15 min",
    age: "6+ luni",
    difficulty: "Ușor",
    servings: 1,
    ingredients: [
      "½ piersică proaspătă sau congelată",
      "¼ cană fulgi de ovăz instant",
      "¼ cană lapte (matern sau formulă)",
      "¼ cană apă",
      "1 vârf scorțișoară sau cardamom (opțional)",
      "¼ cană zmeură (opțional)",
      "1 vârf migdale măcinate (opțional)",
    ],
    steps: [
      "Spală piersica, opărește pentru a curăța coaja, scoate sâmburele.",
      "Pasează piersica.",
      "Fierbe laptele cu apa, adaugă piersica pasată.",
      "Adaugă fulgii de ovăz și condimentul. Amestecă.",
      "Acoperă 5 minute. Lasă să se răcească.",
      "Pune în castronul bebelușului.",
      "Adaugă zmeura și migdalele măcinate deasupra.",
    ],
    allergens: ["Lactoză", "Gluten", "Nuci (migdale)"],
    relatedFoods: ["piersici", "ovaz", "zmeura", "unt-migdale"],
    storage: "Se păstrează la frigider 3 zile.",
  },
  {
    id: "terci-mov-afine",
    name: "Terci mov de ovăz cu afine",
    emoji: "🟣",
    mealType: "mic-dejun",
    time: "15 min",
    age: "6+ luni",
    difficulty: "Ușor",
    servings: 1,
    ingredients: [
      "¼ cană afine proaspete sau congelate",
      "¼ cană fulgi de ovăz instant",
      "¼ cană lapte",
      "¼ cană apă",
      "1 vârf fulgi de cocos (opțional)",
      "1 banană (opțional)",
    ],
    steps: [
      "Spală afinele și pasează-le.",
      "Fierbe laptele cu apa.",
      "Adaugă fulgii de ovăz și afinele pasate. Amestecă.",
      "Acoperă 5 minute. Lasă să se răcească.",
      "Pune în castronul bebelușului. Devine mov frumos!",
      "Presară fulgi de cocos. Taie banana în bețișoare pe lângă.",
    ],
    allergens: ["Lactoză", "Nucă de cocos"],
    relatedFoods: ["afine", "ovaz", "banana", "unt-cocos"],
    storage: "Se păstrează la frigider 1 săptămână.",
  },
  {
    id: "clatite-banana-naut",
    name: "Clătite din făină de năut cu banană",
    emoji: "🥞",
    mealType: "mic-dejun",
    time: "30 min",
    age: "8+ luni",
    difficulty: "Mediu",
    servings: "3-4",
    ingredients: [
      "1 banană coaptă",
      "¾ cană lapte",
      "1 linguriță extract de vanilie",
      "1 cană făină de năut",
      "1 linguriță praf de copt",
      "1 linguriță scorțișoară",
      "2 linguri ulei de cocos",
      "½ cană ricotta (opțional)",
      "1 linguriță unt de arahide (opțional)",
    ],
    steps: [
      "Pasează banana. Amestecă cu laptele și vanilia.",
      "Separat, amestecă ingredientele uscate (făina, praful de copt, scorțișoara).",
      "Toarnă ingredientele umede peste cele uscate. Amestecă. Cocoloașele sunt ok!",
      "Încălzește uleiul de cocos într-o tigaie la foc mediu.",
      "Pune câte 2 linguri de aluat și aplatizează ușor.",
      "Gătește 3 minute pe fiecare parte până sunt aurii.",
      "Amestecă ricotta cu untul de arahide pentru un dip cremos.",
      "Servește 2-3 clătite cu dip-ul pe lângă. Răcește bine!",
    ],
    allergens: ["Lactoză", "Nucă de cocos", "Arahide"],
    relatedFoods: ["banana", "naut", "unt-cocos", "unt-arahide"],
    storage: "Clătitele se păstrează la frigider 2 zile sau congelator 2 luni.",
  },
  {
    id: "clatite-dovleac-ricotta",
    name: "Clătite de dovleac cu ricotta",
    emoji: "🎃",
    mealType: "mic-dejun",
    time: "30 min",
    age: "8+ luni",
    difficulty: "Mediu",
    servings: "3-4",
    ingredients: [
      "4 linguri unt nesărat",
      "2 ouă",
      "¾ cană lapte",
      "¼ cană piure de dovleac",
      "½ cană ricotta",
      "½ linguriță extract de vanilie",
      "½ cană făină integrală",
      "¼ cană făină de porumb",
      "1 linguriță praf de copt",
      "⅛ linguriță scorțișoară",
      "1 banană (opțional)",
      "1 linguriță nuci pecan măcinate (opțional)",
    ],
    steps: [
      "Topește 2 linguri de unt. Amestecă cu ouăle, laptele, dovleacul, ¼ cană ricotta și vanilia.",
      "Separat, amestecă ingredientele uscate.",
      "Combină ingredientele umede cu cele uscate.",
      "Încălzește restul de unt în tigaie la foc mediu.",
      "Pune câte 2 linguri de aluat, aplatizează.",
      "Gătește 3 minute pe fiecare parte.",
      "Taie banana în bețișoare și rostogolește prin nuci pecan.",
      "Servește 2-3 clătite cu ricotta și banană pe lângă.",
    ],
    allergens: ["Lactoză", "Ou", "Gluten", "Nuci (pecan)"],
    relatedFoods: ["dovleac", "ou", "branza-vaci", "banana"],
    storage: "Clătitele se păstrează la frigider 2 zile sau congelator 2 luni.",
  },
  {
    id: "piure-cartof-dulce-scortisoara",
    name: "Piure de cartof dulce cu scorțișoară",
    emoji: "🍠",
    mealType: "mic-dejun",
    time: "20 min",
    age: "6+ luni",
    difficulty: "Ușor",
    servings: 1,
    ingredients: [
      "1 cartof dulce mediu",
      "1 felie pâine moale (opțional)",
      "1 vârf scorțișoară (opțional)",
    ],
    steps: [
      "Curăță cartoful dulce și taie-l în cuburi.",
      "Fierbe în apă 10-15 minute până se înmoaie.",
      "Scurge și pasează până e fin, adaugă apă dacă e prea dens.",
      "Prăjește ușor pâinea și taie-o în bețișoare.",
      "Pune piureul în castronul bebelușului.",
      "Presară scorțișoară și servește cu bețișoarele de pâine.",
    ],
    allergens: ["Gluten"],
    relatedFoods: ["cartof-dulce", "paine", "scortisoara"],
    storage: "Se păstrează la frigider 3 zile.",
  },
  {
    id: "orez-lapte-cocos-scortisoara",
    name: "Orez cu lapte de cocos și scorțișoară",
    emoji: "🍚",
    mealType: "mic-dejun",
    time: "1 oră",
    age: "8+ luni",
    difficulty: "Mediu",
    servings: "3-6",
    ingredients: [
      "1 cană orez basmati",
      "2 căni apă",
      "¾ cană lapte de cocos integral",
      "⅛ linguriță scorțișoară Ceylon",
      "1 linguriță ulei de cocos",
      "1 linguriță semințe de susan (opțional)",
      "2-3 felii de portocală (opțional)",
    ],
    steps: [
      "Clătește orezul și înmoaie-l 30 minute în apă. Scurge.",
      "Pune orezul cu 2 căni de apă la fiert.",
      "Când fierbe, scade focul, acoperă. Gătește 15-20 minute.",
      "Adaugă laptele de cocos și scorțișoara. Amestecă.",
      "Gătește acoperit încă 10 minute la foc mic.",
      "Unge o tavă cu uleiul de cocos.",
      "Pune orezul în tavă și aplatizează.",
      "Presară semințe de susan. Lasă să se răcească — se întărește.",
      "Taie în dreptunghiuri sau triunghiuri.",
      "Servește 1-2 forme cu felii de portocală pe lângă.",
    ],
    allergens: ["Nucă de cocos", "Susan"],
    relatedFoods: ["orez", "unt-cocos", "scortisoara", "portocale"],
    storage: "Se păstrează la frigider 1 săptămână.",
  },
  {
    id: "piure-sfecla-morcov",
    name: "Piure de sfeclă și morcov",
    emoji: "🟣",
    mealType: "mic-dejun",
    time: "40 min",
    age: "8+ luni",
    difficulty: "Mediu",
    servings: "1-2 copii + 2-3 adulți",
    ingredients: [
      "2 morcovi medii",
      "2 sfecle medii",
      "1 cană lapte (de cocos, matern sau formulă)",
      "1 vârf scorțișoară, coriandru și chimion (opțional)",
      "1 lingură tahini de susan (opțional)",
      "1 felie pâine moale",
      "½ cană iaurt natural (opțional)",
      "1 vârf migdale măcinate (opțional)",
    ],
    steps: [
      "Curăță și taie morcovii și sfecla în cuburi.",
      "Pune-le într-o oală cu laptele și apă cât să le acopere.",
      "Adaugă condimentele. Fierbe la foc mic 40 minute.",
      "Scurge legumele (păstrează lichidul).",
      "Pasează cu tahini, adăugând lichid pentru consistență.",
      "Răcește la temperatura camerei.",
      "Prăjește pâinea și taie-o în bețișoare.",
      "Pune piureul în castron, presară migdale, servește cu pâinea.",
      "Atenție: totul va deveni roz!",
    ],
    allergens: ["Lactoză", "Susan", "Nuci (migdale)", "Nucă de cocos", "Gluten"],
    relatedFoods: ["sfecla", "morcov", "iaurt", "paine", "unt-migdale"],
    storage: "Se păstrează la frigider 5 zile.",
  },
  {
    id: "scramble-ou-tofu",
    name: "Scramble de ou cu tofu",
    emoji: "🧈",
    mealType: "mic-dejun",
    time: "15 min",
    age: "8+ luni",
    difficulty: "Ușor",
    servings: 1,
    ingredients: [
      "60g tofu ferm",
      "2 ouă",
      "1 linguriță ulei de măsline",
      "1 felie pepene galben (opțional)",
    ],
    steps: [
      "Clătește și taie mărunt tofu-ul.",
      "Bate ouăle și amestecă cu tofu-ul.",
      "Încălzește uleiul în tigaie la foc mediu.",
      "Toarnă amestecul de ou cu tofu.",
      "Gătește amestecând des, 5 minute, până e pufos.",
      "Răcește la temperatura camerei.",
      "Servește cu felii de pepene galben pe lângă.",
    ],
    allergens: ["Ou", "Soia"],
    relatedFoods: ["ou", "tofu", "ulei-masline"],
    storage: "Tofu deschis se păstrează la frigider 3 zile.",
  },
  {
    id: "somon-orez-bol",
    name: "Bol de somon cu orez",
    emoji: "🐟",
    mealType: "mic-dejun",
    time: "30 min",
    age: "8+ luni",
    difficulty: "Mediu",
    servings: "2-3",
    ingredients: [
      "½ cană orez basmati",
      "1 cană apă sau supă de legume fără sare",
      "30g somon fără sare (din conservă sau proaspăt)",
      "1 nap mic (opțional)",
      "½ linguriță semințe de susan (opțional)",
    ],
    steps: [
      "Clătește orezul. Pune-l cu apa la fiert.",
      "Când fierbe, scade focul, acoperă. Gătește 15 minute.",
      "Lasă acoperit 10 minute. Aerisește cu furculița.",
      "Clătește somonul din conservă. Sfărâmă-l bine. VERIFICĂ TOATE OASELE!",
      "Curăță napul, taie în cuburi, fierbe la abur 10 minute. Pasează.",
      "Pune piureul de nap în castron, adaugă orez deasupra.",
      "Presară somonul sfărâmat și semințele de susan.",
    ],
    allergens: ["Pește", "Susan"],
    relatedFoods: ["somon", "orez"],
    storage: "Orezul se păstrează la frigider 2 zile.",
  },
  {
    id: "hummus-castravete",
    name: "Hummus cu castravete și pâine moale",
    emoji: "🫘",
    mealType: "mic-dejun",
    time: "20 min",
    age: "8+ luni",
    difficulty: "Mediu",
    servings: "2-4",
    ingredients: [
      "1½ cană năut fiert (din conservă, clătit bine)",
      "1 cățel de usturoi",
      "2 linguri suc de lămâie",
      "2 linguri ulei de măsline",
      "2 linguri apă",
      "2 linguri tahini de susan",
      "1 felie pâine moale",
      "1 castravete mic",
      "½ linguriță semințe de susan (opțional)",
    ],
    steps: [
      "Clătește năutul bine. Curăță usturoiul.",
      "Pune totul în blender: năut, usturoi, suc de lămâie, ulei, apă, tahini.",
      "Mixează până e cremos. Adaugă apă dacă e prea dens.",
      "Curăță castravetele și taie-l în bețișoare.",
      "Taie pâinea moale în bețișoare.",
      "Pune hummus în castronul bebelușului.",
      "Presară semințe de susan. Servește cu bețișoare pentru a învăța să înmoaie.",
    ],
    allergens: ["Susan", "Gluten"],
    relatedFoods: ["naut", "castravete", "usturoi", "paine", "ulei-masline"],
    storage: "Hummus se păstrează la frigider 1 săptămână.",
  },
];

const PRANZ_LUNCH_RECIPES: RecipeCatalogItem[] = [
  {
    id: "salata-ou-avocado-pranz",
    name: "Salată de ou cu avocado și roșie",
    emoji: "🥚",
    mealType: "pranz",
    time: "15 min",
    age: "6+ luni",
    difficulty: "Ușor",
    servings: 1,
    ingredients: [
      "3 ouă",
      "1 avocado copt",
      "1 vârf pudră de ceapă (opțional)",
      "1 vârf semințe de susan",
      "1 roșie (opțional)",
    ],
    steps: [
      "Fierbe ouăle tare 10 minute. Pune-le în apă cu gheață.",
      "Curăță ouăle și pune-le într-un castron.",
      "Curăță avocado, pasează o jumătate și amestecă cu ouăle și pudra de ceapă.",
      "Taie cealaltă jumătate în bețișoare.",
      "Taie roșia în bucăți potrivite vârstei.",
      "Presară semințe de susan deasupra.",
    ],
    allergens: ["Ou", "Susan"],
    relatedFoods: ["ou", "avocado", "rosii"],
    storage: "Se păstrează la frigider 5 zile.",
  },
  {
    id: "fasole-rosie-rosii",
    name: "Fasole roșie cu roșii și iaurt",
    emoji: "🫘",
    mealType: "pranz",
    time: "10 min",
    age: "6+ luni",
    difficulty: "Ușor",
    servings: 1,
    ingredients: [
      "½ cană fasole roșie fiartă (clătită bine)",
      "½ roșie coaptă",
      "1 linguriță ulei de măsline",
      "1 vârf usturoi pudră",
      "½ cană iaurt natural",
      "1 vârf semințe de susan",
      "1 felie pâine moale (opțional)",
    ],
    steps: [
      "Clătește fasolea pentru a elimina sodiul.",
      "Pasează ușor fasolea cu furculița (pentru bebeluși sub 12 luni).",
      "Taie roșia în cuburi mici. Amestecă cu fasolea.",
      "Adaugă uleiul și pudra de usturoi. Lasă 5 minute.",
      "Pune iaurtul în castron, adaugă fasolea deasupra.",
      "Presară susan. Servește cu pâine moale pe lângă.",
    ],
    allergens: ["Lactoză", "Susan", "Gluten"],
    relatedFoods: ["rosii", "iaurt", "usturoi", "paine"],
    storage: "Se păstrează la frigider 3 zile.",
  },
  {
    id: "dip-sfecla-nuci",
    name: "Dip de sfeclă cu nuci și castravete",
    emoji: "🟣",
    mealType: "pranz",
    time: "10 min",
    age: "8+ luni",
    difficulty: "Ușor",
    servings: "1-2",
    ingredients: [
      "½ cană sfeclă fiartă (din conservă e ok)",
      "¼ cană iaurt natural",
      "1 lingură ulei de măsline",
      "1 lingură nuci măcinate",
      "1 lingură suc de lămâie",
      "1 vârf chimion și coriandru",
      "1 castravete mic",
    ],
    steps: [
      "Pune sfecla în blender sau robot de bucătărie.",
      "Adaugă iaurtul, uleiul, nucile măcinate, sucul de lămâie și condimentele.",
      "Mixează până e cremos și roz.",
      "Curăță castravetele și taie-l în bețișoare.",
      "Pune dip-ul în castronul bebelușului.",
      "Servește cu bețișoarele de castravete pe lângă.",
    ],
    allergens: ["Lactoză", "Nuci"],
    relatedFoods: ["sfecla", "nuci-macinate", "castravete", "iaurt"],
    storage: "Se păstrează la frigider 5 zile.",
  },
  {
    id: "dip-fasole-alba-verde",
    name: "Dip de fasole albă cu fasole verde la abur",
    emoji: "🫘",
    mealType: "pranz",
    time: "15 min",
    age: "6+ luni",
    difficulty: "Ușor",
    servings: "1-2",
    ingredients: [
      "½ cană fasole albă fiartă (clătită)",
      "2 linguri iaurt natural",
      "1 lingură ulei de măsline",
      "1 lingură suc de lămâie",
      "1 vârf usturoi pudră",
      "6 fasole verde proaspete sau congelate",
      "1 portocală (opțional)",
    ],
    steps: [
      "Clătește fasolea albă bine.",
      "Pasează cu iaurtul, uleiul, sucul de lămâie și usturoiul până e cremos.",
      "Spală fasolea verde și fierbe la abur 10 minute.",
      "Răcește fasolea verde la temperatura camerei.",
      "Pune dip-ul în castron cu fasolea verde pe lângă.",
      "Taie portocala în felii potrivite vârstei.",
    ],
    allergens: ["Lactoză"],
    relatedFoods: ["fasole-verde", "iaurt", "ulei-masline"],
    storage: "Se păstrează la frigider 4 zile.",
  },
  {
    id: "scramble-ciuperci-avocado",
    name: "Omletă de ciuperci cu avocado",
    emoji: "🍄",
    mealType: "pranz",
    time: "15 min",
    age: "10+ luni",
    difficulty: "Ușor",
    servings: "1-2",
    ingredients: [
      "2 ciuperci champignon",
      "2 ouă",
      "2 lingurițe unt nesărat",
      "½ avocado",
      "1 linguriță semințe de cânepă",
      "1 felie pepene galben (opțional)",
    ],
    steps: [
      "Spală și taie mărunt ciupercile.",
      "Bate ouăle într-un castron.",
      "Topește untul într-o tigaie la foc mediu.",
      "Adaugă ciupercile, gătește 5 minute până se înmoaie.",
      "Scade focul, toarnă ouăle și amestecă des până sunt pufoase.",
      "Taie avocado în felii și rostogolește prin semințe de cânepă.",
      "Servește cu pepene galben pe lângă.",
    ],
    allergens: ["Lactoză", "Ou"],
    relatedFoods: ["ciuperci", "ou", "avocado"],
    storage: "Avocado tăiat se păstrează 3 zile la frigider.",
  },
  {
    id: "hummus-brocoli-paine-moale",
    name: "Hummus cu broccoli la abur și pâine moale",
    emoji: "🥦",
    mealType: "pranz",
    time: "15 min",
    age: "8+ luni",
    difficulty: "Ușor",
    servings: "1-2",
    ingredients: [
      "¼ cană hummus de casă sau cumpărat",
      "½ cană broccoli buchețele",
      "½ lingurița ulei de măsline",
      "½ lingurița suc de lămâie",
      "1 felie pâine moale",
      "1 vârf semințe de susan",
    ],
    steps: [
      "Fierbe broccoli la abur 10 minute până e moale.",
      "Stropește cu ulei și suc de lămâie.",
      "Taie pâinea moale în bețișoare.",
      "Pune hummus în castronul bebelușului.",
      "Presară semințe de susan deasupra.",
      "Servește cu broccoli și pâine moale pentru a învăța să înmoaie.",
    ],
    allergens: ["Susan", "Gluten"],
    relatedFoods: ["naut", "broccoli", "paine"],
    storage: "Hummus se păstrează la frigider 1 săptămână.",
  },
  {
    id: "taitei-unt-arahide-broccoli",
    name: "Tăiței cu unt de arahide și broccoli",
    emoji: "🍜",
    mealType: "pranz",
    time: "15 min",
    age: "8+ luni",
    difficulty: "Ușor",
    servings: "1-2",
    ingredients: [
      "½ cană broccoli buchețele",
      "1 lingură unt de arahide fin",
      "1 lingură apă",
      "½ lingurița oțet de mere",
      "60g tăiței de orez",
      "1 vârf semințe de susan",
    ],
    steps: [
      "Fierbe broccoli la abur până e moale, ~10 minute.",
      "Fierbe tăițeii conform instrucțiunilor de pe pachet. Scurge.",
      "Amestecă untul de arahide cu apa și oțetul până e cremos.",
      "Pune tăițeii în sosul de arahide. Amestecă bine.",
      "Poți tăia tăițeii mai scurți cu foarfecele pentru bebeluși.",
      "Servește cu broccoli și presară susan deasupra.",
    ],
    allergens: ["Arahide", "Susan"],
    relatedFoods: ["unt-arahide", "broccoli", "orez"],
    storage: "Se păstrează la frigider 3 zile.",
  },
  {
    id: "polenta-rosii-ricotta",
    name: "Mămăligă cu roșii și ricotta",
    emoji: "🌽",
    mealType: "pranz",
    time: "10 min",
    age: "6+ luni",
    difficulty: "Ușor",
    servings: "1-2",
    ingredients: [
      "¼ cană mălai instant",
      "½ cană apă sau supă de legume",
      "¼ cană ricotta",
      "½ roșie coaptă",
      "1 linguriță ulei de măsline",
      "6 fasole verde (opțional)",
    ],
    steps: [
      "Fierbe apa, scade focul și adaugă mălaiul amestecând continuu.",
      "Gătește 5 minute, apoi acoperă 5 minute.",
      "Amestecă ricotta în polenta caldă.",
      "Taie roșia în bucăți potrivite vârstei.",
      "Pune polenta în castron, adaugă roșia deasupra.",
      "Stropește cu ulei de măsline.",
    ],
    allergens: ["Lactoză"],
    relatedFoods: ["porumb", "rosii", "branza-vaci"],
    storage: "Se păstrează la frigider 3 zile.",
  },
  {
    id: "quesadilla-dovleac",
    name: "Quesadilla cu dovleac și mozzarella",
    emoji: "🎃",
    mealType: "pranz",
    time: "15 min",
    age: "12+ luni",
    difficulty: "Ușor",
    servings: "1-2",
    ingredients: [
      "1 tortilla de porumb sau grâu",
      "1 lingură unt nesărat",
      "50g mozzarella rasă",
      "1 lingură piure de dovleac",
      "½ avocado (opțional)",
      "1 linguriță semințe de cânepă",
    ],
    steps: [
      "Topește untul într-o tigaie la foc mediu.",
      "Pune tortilla și prăjește 2 minute până e aurie dedesubt.",
      "Întoarce tortilla.",
      "Presară brânza pe o jumătate, întinde piureul de dovleac deasupra.",
      "Îndoaie tortilla. Apasă ușor.",
      "Acoperă tigaia, gătește 2 minute.",
      "Taie în triunghiuri. Răcește bine.",
      "Servește cu avocado în felii pe lângă.",
    ],
    allergens: ["Lactoză", "Gluten"],
    relatedFoods: ["dovleac", "branza-vaci", "avocado"],
    storage: "Se păstrează la frigider 3 zile.",
  },
  {
    id: "frittata-spanac-cartof-dulce",
    name: "Frittata de spanac cu cartof dulce",
    emoji: "🥬",
    mealType: "pranz",
    time: "30 min",
    age: "6+ luni",
    difficulty: "Mediu",
    servings: "1-2",
    ingredients: [
      "3 ouă",
      "¼ cană spanac proaspăt sau congelat",
      "¼ cană cartof dulce cuburi",
      "2 lingurițe ulei de măsline",
      "1 roșie (opțional)",
      "½ banană (opțional)",
    ],
    steps: [
      "Bate ouăle.",
      "Spală și taie mărunt spanacul.",
      "Încălzește uleiul, adaugă cartoful dulce. Gătește 5 minute.",
      "Adaugă spanacul, gătește până se ofilește, ~5 minute.",
      "Toarnă ouăle, acoperă, foc mic, 5-10 minute.",
      "Taie frittata în bețișoare.",
      "Servește cu roșie și banană pe lângă.",
    ],
    allergens: ["Ou"],
    relatedFoods: ["spanac", "cartof-dulce", "ou"],
    storage: "Se păstrează la frigider 4 zile.",
  },
  {
    id: "penne-dovleac-broccoli",
    name: "Penne cu cremă de dovleac și broccoli",
    emoji: "🍝",
    mealType: "pranz",
    time: "15 min",
    age: "8+ luni",
    difficulty: "Ușor",
    servings: 1,
    ingredients: [
      "1 lingură ricotta",
      "1 lingură piure de dovleac",
      "1 linguriță suc de lămâie",
      "1 vârf usturoi pudră și nucșoară",
      "50g penne din năut sau linte",
      "½ cană broccoli buchețele",
      "2 căpșuni mari (opțional)",
    ],
    steps: [
      "Amestecă ricotta cu piureul de dovleac, sucul de lămâie și condimentele.",
      "Fierbe penne-le conform instrucțiunilor. Scurge.",
      "Amestecă pastele cu sosul cremos.",
      "Fierbe broccoli la abur 10 minute.",
      "Servește pastele cu broccoli pe lângă.",
      "Adaugă căpșuni tăiate potrivit vârstei.",
    ],
    allergens: ["Lactoză"],
    relatedFoods: ["dovleac", "broccoli", "branza-vaci", "paste"],
    storage: "Se păstrează la frigider 3 zile.",
  },
  {
    id: "cartof-dulce-fasole-avocado",
    name: "Cartof dulce cu fasole neagră și avocado",
    emoji: "🍠",
    mealType: "pranz",
    time: "30 min",
    age: "6+ luni",
    difficulty: "Mediu",
    servings: 1,
    ingredients: [
      "1 cartof dulce mediu",
      "¼ cană fasole neagră fiartă",
      "1 linguriță ulei de măsline",
      "½ avocado",
      "¼ cană afine (opțional)",
    ],
    steps: [
      "Curăță cartoful dulce, taie în bețișoare.",
      "Fierbe 15-20 minute până e moale. Scurge.",
      "Clătește fasolea. Pasează ușor cu furculița (pentru sub 12 luni).",
      "Stropește fasolea cu ulei.",
      "Taie avocado în felii.",
      "Servește totul împreună cu afine pe lângă.",
    ],
    allergens: [],
    relatedFoods: ["cartof-dulce", "avocado", "afine"],
    storage: "Cartoful dulce gătit se păstrează 3 zile la frigider.",
  },
  {
    id: "chiftele-pui-mar",
    name: "Chifteluțe de pui cu măr",
    emoji: "🍗",
    mealType: "pranz",
    time: "45 min",
    age: "6+ luni",
    difficulty: "Mediu",
    servings: "8-10",
    ingredients: [
      "500g piept de pui tocat",
      "1 lingură ulei",
      "½ cană făină de nuci",
      "1 ou",
      "1 ceapă mică",
      "1 măr",
      "½ linguriță cimbru uscat",
      "1 cartof mic (opțional)",
      "½ cană broccoli (opțional)",
    ],
    steps: [
      "Preîncălzește cuptorul la 200°C. Unge tava cu ulei.",
      "Curăță ceapa și mărul. Rade mărul pe răzătoare.",
      "Amestecă puiul, făina, oul, ceapa tocată, mărul ras și cimbrul.",
      "Formează chiftelute mici.",
      "Coace 10 minute, întoarce, mai coace 5 minute.",
      "Verifică să nu mai fie roz înăuntru.",
      "Păstrează 1-2 pentru masă, congelează restul.",
      "Servește cu cartof fiert și broccoli la abur.",
    ],
    allergens: ["Ou", "Nuci"],
    relatedFoods: ["pui", "mere", "ou"],
    storage: "Se păstrează la frigider 3 zile sau congelator 2 luni.",
  },
  {
    id: "chili-vita-fasole",
    name: "Chili de vită cu fasole roșie",
    emoji: "🥩",
    mealType: "pranz",
    time: "45 min",
    age: "8+ luni",
    difficulty: "Mediu",
    servings: "4-8",
    ingredients: [
      "500g vită tocată",
      "1 ardei gras mare",
      "1 ceapă mare",
      "4 căței de usturoi",
      "4 linguri ulei de măsline",
      "1 vârf boia dulce, chimion, coriandru, ardei (opțional)",
      "1½ cană roșii pasate",
      "1 cană apă sau supă de legume",
      "1½ cană fasole roșie fiartă",
      "½ cană iaurt natural",
      "½ cană broccoli (opțional)",
    ],
    steps: [
      "Taie ardeiul, ceapa și usturoiul mărunt.",
      "Încălzește uleiul, călește ceapa și ardeiul 5 minute.",
      "Adaugă condimentele, gătește 30 secunde.",
      "Adaugă vita tocată, sfărâmă cu lingura. Gătește 10 minute.",
      "Adaugă roșiile pasate și apa. Fierbe.",
      "Gătește la foc mediu 15 minute fără capac.",
      "Clătește fasolea și adaugă-o. Oprește focul.",
      "Pune chili în castronul bebelușului. Pasează fasolea pentru sub 12 luni.",
      "Adaugă iaurt pe lângă.",
    ],
    allergens: ["Lactoză"],
    relatedFoods: ["vita", "ardei-gras", "rosii", "usturoi", "iaurt"],
    storage: "Se păstrează la frigider 3 zile sau congelator 6 luni.",
  },
  {
    id: "chiftele-miel-dip-ardei",
    name: "Chifteluțe de miel cu dip de ardei și iaurt",
    emoji: "🍖",
    mealType: "pranz",
    time: "30 min",
    age: "10+ luni",
    difficulty: "Mediu",
    servings: "4-6",
    ingredients: [
      "500g miel tocat",
      "1 cățel de usturoi",
      "1 ou",
      "½ cană pesmet sau făină de nuci",
      "½ linguriță chimion, coriandru, turmeric (opțional)",
      "1 ardei gras copt (din borcan e ok)",
      "¼ cană iaurt natural",
      "½ cană conopidă (opțional)",
    ],
    steps: [
      "Preîncălzește cuptorul la 220°C.",
      "Amestecă mielul, usturoiul tocat, oul, pesmetul și condimentele.",
      "Formează chiftelute. Pune pe tavă.",
      "Coace 8 minute, întoarce, mai coace 5-10 minute.",
      "Verifică să nu fie roz înăuntru.",
      "Taie ardeiul copt mărunt, amestecă cu iaurtul.",
      "Pune dip-ul în castron cu chifteluțele pe lângă.",
      "Servește cu conopidă la abur.",
    ],
    allergens: ["Lactoză", "Ou", "Gluten"],
    relatedFoods: ["miel", "ardei-gras", "iaurt", "conopida"],
    storage: "Se păstrează la frigider 4 zile sau congelator 2 luni.",
  },
  {
    id: "burgeri-fasole-quinoa",
    name: "Burgeri de fasole neagră cu quinoa",
    emoji: "🫘",
    mealType: "pranz",
    time: "1 oră",
    age: "8+ luni",
    difficulty: "Mediu",
    servings: "8-10",
    ingredients: [
      "⅓ cană quinoa uscată",
      "1 cană apă",
      "1½ cană fasole neagră fiartă",
      "1 ou",
      "½ cană făină de nuci",
      "½ linguriță chimion, coriandru, boia (opțional)",
      "2 linguri ulei de măsline",
      "½ cană iaurt natural (opțional)",
      "½ avocado (opțional)",
    ],
    steps: [
      "Fierbe quinoa cu apa 20 minute. Lasă 5 minute acoperită.",
      "Clătește fasolea, pune într-un castron. Pasează ușor.",
      "Adaugă quinoa, oul, făina și condimentele. Amestecă.",
      "Formează burgeri mici. Unge cu ulei.",
      "Coace la 220°C, 10 minute pe fiecare parte.",
      "Păstrează 1-2 pentru masă, congelează restul.",
      "Servește cu avocado și iaurt.",
    ],
    allergens: ["Lactoză", "Ou", "Nuci"],
    relatedFoods: ["quinoa", "ou", "avocado", "iaurt"],
    storage: "Se păstrează la frigider 3 zile sau congelator 2 luni.",
  },
  {
    id: "tocana-legume-curcubeu",
    name: "Tocăniță curcubeu de legume cu fasole",
    emoji: "🌈",
    mealType: "pranz",
    time: "1½ ore",
    age: "6+ luni",
    difficulty: "Mediu",
    servings: "4-8",
    ingredients: [
      "1 ceapă mare",
      "4 căței usturoi",
      "4 ardei grași (diverse culori)",
      "1 dovlecel",
      "1 cană dovleac plăcintar cuburi",
      "2 căni fasole verde",
      "4 linguri ulei de măsline",
      "1½ cană roșii pasate",
      "1 cană apă sau supă de legume",
      "¼ cană fasole roșie fiartă",
      "¼ cană iaurt natural (opțional)",
    ],
    steps: [
      "Taie toate legumele în bucăți potrivite vârstei bebelușului.",
      "Încălzește uleiul, călește ceapa, usturoiul și ardeii 5 minute.",
      "Adaugă dovleacul și fasolea verde, gătește 10 minute.",
      "Toarnă roșiile și apa. Acoperă.",
      "Gătește la foc mic 30 minute amestecând din când în când.",
      "Deschide capacul, gătește încă 30 minute până scade lichidul.",
      "Adaugă fasolea roșie (pasată pentru sub 12 luni).",
      "Servește cu iaurt pe lângă.",
    ],
    allergens: ["Lactoză"],
    relatedFoods: [
      "ardei-gras",
      "dovlecel",
      "dovleac-butternut",
      "fasole-verde",
      "rosii",
      "iaurt",
    ],
    storage: "Se păstrează la frigider 3 zile sau congelator 2 luni.",
  },
  {
    id: "crocante-somon-dip-avocado",
    name: "Crocante de somon cu dip de avocado",
    emoji: "🐟",
    mealType: "pranz",
    time: "45 min",
    age: "8+ luni",
    difficulty: "Mediu",
    servings: "8-10",
    ingredients: [
      "200g somon fără sare (conservă sau proaspăt)",
      "1 cartof mediu",
      "2 cepe verzi",
      "2 ouă",
      "1 lingură suc de lămâie",
      "½ lingurița usturoi pudră și boia",
      "1 cană pesmet sau mălai",
      "½ avocado",
      "¼ cană iaurt natural",
      "½ mango (opțional)",
    ],
    steps: [
      "Clătește somonul. VERIFICĂ TOATE OASELE!",
      "Fierbe cartoful, scurge, pasează.",
      "Taie ceapa verde mărunt.",
      "Amestecă somonul, cartoful, ceapa, ouăle, sucul de lămâie și condimentele.",
      "Formează crochete mici. Rostogolește prin pesmet.",
      "Coace la 200°C, 10 minute pe fiecare parte.",
      "Pasează avocado cu iaurtul pentru dip.",
      "Servește cu dip și mango pe lângă.",
    ],
    allergens: ["Pește", "Ou", "Lactoză", "Gluten"],
    relatedFoods: ["somon", "ou", "avocado", "iaurt", "mango"],
    storage: "Se păstrează la congelator 2 luni.",
  },
  {
    id: "chiftele-curcan-merisoare",
    name: "Chifteluțe de curcan cu sos de merișoare",
    emoji: "🦃",
    mealType: "pranz",
    time: "30 min",
    age: "6+ luni",
    difficulty: "Mediu",
    servings: "4-6",
    ingredients: [
      "500g curcan tocat",
      "1 ceapă mică",
      "1 ou",
      "½ cană făină de grâu sau nuci",
      "½ lingurița boia dulce",
      "1 cană merișoare proaspete sau congelate",
      "1 portocală",
      "1 baton de scorțișoară (opțional)",
      "½ cană ricotta (opțional)",
    ],
    steps: [
      "Preîncălzește cuptorul la 220°C.",
      "Amestecă curcanul, ceapa tocată, oul, făina și boia.",
      "Formează chiftelute. Coace 8 min, întoarce, mai coace 5-10 min.",
      "Verifică să nu fie roz.",
      "Pentru sos: fierbe merișoarele cu sucul de portocală și scorțișoara.",
      "Gătește 10 minute până se sparg bobițele. Pasează.",
      "Pune ricotta în castron, adaugă sos deasupra.",
      "Servește chifteluțele pe lângă.",
    ],
    allergens: ["Ou", "Lactoză", "Gluten"],
    relatedFoods: ["curcan", "ou", "branza-vaci"],
    storage:
      "Chifteluțele: frigider 4 zile, congelator 2 luni. Sosul: frigider 2 săptămâni.",
  },
  {
    id: "pulpe-pui-tava-legume",
    name: "Pulpe de pui la tavă cu legume",
    emoji: "🍗",
    mealType: "pranz",
    time: "1½ ore",
    age: "8+ luni",
    difficulty: "Mediu",
    servings: 8,
    ingredients: [
      "1kg pulpe de pui",
      "2 ardei grași mari",
      "2 cartofi dulci medii",
      "2 dovlecei mici",
      "4 linguri ulei de floarea-soarelui",
      "½ lingurița piper negru (opțional)",
      "1 lingurița suc de lămâie",
      "½ cană iaurt natural",
    ],
    steps: [
      "Preîncălzește cuptorul la 175°C.",
      "Taie ardeii, cartofii dulci și dovleceii în bețișoare.",
      "Unge pulpele și ardeii cu 2 linguri ulei. Presară piper.",
      "Coace 30 minute.",
      "Întoarce pulpele. Adaugă legumele pe tavă cu restul de ulei.",
      "Coace încă 30 minute până pulpele sunt aurii.",
      "Verifică să nu fie roz (75°C intern).",
      "IMPORTANT: Scoate pielea și dezosează complet! Sfărâmă carnea fin pentru 8-12 luni, taie bucăți mici pentru 12+ luni.",
      "Stropește cu suc de lămâie. Servește cu iaurt. Nu servi pulpa întreagă bebelușului — doar carnea dezosată și sfărâmată.",
    ],
    allergens: ["Lactoză"],
    relatedFoods: ["pui", "ardei-gras", "cartof-dulce", "dovlecel", "iaurt"],
    storage:
      "Pulpele: frigider 4 zile. Legumele: frigider 3 zile. Ambele: congelator 2 luni.",
  },
  {
    id: "paste-bolognese",
    name: "Paste cu sos bolognese de casă",
    emoji: "🍝",
    mealType: "pranz",
    time: "1 oră",
    age: "8+ luni",
    difficulty: "Mediu",
    servings: "12-24",
    ingredients: [
      "500g porc tocat",
      "250g vită tocată",
      "½ cană ulei de măsline",
      "1 ceapă mare",
      "4 căței usturoi",
      "2 linguri pastă de tomate",
      "2 conserve roșii pasate (800g total)",
      "2 foi de dafin",
      "100g penne din năut sau linte per porție",
    ],
    steps: [
      "Taie ceapa și usturoiul mărunt.",
      "Încălzește jumătate din ulei, călește ceapa 5 minute.",
      "Adaugă carnea, sfărâmă bine. Gătește 15 minute.",
      "Adaugă usturoiul și pasta de tomate. Gătește 2 minute.",
      "Adaugă roșiile, foile de dafin și restul de ulei.",
      "Fierbe, apoi scade focul. Gătește la foc mic 2-3 ore.",
      "Fierbe pastele separat. Servește cu sos deasupra.",
      "Sosul se congelează în borcane mici (lasă loc de expansiune!).",
    ],
    allergens: [],
    relatedFoods: ["vita", "rosii", "usturoi", "paste"],
    storage: "Sosul: congelator 6 luni în borcane de sticlă.",
  },
  {
    id: "biscuiti-polenta-rosii",
    name: "Bețișoare de polenta coapte cu roșii",
    emoji: "🌽",
    mealType: "pranz",
    time: "45 min",
    age: "8+ luni",
    difficulty: "Mediu",
    servings: "8-10",
    ingredients: [
      "2 căni lapte",
      "1 cană mălai instant",
      "1 linguriță coajă de lămâie rasă (opțional)",
      "½ lingurița cimbru uscat și piper (opțional)",
      "1 lingură ulei",
      "1 roșie",
      "1 cană spanac proaspăt sau congelat (opțional)",
    ],
    steps: [
      "Fierbe laptele, scade focul, toarnă mălaiul amestecând.",
      "Adaugă coaja de lămâie și condimentele.",
      "Gătește 5 minute. Acoperă 5 minute.",
      "Tapetează o tavă mică cu hârtie de copt unsă.",
      "Toarnă polenta, nivelează. Pune la frigider 30 minute.",
      "Taie în bețișoare. Coace la 220°C, 15 min pe o parte, 5 min pe cealaltă.",
      "Taie roșia mărunt pentru sos/relish.",
      "Servește bețișoarele cu sosul de roșii și spanac gătit.",
    ],
    allergens: ["Lactoză"],
    relatedFoods: ["porumb", "rosii", "spanac"],
    storage: "Se păstrează la frigider 2 zile sau congelator 2 luni.",
  },
  {
    id: "supa-linte-rosie-morcov",
    name: "Supă cremă de linte roșie cu morcov",
    emoji: "🥣",
    mealType: "pranz",
    time: "25 min",
    age: "6+ luni",
    difficulty: "Ușor",
    servings: "4-6",
    ingredients: [
      "1 cană linte roșie",
      "2 morcovi medii",
      "1 cartof mic",
      "1 ceapă mică",
      "1 cățel usturoi",
      "1 lingură ulei de măsline",
      "3 căni apă",
      "1 vârf turmeric și chimion (opțional)",
      "1 linguriță suc de lămâie",
    ],
    steps: [
      "Clătește lintea bine sub jet de apă.",
      "Curăță și taie morcovii, cartoful și ceapa.",
      "Încălzește uleiul, călește ceapa și usturoiul 3 minute.",
      "Adaugă legumele, lintea, apa și condimentele.",
      "Fierbe, apoi scade focul. Gătește 20 minute acoperit.",
      "Pasează totul cu blenderul vertical.",
      "Adaugă sucul de lămâie. Servește călduță.",
    ],
    allergens: [],
    relatedFoods: ["linte", "morcov", "cartof", "usturoi", "turmeric"],
    storage: "Se păstrează la frigider 5 zile sau congelator 3 luni.",
  },
  {
    id: "risotto-dovlecel-parmezan",
    name: "Risotto de dovlecel",
    emoji: "🍚",
    mealType: "pranz",
    time: "30 min",
    age: "8+ luni",
    difficulty: "Mediu",
    servings: "2-3",
    ingredients: [
      "½ cană orez arborio sau rotund",
      "1 dovlecel mic",
      "1 ceapă mică",
      "1 cățel usturoi",
      "1 lingură unt nesărat",
      "2 căni apă caldă sau supă de legume",
      "1 linguriță ulei de măsline",
    ],
    steps: [
      "Curăță și rade dovlecelul pe răzătoare.",
      "Taie ceapa și usturoiul mărunt.",
      "Topește untul, călește ceapa 3 minute.",
      "Adaugă orezul, amestecă 1 minut.",
      "Adaugă apa treptat, câte un polonic, amestecând des.",
      "După 15 minute adaugă dovlecelul ras.",
      "Gătește încă 5 minute până orezul e cremos.",
      "Servește călduț.",
    ],
    allergens: ["Lactoză"],
    relatedFoods: ["orez", "dovlecel", "usturoi"],
    storage: "Se păstrează la frigider 2 zile.",
  },
  {
    id: "piure-mazare-menta-paine-moale",
    name: "Piure de mazăre cu mentă pe pâine moale",
    emoji: "🫛",
    mealType: "pranz",
    time: "10 min",
    age: "8+ luni",
    difficulty: "Ușor",
    servings: 1,
    ingredients: [
      "½ cană mazăre congelată",
      "2-3 frunze mentă proaspătă (opțional)",
      "1 linguriță ulei de măsline",
      "1 linguriță suc de lămâie",
      "1 felie pâine moale",
      "½ avocado (opțional)",
    ],
    steps: [
      "Fierbe mazărea 5 minute. Scurge.",
      "Pasează cu furculița sau blenderul (nu trebuie să fie perfect fin).",
      "Adaugă menta tocată fin, uleiul și sucul de lămâie.",
      "Taie pâinea moale în bețișoare.",
      "Întinde piureul de mazăre pe pâine moale.",
      "Servește cu avocado feliat pe lângă.",
    ],
    allergens: ["Gluten"],
    relatedFoods: ["mazare", "busuioc", "paine", "avocado"],
    storage: "Se păstrează la frigider 3 zile.",
  },
  {
    id: "gratin-conopida-branza",
    name: "Gratin de conopidă cu brânză",
    emoji: "🥦",
    mealType: "pranz",
    time: "35 min",
    age: "8+ luni",
    difficulty: "Mediu",
    servings: "2-4",
    ingredients: [
      "1 conopidă mică (buchețele)",
      "1 lingură unt nesărat",
      "1 lingură făină",
      "½ cană lapte",
      "50g brânză de vaci sau cașcaval ras",
      "1 vârf nucșoară (opțional)",
    ],
    steps: [
      "Fierbe conopida la abur 10 minute până e moale.",
      "Topește untul într-o crăticioară mică la foc mic.",
      "Adaugă făina, amestecă 1 minut.",
      "Toarnă laptele treptat, amestecând continuu.",
      "Gătește până se îngroașă, ~3 minute.",
      "Adaugă brânza și nucșoara, amestecă.",
      "Pune conopida într-un vas de cuptor, toarnă sosul.",
      "Gratinează la 200°C, 10 minute.",
    ],
    allergens: ["Lactoză", "Gluten"],
    relatedFoods: ["conopida", "branza-vaci"],
    storage: "Se păstrează la frigider 3 zile.",
  },
  {
    id: "wrap-pui-iaurt-castravete",
    name: "Mini wrap cu pui, iaurt și castravete",
    emoji: "🌯",
    mealType: "pranz",
    time: "20 min",
    age: "12+ luni",
    difficulty: "Ușor",
    servings: "2-3",
    ingredients: [
      "1 piept de pui mic fiert și sfărâmat",
      "¼ cană iaurt natural",
      "1 linguriță suc de lămâie",
      "½ castravete mic",
      "2 tortilla mici",
      "1 vârf boia dulce (opțional)",
    ],
    steps: [
      "Fierbe pieptul de pui 25 minute. Sfărâmă cu 2 furculițe.",
      "Amestecă puiul cu iaurtul, sucul de lămâie și boia.",
      "Rade castravetele pe răzătoare. Stoarce excesul de apă.",
      "Întinde amestecul de pui pe tortilla.",
      "Adaugă castravetele ras deasupra.",
      "Rulează strâns și taie în rondele de 2-3 cm.",
      "Servește la temperatura camerei.",
    ],
    allergens: ["Lactoză", "Gluten"],
    relatedFoods: ["pui", "iaurt", "castravete"],
    storage: "Se păstrează la frigider 2 zile.",
  },
  {
    id: "supa-crema-dovleac-ghimbir",
    name: "Supă cremă de dovleac cu ghimbir",
    emoji: "🎃",
    mealType: "pranz",
    time: "35 min",
    age: "8+ luni",
    difficulty: "Mediu",
    servings: "4-6",
    ingredients: [
      "400g dovleac curățat cuburi",
      "1 morcov",
      "1 cartof mic",
      "1 ceapă",
      "1 vârf de ghimbir proaspăt ras",
      "1 lingură ulei de măsline",
      "3 căni apă",
      "2 linguri lapte de cocos (opțional)",
    ],
    steps: [
      "Curăță și taie toate legumele în cuburi.",
      "Încălzește uleiul, călește ceapa 3 minute.",
      "Adaugă legumele și ghimbirul, amestecă.",
      "Toarnă apa, fierbe, apoi foc mic 25 minute.",
      "Pasează totul cu blenderul vertical.",
      "Adaugă laptele de cocos pentru cremozitate.",
      "Servește călduță cu o picătură de ulei deasupra.",
    ],
    allergens: ["Nucă de cocos"],
    relatedFoods: ["dovleac", "morcov", "ghimbir", "unt-cocos"],
    storage: "Se păstrează la frigider 5 zile sau congelator 3 luni.",
  },
  {
    id: "omleta-spanac-branza-capra",
    name: "Omletă de spanac cu brânză de capră",
    emoji: "🥬",
    mealType: "pranz",
    time: "30 min",
    age: "8+ luni",
    difficulty: "Mediu",
    servings: "1-2",
    ingredients: [
      "½ cană spanac proaspăt sau congelat",
      "1 ceapă mică",
      "2 lingurițe ulei de măsline",
      "3 ouă",
      "1 lingură brânză de capră",
      "1 felie pâine moale (opțional)",
      "½ lingurița semințe de cânepă",
    ],
    steps: [
      "Spală și taie mărunt spanacul. Taie ceapa fin.",
      "Încălzește uleiul, călește ceapa 5 minute.",
      "Adaugă spanacul, gătește 5 minute.",
      "Bate ouăle, toarnă peste legume.",
      "Acoperă, foc mic, 5 minute.",
      "Sfărâmă brânza de capră deasupra.",
      "Acoperă încă 3 minute.",
      "Taie în bețișoare. Presară semințe de cânepă.",
    ],
    allergens: ["Lactoză", "Ou"],
    relatedFoods: ["spanac", "ou", "branza-vaci"],
    storage: "Se păstrează la frigider 4 zile sau congelator 2 luni.",
  },
  {
    id: "tofu-susan-broccoli-ananas",
    name: "Tofu cu susan și broccoli",
    emoji: "🧈",
    mealType: "pranz",
    time: "15 min",
    age: "8+ luni",
    difficulty: "Ușor",
    servings: "1-2",
    ingredients: [
      "60g tofu ferm",
      "½ cană broccoli buchețele",
      "2 lingurițe ulei de susan",
      "1 lingură unt de arahide fin",
      "2 linguri apă",
      "½ lingurița oțet de mere",
      "½ lingurița semințe de susan",
      "2 felii ananas (opțional)",
    ],
    steps: [
      "Clătește tofu-ul, usucă-l și taie-l în bețișoare.",
      "Fierbe broccoli la abur 10 minute.",
      "Încălzește 1 linguriță ulei de susan, prăjește tofu 3 minute pe fiecare parte.",
      "Amestecă untul de arahide, apa, oțetul și restul de ulei pentru sos.",
      "Pune tofu în sos, amestecă.",
      "Presară semințe de susan.",
      "Servește cu broccoli și felii de ananas.",
    ],
    allergens: ["Soia", "Arahide", "Susan"],
    relatedFoods: ["tofu", "broccoli", "unt-arahide", "ananas"],
    storage: "Se păstrează la frigider 4 zile.",
  },
  {
    id: "naut-curry-cocos-mango",
    name: "Năut curry cu lapte de cocos",
    emoji: "🫘",
    mealType: "pranz",
    time: "30 min",
    age: "8+ luni",
    difficulty: "Mediu",
    servings: "4-6",
    ingredients: [
      "1½ cană năut fiert",
      "1 ceapă mică",
      "2 căței usturoi",
      "1 bucățică ghimbir proaspăt",
      "1 lingură ulei de cocos",
      "1 cană roșii pasate",
      "½ cană lapte de cocos",
      "½ linguriță turmeric, chimion, coriandru, scorțișoară, cardamom",
      "½ mango (opțional)",
    ],
    steps: [
      "Taie ceapa, usturoiul și ghimbirul mărunt.",
      "Încălzește uleiul, călește ceapa 3 minute.",
      "Adaugă usturoiul, ghimbirul și condimentele. Gătește 30 secunde.",
      "Adaugă roșiile, fierbe 5 minute.",
      "Clătește năutul, adaugă-l în oală cu laptele de cocos.",
      "Gătește la foc mic 15 minute.",
      "Pasează ușor o parte (lasă și năuți întregi pentru textură).",
      "Servește cu mango feliat pe lângă.",
    ],
    allergens: ["Nucă de cocos"],
    relatedFoods: ["naut", "unt-cocos", "rosii", "ghimbir", "turmeric", "mango"],
    storage: "Se păstrează la frigider 5 zile sau congelator 2 luni.",
  },
  {
    id: "paste-linte-marinara-conopida",
    name: "Paste de linte cu sos marinara și conopidă",
    emoji: "🍝",
    mealType: "pranz",
    time: "15 min",
    age: "8+ luni",
    difficulty: "Ușor",
    servings: 1,
    ingredients: [
      "50g penne de linte",
      "2 linguri sos de roșii fără sare",
      "½ cană conopidă buchețele",
      "½ lingurița ulei de măsline",
      "½ lingurița suc de lămâie",
    ],
    steps: [
      "Fierbe pastele conform instrucțiunilor. Scurge.",
      "Amestecă pastele cu sosul de roșii.",
      "Fierbe conopida la abur 10 minute.",
      "Stropește conopida cu ulei și suc de lămâie.",
      "Servește pastele cu conopida pe lângă.",
    ],
    allergens: [],
    relatedFoods: ["linte", "rosii", "conopida", "paste"],
    storage: "Se păstrează la frigider 3 zile.",
  },
  {
    id: "pate-ficat-pui-pere",
    name: "Pate de ficat de pui cu pere fierte",
    emoji: "🍗",
    mealType: "pranz",
    time: "30 min",
    age: "6+ luni",
    difficulty: "Mediu",
    servings: "6-8",
    ingredients: [
      "250g ficat de pui",
      "1 cană apă",
      "1 ceapă mică",
      "2 linguri unt nesărat",
      "1 felie pâine moale",
      "1 pară (opțional)",
    ],
    steps: [
      "Pune ficatul într-o oală cu apa și ceapa tăiată în jumătate.",
      "Fierbe, apoi scade focul. Gătește 15-20 minute acoperit.",
      "Verifică să nu mai fie roz deloc înăuntru.",
      "Scurge, pune ficatul și ceapa în blender.",
      "Adaugă untul. Mixează până e cremos.",
      "Întinde max 1 lingură pe pâine moale pentru bebeluș.",
      "Congelează restul în forme de gheață — porții perfecte!",
      "Fierbe para tăiată felii 10 minute. Servește pe lângă.",
    ],
    allergens: ["Lactoză", "Gluten"],
    relatedFoods: ["pui", "paine", "pere"],
    storage: "Se păstrează la frigider 3 zile sau congelator 2 luni.",
  },
  {
    id: "nuggets-pui-quinoa-dip",
    name: "Nuggets de pui în crustă de quinoa cu dip de avocado",
    emoji: "🍗",
    mealType: "pranz",
    time: "30 min",
    age: "8+ luni",
    difficulty: "Mediu",
    servings: "8-10",
    ingredients: [
      "500g piept de pui",
      "1 lingură ulei",
      "2 căni quinoa fiartă",
      "2 ouă",
      "1 cană făină",
      "½ lingurița usturoi pudră, boia dulce (opțional)",
      "½ avocado",
      "¼ cană iaurt natural",
      "½ cană broccoli (opțional)",
    ],
    steps: [
      "Preîncălzește cuptorul la 220°C. Unge tava.",
      "Taie puiul în bucăți cât degetul mare.",
      "Pregătește 3 castroane: făină+condimente, ouă bătute, quinoa.",
      "Treci bucățile prin: făină → ou → quinoa. Pune pe tavă.",
      "Coace 20 minute, întoarce, mai coace 5 minute.",
      "Verifică temperatura internă (75°C).",
      "Pasează avocado cu iaurtul pentru dip.",
      "Servește 1-2 nuggets cu dip și broccoli.",
    ],
    allergens: ["Ou", "Lactoză", "Gluten"],
    relatedFoods: ["pui", "quinoa", "ou", "avocado", "broccoli"],
    storage: "Se păstrează la congelator 2 luni.",
  },
  {
    id: "quinoa-cocos-cartof-dulce",
    name: "Quinoa cu cocos și cartof dulce",
    emoji: "🥥",
    mealType: "pranz",
    time: "45 min",
    age: "6+ luni",
    difficulty: "Mediu",
    servings: "6-12",
    ingredients: [
      "1 cană quinoa uscată",
      "1 cană lapte de cocos integral",
      "1 cană apă",
      "1 baton de scorțișoară (opțional)",
      "2 cartofi dulci medii",
      "1 portocală (opțional)",
    ],
    steps: [
      "Clătește quinoa bine.",
      "Fierbe quinoa cu laptele de cocos, apa și scorțișoara.",
      "Acoperă, foc mic, 20 minute.",
      "Lasă acoperită 5 minute. Scoate scorțișoara.",
      "Curăță cartofii dulci, taie în bețișoare.",
      "Fierbe cartofii 15-20 minute. Scurge.",
      "Pune quinoa și cartof dulce în castron.",
      "Servește cu felii de portocală.",
    ],
    allergens: ["Nucă de cocos"],
    relatedFoods: ["quinoa", "unt-cocos", "cartof-dulce", "portocale", "scortisoara"],
    storage:
      "Quinoa: frigider 3 zile. Cartoful: frigider 3 zile. Ambele: congelator 2-3 luni.",
  },
  {
    id: "chiftele-peste-alb-dip-ardei",
    name: "Chifteluțe de pește alb cu dip de ardei roșu",
    emoji: "🐟",
    mealType: "pranz",
    time: "30 min",
    age: "8+ luni",
    difficulty: "Mediu",
    servings: "8-10",
    ingredients: [
      "500g cod sau merlucius proaspăt/congelat",
      "1 cană lapte",
      "2 tulpini țelină",
      "1 ceapă mică",
      "1 lingură ulei",
      "2 ouă",
      "2 linguri maioneză vegană",
      "1 lingură suc de lămâie",
      "1 cană pesmet sau mălai",
      "1 ardei gras copt",
      "¼ cană iaurt natural",
      "¼ cană fasole roșie (opțional)",
    ],
    steps: [
      "Pune peștele cu laptele, țelina și ceapa într-o tigaie. Adaugă apă.",
      "Fierbe încet 8-12 minute. VERIFICĂ OASELE!",
      "Sfărâmă peștele. Taie mărunt ceapa și țelina.",
      "Amestecă peștele, ouăle, maioneza, sucul de lămâie și ¼ cană pesmet.",
      "Formează chiftelute. Rostogolește prin restul de pesmet.",
      "Coace la 200°C, 10 minute pe fiecare parte.",
      "Taie ardeiul copt mărunt, amestecă cu iaurtul.",
      "Servește cu dip și fasole pe lângă.",
    ],
    allergens: ["Pește", "Ou", "Lactoză", "Gluten"],
    relatedFoods: ["peste-alb", "ou", "ardei-gras", "iaurt"],
    storage: "Se păstrează la congelator 2 luni.",
  },
  {
    id: "piure-pastarnac-mar-paine-moale",
    name: "Piure de păstârnac cu măr",
    emoji: "🥕",
    mealType: "pranz",
    time: "25 min",
    age: "6+ luni",
    difficulty: "Ușor",
    servings: "1-2",
    ingredients: [
      "2 păstârnaci medii",
      "1 măr",
      "½ cană lapte (matern sau formulă)",
      "1 lingură unt nesărat (opțional)",
      "1 felie pâine moale (opțional)",
      "1 vârf nuci măcinate (opțional)",
    ],
    steps: [
      "Curăță păstârnacii și mărul. Scoate semințele mărului.",
      "Taie în cuburi și pune într-o oală cu lapte și apă.",
      "Fierbe 20 minute la foc mic.",
      "Scurge (păstrează lichidul).",
      "Pasează cu untul, adaugă lichid pentru consistență.",
      "Prăjește pâinea, taie în bețișoare.",
      "Presară nuci măcinate deasupra.",
    ],
    allergens: ["Lactoză", "Nuci", "Gluten"],
    relatedFoods: ["pastarnac", "mere", "nuci-macinate", "paine"],
    storage: "Se păstrează la frigider 5 zile.",
  },
  {
    id: "orez-prajit-ou-legume",
    name: "Orez prăjit cu ou și legume",
    emoji: "🍳",
    mealType: "pranz",
    time: "20 min",
    age: "8+ luni",
    difficulty: "Mediu",
    servings: "1-2",
    ingredients: [
      "½ cană orez fiert (de la o zi înainte ideal)",
      "1 ceapă verde",
      "1 vârf ghimbir pudră",
      "1 vârf usturoi pudră",
      "2 ouă",
      "1 morcov mic ras",
      "2 linguri ulei de floarea-soarelui",
      "1 vârf semințe de susan (opțional)",
    ],
    steps: [
      "Taie ceapa verde mărunt. Bate ouăle cu ghimbirul și usturoiul.",
      "Încălzește uleiul la foc mare. Adaugă orezul, prăjește 5 minute.",
      "Adaugă morcovul ras, gătește 2 minute.",
      "Toarnă ouăle, amestecă continuu 3 minute.",
      "Presară semințe de susan.",
      "Servește la temperatura camerei.",
    ],
    allergens: ["Ou", "Susan"],
    relatedFoods: ["orez", "ou", "morcov", "ghimbir"],
    storage: "Se păstrează la frigider 1 zi.",
  },
];

const OLDER_BABY_RECIPES: RecipeCatalogItem[] = [
  {
    id: "paste-somon-smantana",
    name: "Paste cu somon și smântânică",
    emoji: "🐟",
    mealType: "pranz",
    time: "20 min",
    age: "10+ luni",
    difficulty: "Mediu",
    servings: "2-3",
    ingredients: [
      "80g paste fusilli mici",
      "100g somon proaspăt fără oase",
      "2 linguri smântână pentru gătit",
      "1 linguriță suc de lămâie",
      "½ cană spanac proaspăt",
      "1 linguriță ulei de măsline",
    ],
    steps: [
      "Fierbe pastele conform instrucțiunilor. Scurge.",
      "Gătește somonul la abur 10 minute. Verifică oasele! Sfărâmă.",
      "Încălzește uleiul, adaugă spanacul, gătește 2 minute.",
      "Adaugă smântâna și sucul de lămâie. Amestecă.",
      "Combină pastele cu sosul și somonul.",
      "Servește călduț.",
    ],
    allergens: ["Pește", "Lactoză", "Gluten"],
    relatedFoods: ["somon", "spanac", "paste"],
    storage: "Se păstrează la frigider 2 zile.",
  },
  {
    id: "tocana-miel-legume",
    name: "Tocăniță de miel cu legume de toamnă",
    emoji: "🍖",
    mealType: "cina",
    time: "1 oră",
    age: "10+ luni",
    difficulty: "Mediu",
    servings: "6-8",
    ingredients: [
      "300g miel tocat",
      "2 morcovi",
      "1 păstârnac",
      "1 cartof",
      "1 ceapă",
      "2 căței usturoi",
      "2 linguri ulei",
      "2 căni apă sau supă de legume",
      "1 frunză de dafin",
      "1 vârf cimbru și rozmarin",
    ],
    steps: [
      "Taie toate legumele în cuburi mici.",
      "Încălzește uleiul, rumene mielul 5 minute sfărâmând.",
      "Adaugă ceapa și usturoiul, gătește 3 minute.",
      "Adaugă morcovii, păstârnacul și cartoful.",
      "Toarnă apa, adaugă foaia de dafin și ierburile.",
      "Fierbe, apoi foc mic acoperit 45 minute.",
      "Scoate foaia de dafin. Zdrobește ușor legumele.",
      "Servește călduță.",
    ],
    allergens: [],
    relatedFoods: ["miel", "morcov", "pastarnac", "cartof", "usturoi"],
    storage: "Se păstrează la frigider 3 zile sau congelator 3 luni.",
  },
  {
    id: "mini-pizza-legume",
    name: "Mini pizza pe pâine cu legume",
    emoji: "🍕",
    mealType: "pranz",
    time: "15 min",
    age: "10+ luni",
    difficulty: "Ușor",
    servings: 1,
    ingredients: [
      "1 felie pâine moale groasă",
      "2 linguri sos de roșii fără sare",
      "30g mozzarella rasă",
      "2 buchețele broccoli fierte și tocate",
      "¼ ardei gras tocat mărunt",
      "1 vârf oregano uscat (opțional)",
    ],
    steps: [
      "Preîncălzește cuptorul la 200°C.",
      "Întinde sosul de roșii pe pâine.",
      "Presară broccoli tocat și ardeiul.",
      "Adaugă mozzarella rasă deasupra.",
      "Coace 8-10 minute până brânza se topește.",
      "Lasă să se răcească! Taie în bețișoare sau pătrate.",
    ],
    allergens: ["Lactoză", "Gluten"],
    relatedFoods: ["rosii", "broccoli", "ardei-gras", "paine"],
    storage: "Se servește proaspăt.",
  },
  {
    id: "ciorba-perisoare-pui",
    name: "Ciorbă de perișoare de pui",
    emoji: "🍲",
    mealType: "pranz",
    time: "45 min",
    age: "10+ luni",
    difficulty: "Mediu",
    servings: "6-8",
    ingredients: [
      "300g pui tocat",
      "1 ou",
      "3 linguri orez",
      "1 morcov",
      "1 păstârnac",
      "½ țelină mică",
      "1 ceapă",
      "1 roșie",
      "1 lingură ulei",
      "6 căni apă",
      "1 legătură pătrunjel",
      "1 linguriță suc de lămâie",
    ],
    steps: [
      "Amestecă puiul tocat cu oul și 2 linguri orez. Formează perișoare mici.",
      "Taie legumele în cuburi mici.",
      "Încălzește uleiul, călește ceapa 3 minute.",
      "Adaugă morcovul, păstârnacul și țelina. Gătește 5 minute.",
      "Toarnă apa, adu la fierbere.",
      "Adaugă perișoarele una câte una și restul de orez.",
      "Gătește la foc mic 25 minute.",
      "Adaugă roșia tocată și pătrunjelul. Stropește cu lămâie.",
    ],
    allergens: ["Ou"],
    relatedFoods: ["pui", "ou", "orez", "morcov", "pastarnac", "rosii"],
    storage: "Se păstrează la frigider 3 zile sau congelator 2 luni.",
  },
  {
    id: "cartofi-dulci-umpluti",
    name: "Cartofi dulci umpluți cu brânză și spanac",
    emoji: "🍠",
    mealType: "cina",
    time: "45 min",
    age: "10+ luni",
    difficulty: "Mediu",
    servings: 2,
    ingredients: [
      "2 cartofi dulci medii",
      "½ cană spanac proaspăt tocat",
      "¼ cană brânză de vaci",
      "1 linguriță unt nesărat",
      "1 vârf nucșoară",
      "1 vârf semințe de cânepă",
    ],
    steps: [
      "Spală cartofii dulci, înțeapă-i cu furculița.",
      "Coace la 200°C timp de 35-40 minute.",
      "Taie-i în jumătate, scoate miezul cu lingura.",
      "Gătește spanacul 2 minute în unt.",
      "Amestecă miezul cu spanacul, brânza și nucșoara.",
      "Umple cojile cu amestecul.",
      "Presară semințe de cânepă deasupra.",
    ],
    allergens: ["Lactoză"],
    relatedFoods: ["cartof-dulce", "spanac", "branza-vaci"],
    storage: "Se păstrează la frigider 3 zile.",
  },
  {
    id: "ghiveci-legume-quinoa",
    name: "Ghiveci de legume cu quinoa",
    emoji: "🥘",
    mealType: "pranz",
    time: "40 min",
    age: "10+ luni",
    difficulty: "Mediu",
    servings: "4-6",
    ingredients: [
      "½ cană quinoa",
      "1 dovlecel mic",
      "1 vânătă mică",
      "1 ardei gras",
      "1 roșie mare",
      "1 ceapă",
      "2 căței usturoi",
      "3 linguri ulei de măsline",
      "1 cană apă",
      "1 vârf busuioc uscat",
    ],
    steps: [
      "Clătește quinoa. Fierbe cu 1 cană apă, 15 minute. Scurge.",
      "Taie toate legumele în cuburi de ~1cm.",
      "Încălzește uleiul, călește ceapa și usturoiul 3 minute.",
      "Adaugă vinetele și ardeiul. Gătește 5 minute.",
      "Adaugă dovlecelul și roșia. Gătește 10 minute.",
      "Amestecă quinoa fiartă cu legumele.",
      "Presară busuioc. Servește călduț.",
    ],
    allergens: [],
    relatedFoods: ["quinoa", "dovlecel", "vinete", "ardei-gras", "rosii", "usturoi"],
    storage: "Se păstrează la frigider 3 zile sau congelator 2 luni.",
  },
  {
    id: "budinca-broccoli-branza",
    name: "Budincă de broccoli cu brânză",
    emoji: "🥦",
    mealType: "cina",
    time: "35 min",
    age: "10+ luni",
    difficulty: "Mediu",
    servings: "4-6",
    ingredients: [
      "2 căni broccoli buchețele",
      "3 ouă",
      "½ cană lapte",
      "½ cană brânză rasă",
      "1 lingură unt pentru uns forma",
      "1 vârf nucșoară",
    ],
    steps: [
      "Fierbe broccoli la abur 8 minute. Tocă grosier.",
      "Bate ouăle cu laptele și nucșoara.",
      "Amestecă broccoli cu compoziția de ouă.",
      "Adaugă jumătate din brânză.",
      "Unge o formă mică de cuptor cu unt.",
      "Toarnă amestecul, presară restul de brânză.",
      "Coace la 180°C, 20-25 minute până e aurie.",
      "Lasă să se răcească. Taie în cuburi sau bețișoare.",
    ],
    allergens: ["Ou", "Lactoză"],
    relatedFoods: ["broccoli", "ou", "branza-vaci"],
    storage: "Se păstrează la frigider 4 zile.",
  },
  {
    id: "vita-cu-prune-orez",
    name: "Tocăniță de vită cu prune și orez",
    emoji: "🥩",
    mealType: "pranz",
    time: "1 oră",
    age: "10+ luni",
    difficulty: "Mediu",
    servings: "4-6",
    ingredients: [
      "300g vită tocată",
      "5-6 prune uscate",
      "1 ceapă",
      "1 morcov",
      "2 linguri ulei",
      "2 căni apă",
      "½ cană orez",
      "1 vârf scorțișoară și chimion",
    ],
    steps: [
      "Înmoaie prunele 15 minute în apă caldă. Taie-le mărunt.",
      "Rumene vita tocată în ulei 10 minute, sfărâmând bine.",
      "Adaugă ceapa și morcovul tăiate mărunt. Gătește 5 minute.",
      "Adaugă prunele, apa și condimentele.",
      "Fierbe, apoi foc mic 30 minute.",
      "Separat fierbe orezul 15 minute.",
      "Servește tocănița peste orez.",
    ],
    allergens: [],
    relatedFoods: ["vita", "prune", "orez", "morcov"],
    storage: "Se păstrează la frigider 3 zile sau congelator 3 luni.",
  },
  {
    id: "supa-crema-mazare-menta",
    name: "Supă cremă de mazăre cu mentă",
    emoji: "🫛",
    mealType: "pranz",
    time: "20 min",
    age: "10+ luni",
    difficulty: "Ușor",
    servings: "3-4",
    ingredients: [
      "2 căni mazăre congelată",
      "1 cartof mic",
      "1 ceapă mică",
      "1 lingură unt",
      "2 căni apă",
      "3-4 frunze mentă proaspătă",
      "2 linguri iaurt (opțional)",
    ],
    steps: [
      "Taie cartoful și ceapa mărunt.",
      "Topește untul, călește ceapa 3 minute.",
      "Adaugă cartoful și apa. Fierbe 10 minute.",
      "Adaugă mazărea congelată. Gătește 5 minute.",
      "Adaugă menta. Pasează cu blenderul.",
      "Servește cu o lingură de iaurt deasupra.",
    ],
    allergens: ["Lactoză"],
    relatedFoods: ["mazare", "cartof", "iaurt", "busuioc"],
    storage: "Se păstrează la frigider 4 zile sau congelator 2 luni.",
  },
  {
    id: "clatite-dovlecel-branza",
    name: "Clătite sărate de dovlecel cu brânză",
    emoji: "🥒",
    mealType: "mic-dejun",
    time: "25 min",
    age: "10+ luni",
    difficulty: "Mediu",
    servings: "3-4",
    ingredients: [
      "1 dovlecel mediu",
      "2 ouă",
      "3 linguri făină",
      "¼ cană brânză de vaci",
      "1 vârf mărar tocat",
      "2 linguri ulei",
      "¼ cană iaurt natural (opțional)",
    ],
    steps: [
      "Rade dovlecelul, stoarce excesul de apă cu mâinile.",
      "Amestecă dovlecelul cu ouăle, făina, brânza și mărarul.",
      "Încălzește uleiul la foc mediu.",
      "Pune câte 2 linguri de compoziție, aplatizează.",
      "Gătește 3 minute pe fiecare parte.",
      "Servește cu iaurt pe lângă.",
    ],
    allergens: ["Ou", "Lactoză", "Gluten"],
    relatedFoods: ["dovlecel", "ou", "branza-vaci", "iaurt"],
    storage: "Se păstrează la frigider 2 zile sau congelator 2 luni.",
  },
  {
    id: "supa-rosii-grisine",
    name: "Supă cremă de roșii cu grissini de casă",
    emoji: "🍅",
    mealType: "pranz",
    time: "30 min",
    age: "12+ luni",
    difficulty: "Mediu",
    servings: "4-6",
    ingredients: [
      "6 roșii mari coapte",
      "1 ceapă",
      "2 căței usturoi",
      "2 linguri ulei de măsline",
      "1 cană apă",
      "1 linguriță busuioc uscat",
      "2 linguri ricotta (opțional)",
      "4 grissini din comerț sau de casă",
    ],
    steps: [
      "Opărește roșiile, curăță coaja, taie-le în jumătăți.",
      "Călește ceapa și usturoiul în ulei 5 minute.",
      "Adaugă roșiile și busuiocul. Gătește 10 minute.",
      "Adaugă apa. Fierbe 10 minute.",
      "Pasează cu blenderul.",
      "Servește cu o lingură de ricotta și grissini pe lângă.",
    ],
    allergens: ["Lactoză", "Gluten"],
    relatedFoods: ["rosii", "usturoi", "branza-vaci", "paine"],
    storage: "Se păstrează la frigider 5 zile sau congelator 3 luni.",
  },
  {
    id: "paste-pesto-pui",
    name: "Paste cu pesto de busuioc și pui",
    emoji: "🍝",
    mealType: "pranz",
    time: "30 min",
    age: "12+ luni",
    difficulty: "Mediu",
    servings: "3-4",
    ingredients: [
      "100g paste fusilli",
      "1 piept de pui mic fiert și sfărâmat",
      "1 cană busuioc proaspăt",
      "1 cățel usturoi",
      "2 linguri ulei de măsline",
      "1 lingură nuci sau migdale",
      "1 linguriță suc de lămâie",
      "1 roșie (opțional)",
    ],
    steps: [
      "Fierbe puiul 25 minute. Sfărâmă cu furculițele.",
      "Fierbe pastele conform instrucțiunilor. Scurge.",
      "Pentru pesto: mixează busuiocul, usturoiul, uleiul, nucile și lămâia.",
      "Amestecă pastele cu pesto și puiul sfărâmat.",
      "Taie roșia pe lângă.",
      "Servește călduț sau la temperatura camerei.",
    ],
    allergens: ["Nuci", "Gluten"],
    relatedFoods: ["pui", "busuioc", "nuci-macinate", "paste", "rosii"],
    storage: "Se păstrează la frigider 3 zile.",
  },
  {
    id: "cartofi-piure-vita-sos",
    name: "Piure de cartofi cu tocăniță de vită",
    emoji: "🥔",
    mealType: "cina",
    time: "45 min",
    age: "12+ luni",
    difficulty: "Mediu",
    servings: "4-6",
    ingredients: [
      "3 cartofi medii",
      "2 linguri unt",
      "¼ cană lapte",
      "300g vită tocată",
      "1 ceapă",
      "1 morcov",
      "1 cană roșii pasate",
      "1 cană apă",
      "1 lingură ulei",
      "1 vârf boia dulce",
    ],
    steps: [
      "Curăță cartofii, fierbe-i 20 minute. Pasează cu unt și lapte.",
      "Călește ceapa tocată în ulei 5 minute.",
      "Adaugă vita, sfărâmă bine. Rumene 10 minute.",
      "Adaugă morcovul ras, roșiile și apa.",
      "Gătește la foc mic 20 minute.",
      "Pune piure în farfurie cu tocănița deasupra.",
    ],
    allergens: ["Lactoză"],
    relatedFoods: ["cartof", "vita", "morcov", "rosii"],
    storage: "Se păstrează la frigider 3 zile sau congelator 2 luni.",
  },
  {
    id: "orez-pui-legume-asiatic",
    name: "Orez cu pui și legume stil asiatic",
    emoji: "🍚",
    mealType: "pranz",
    time: "30 min",
    age: "12+ luni",
    difficulty: "Mediu",
    servings: "2-3",
    ingredients: [
      "½ cană orez basmati",
      "150g piept de pui",
      "1 morcov ras",
      "½ cană mazăre",
      "1 ceapă verde",
      "1 linguriță ulei de susan",
      "1 linguriță sos de soia fără sare",
      "1 vârf ghimbir ras",
    ],
    steps: [
      "Fierbe orezul 15 minute. Scurge.",
      "Fierbe puiul 25 minute. Taie-l în cuburi mici.",
      "Încălzește uleiul de susan. Călește ceapa verde 2 minute.",
      "Adaugă morcovul ras și mazărea. Gătește 3 minute.",
      "Adaugă orezul, puiul și ghimbirul. Amestecă.",
      "Stropește cu sos de soia. Servește călduț.",
    ],
    allergens: ["Susan", "Soia"],
    relatedFoods: ["orez", "pui", "morcov", "mazare", "ghimbir"],
    storage: "Se păstrează la frigider 2 zile.",
  },
  {
    id: "lasagna-legume-simpla",
    name: "Lasagna simplă cu legume",
    emoji: "🍝",
    mealType: "cina",
    time: "1 oră",
    age: "12+ luni",
    difficulty: "Mediu",
    servings: "6-8",
    ingredients: [
      "6 foi de lasagna",
      "1 dovlecel ras",
      "1 morcov ras",
      "1 cană spanac",
      "1 cană ricotta",
      "1 cană sos de roșii",
      "½ cană mozzarella rasă",
      "1 lingură ulei",
      "1 vârf nucșoară",
    ],
    steps: [
      "Călește dovlecelul și morcovul ras în ulei 5 minute.",
      "Adaugă spanacul, gătește 2 minute.",
      "Amestecă ricotta cu nucșoara.",
      "Într-o tavă unsă: strat sos, strat foi, strat legume, strat ricotta.",
      "Repetă straturile. Termină cu sos și mozzarella deasupra.",
      "Acoperă cu folie. Coace la 180°C, 30 minute.",
      "Scoate folia, mai coace 10 minute.",
      "Lasă 10 minute să se răcească. Taie în pătrate.",
    ],
    allergens: ["Lactoză", "Gluten"],
    relatedFoods: ["dovlecel", "morcov", "spanac", "branza-vaci", "rosii", "paste"],
    storage: "Se păstrează la frigider 4 zile sau congelator 2 luni.",
  },
  {
    id: "biban-cuptor-legume",
    name: "Biban la cuptor cu legume",
    emoji: "🐟",
    mealType: "cina",
    time: "35 min",
    age: "12+ luni",
    difficulty: "Mediu",
    servings: "2-3",
    ingredients: [
      "200g file de biban sau doradă",
      "1 dovlecel mic",
      "1 morcov",
      "1 cartof mic",
      "2 linguri ulei de măsline",
      "1 linguriță suc de lămâie",
      "1 vârf mărar (opțional)",
    ],
    steps: [
      "Preîncălzește cuptorul la 190°C.",
      "Taie legumele în bețișoare subțiri.",
      "Pune legumele pe tavă, stropește cu 1 lingură ulei.",
      "Coace legumele 15 minute.",
      "Verifică peștele de oase! Pune-l peste legume.",
      "Stropește cu restul de ulei și suc de lămâie.",
      "Coace încă 12-15 minute.",
      "Sfărâmă peștele cu furculița. Presară mărar.",
    ],
    allergens: ["Pește"],
    relatedFoods: ["peste-alb", "dovlecel", "morcov", "cartof"],
    storage: "Se păstrează la frigider 2 zile.",
  },
  {
    id: "chiftele-legume-cuptor",
    name: "Chifteluțe de legume la cuptor",
    emoji: "🥕",
    mealType: "pranz",
    time: "40 min",
    age: "12+ luni",
    difficulty: "Mediu",
    servings: "6-8",
    ingredients: [
      "1 morcov mare",
      "1 dovlecel mic",
      "½ cană mazăre",
      "½ cană conopidă buchețele",
      "2 ouă",
      "½ cană pesmet",
      "¼ cană brânză rasă",
      "1 lingură ulei",
    ],
    steps: [
      "Fierbe morcovul, mazărea și conopida 10 minute. Scurge.",
      "Rade dovlecelul crud. Stoarce apa.",
      "Pasează legumele fierte grosier (nu prea fin).",
      "Amestecă cu dovlecelul, ouăle, pesmetul și brânza.",
      "Formează chifteluțe mici sau bețișoare.",
      "Unge tava. Coace la 200°C, 10 minute pe fiecare parte.",
      "Servește cu iaurt pe lângă.",
    ],
    allergens: ["Ou", "Lactoză", "Gluten"],
    relatedFoods: ["morcov", "dovlecel", "mazare", "conopida", "ou", "iaurt"],
    storage: "Se păstrează la frigider 4 zile sau congelator 2 luni.",
  },
  {
    id: "tortilla-vita-legume",
    name: "Tortilla rulată cu vită și legume",
    emoji: "🌯",
    mealType: "pranz",
    time: "25 min",
    age: "12+ luni",
    difficulty: "Mediu",
    servings: "2-3",
    ingredients: [
      "200g vită tocată",
      "1 ardei gras",
      "1 morcov ras",
      "½ ceapă",
      "1 lingură ulei",
      "1 linguriță boia dulce",
      "2 tortilla medii",
      "2 linguri iaurt natural",
      "¼ cană salată verde tocată",
    ],
    steps: [
      "Călește ceapa în ulei 3 minute.",
      "Adaugă vita, sfărâmă. Gătește 10 minute.",
      "Adaugă ardeiul tocat, morcovul ras și boia. Gătește 5 minute.",
      "Încălzește tortilla 30 secunde pe fiecare parte.",
      "Întinde iaurt pe tortilla.",
      "Adaugă carnea cu legume și salata.",
      "Rulează strâns, taie în rondele de 3 cm.",
    ],
    allergens: ["Lactoză", "Gluten"],
    relatedFoods: ["vita", "ardei-gras", "morcov", "iaurt"],
    storage: "Se mănâncă proaspăt, nu se păstrează bine.",
  },
  {
    id: "supa-legume-paste-alfabet",
    name: "Supă de legume cu paste alfabet",
    emoji: "🍲",
    mealType: "pranz",
    time: "30 min",
    age: "12+ luni",
    difficulty: "Ușor",
    servings: "4-6",
    ingredients: [
      "1 morcov",
      "1 cartof mic",
      "½ țelină mică",
      "1 ceapă",
      "1 roșie",
      "1 lingură ulei",
      "4 căni apă",
      "½ cană paste alfabet sau stelute",
      "1 legătură pătrunjel",
    ],
    steps: [
      "Taie toate legumele în cuburi mici (0.5-1cm).",
      "Încălzește uleiul, călește ceapa 3 minute.",
      "Adaugă morcovul, cartoful și țelina. Gătește 5 minute.",
      "Toarnă apa. Fierbe, apoi foc mic 15 minute.",
      "Adaugă pastele și roșia tocată. Gătește 8-10 minute.",
      "Presară pătrunjel tocat mărunt.",
      "Servește călduță.",
    ],
    allergens: ["Gluten"],
    relatedFoods: ["morcov", "cartof", "rosii", "paste"],
    storage:
      "Se păstrează la frigider 3 zile. Nu congela (pastele se înmoaie prea tare).",
  },
  {
    id: "curry-pui-cocos-orez",
    name: "Curry ușor de pui cu orez",
    emoji: "🍛",
    mealType: "cina",
    time: "35 min",
    age: "12+ luni",
    difficulty: "Mediu",
    servings: "4-6",
    ingredients: [
      "2 piepturi de pui",
      "1 ceapă",
      "2 căței usturoi",
      "1 bucățică ghimbir",
      "1 lingură ulei de cocos",
      "1 cană roșii pasate",
      "½ cană lapte de cocos",
      "½ linguriță turmeric, chimion, coriandru, scorțișoară",
      "1 cană orez basmati",
      "½ mango (opțional)",
    ],
    steps: [
      "Fierbe puiul 25 minute. Sfărâmă cu furculițele.",
      "Taie ceapa, usturoiul și ghimbirul mărunt.",
      "Încălzește uleiul de cocos, călește ceapa 3 minute.",
      "Adaugă usturoiul, ghimbirul și condimentele. Gătește 1 minut.",
      "Adaugă roșiile, fierbe 5 minute.",
      "Adaugă puiul sfărâmat și laptele de cocos.",
      "Gătește la foc mic 10 minute.",
      "Fierbe orezul separat. Servește curry-ul peste orez.",
      "Adaugă mango feliat pe lângă.",
    ],
    allergens: ["Nucă de cocos"],
    relatedFoods: ["pui", "unt-cocos", "rosii", "ghimbir", "turmeric", "orez", "mango"],
    storage: "Se păstrează la frigider 3 zile sau congelator 2 luni.",
  },
];

export const RECIPES: RecipeCatalogItem[] = [
  ...LEGACY_RECIPES,
  ...MIC_DEJUN_RECIPES,
  ...MIC_DEJUN_8PLUS_EXTRA,
  ...MIC_DEJUN_10PLUS_EXTRA,
  ...MIC_DEJUN_12PLUS_EXTRA,
  ...PRANZ_LUNCH_RECIPES,
  ...OLDER_BABY_RECIPES,
  ...CINA_8PLUS_RECIPES,
  ...CINA_10PLUS_DINNER_RECIPES,
  ...CINA_12PLUS_DINNER_RECIPES,
  ...PRANZ_6_8_RECIPES,
  ...PRANZ_8_10_RECIPES,
  ...PRANZ_12PLUS_RECIPES,
  ...GUSTARE_RECIPES,
  ...GUSTARI_12PLUS_RECIPES,
];
