import type { RecipeCatalogItem } from "./recipesDatabase";

export const RETETE_PESTE: RecipeCatalogItem[] = [
  {
    id: "piure-somon-cartof-dulce",
    name: "Piure de somon cu cartof dulce",
    emoji: "🐟",
    mealType: "pranz",
    time: "25 min",
    age: "8+ luni",
    difficulty: "Ușor",
    servings: "2-3",
    ingredients: ["100g file de somon (fără piele, fără oase)","1 cartof dulce mediu","1 linguriță ulei de măsline","1 vârf cimbru (opțional)","apă cât cuprinde"],
    steps: ["Curăță cartoful dulce și taie-l cuburi. Fierbe 15 minute până se înmoaie.","Verifică somonul atent pentru oase (trece cu degetul pe toată suprafața).","Gătește somonul la abur sau în apă clocotită 8-10 minute.","Blendează cartoful dulce cu somonul și uleiul de măsline.","Adaugă apă de la fiertură până ajungi la consistența dorită.","Adaugă cimbru. Servește călduț."],
    allergens: ["Pește"],
    relatedFoods: ["somon", "cartof-dulce"],
    storage: "Se păstrează la frigider 2 zile sau congelator 1 lună.",
  },
  {
    id: "piure-cod-morcov-pastarnac",
    name: "Piure de cod cu morcov și păstârnac",
    emoji: "🐠",
    mealType: "pranz",
    time: "25 min",
    age: "8+ luni",
    difficulty: "Ușor",
    servings: "2-3",
    ingredients: ["100g file de cod (fără piele, fără oase)","2 morcovi","1 rădăcină mică de păstârnac","1 linguriță ulei de măsline","1 vârf mărar"],
    steps: ["Curăță morcovii și păstârnacul, taie-i cuburi.","Fierbe legumele 15 minute până sunt moi.","Verifică codul pentru oase și găteşte-l la abur 8 minute.","Blendează totul împreună cu uleiul de măsline.","Adaugă apă de fiertură pentru consistență.","Presară mărar. Servește călduț."],
    allergens: ["Pește"],
    relatedFoods: ["cod", "morcov", "pastarnac"],
    storage: "Se păstrează la frigider 2 zile sau congelator 1 lună.",
  },
  {
    id: "piure-merluciu-broccoli",
    name: "Piure de merluciu cu broccoli",
    emoji: "🥦",
    mealType: "pranz",
    time: "20 min",
    age: "8+ luni",
    difficulty: "Ușor",
    servings: "2",
    ingredients: ["100g file de merluciu (fără piele, fără oase)","150g broccoli (buchețele)","1 linguriță unt","1 vârf nucșoară","apă cât cuprinde"],
    steps: ["Fierbe broccoli la abur 8-10 minute până se înmoaie.","Verifică merluciul pentru oase. Gătește-l la abur 8 minute.","Blendează broccoli cu merluciul și untul.","Adaugă apă de la abur pentru consistență.","Adaugă un vârf de nucșoară. Servește imediat."],
    allergens: ["Pește", "Lactoză"],
    relatedFoods: ["merluciu", "broccoli"],
    storage: "Se păstrează la frigider 2 zile.",
  },
  {
    id: "supa-crema-somon-zucchini",
    name: "Supă cremă de somon cu zucchini",
    emoji: "🍵",
    mealType: "pranz",
    time: "30 min",
    age: "8+ luni",
    difficulty: "Ușor",
    servings: "3-4",
    ingredients: ["150g file de somon (fără piele, fără oase)","2 zucchini mici","1 morcov","1 linguriță ulei de măsline","1 vârf busuioc uscat","500ml apă"],
    steps: ["Taie zucchinii și morcovul cuburi. Fierbe în apă 15 minute.","Verifică somonul pentru oase. Adaugă-l în supă.","Fierbe încă 10 minute la foc mic.","Scoate somonul, verifică din nou pentru oase, adaugă-l înapoi.","Blendează totul cu uleiul de măsline și busuiocul.","Servește călduț."],
    allergens: ["Pește"],
    relatedFoods: ["somon", "zucchini", "morcov"],
    storage: "Se păstrează la frigider 2 zile sau congelator 1 lună.",
  },
  {
    id: "pastrav-piure-mazare",
    name: "Păstrăv cu piure de mazăre",
    emoji: "🐟",
    mealType: "pranz",
    time: "25 min",
    age: "8+ luni",
    difficulty: "Ușor",
    servings: "2",
    ingredients: ["100g file de păstrăv (fără piele, fără oase)","150g mazăre (proaspătă sau congelată)","1 linguriță unt","1 vârf mentă uscată (opțional)","zeamă de lămâie (1-2 picături, opțional)"],
    steps: ["Fierbe mazărea 5-7 minute. Pasează bine cu o furculiță.","Verifică păstrăvul pentru oase. Gătește-l la abur 10 minute.","Amestecă untul în piureul de mazăre.","Fărâmițează bine păstrăvul. Verifică din nou pentru oase.","Pune piureul în farfurie, adaugă păstrăvul deasupra.","Adaugă mentă și câteva picături de lămâie."],
    allergens: ["Pește", "Lactoză"],
    relatedFoods: ["pastrav", "mazare"],
    storage: "Se păstrează la frigider 2 zile.",
  },
  {
    id: "sardine-piure-cartof",
    name: "Sardine cu piure de cartof",
    emoji: "🐟",
    mealType: "pranz",
    time: "20 min",
    age: "8+ luni",
    difficulty: "Ușor",
    servings: "2",
    ingredients: ["50g sardine în apă (conservă, fără sare adăugată)","2 cartofi medii","1 linguriță ulei de măsline","1 vârf mărar"],
    steps: ["Fierbe cartofii 15-20 minute. Pasează-i cu uleiul de măsline.","Scurge sardinele. Verifică-le atent pentru oase (sardinele conservate au oasele moi, dar verifică).","Fărâmițează bine sardinele.","Amestecă sardinele în piureul de cartof.","Presară mărar. Servește călduț."],
    allergens: ["Pește"],
    relatedFoods: ["sardine", "cartof"],
    storage: "Se consumă imediat sau se păstrează la frigider 1 zi.",
  },
  {
    id: "chiftele-somon-morcov-cuptor",
    name: "Chifteluțe de somon cu morcov la cuptor",
    emoji: "🟠",
    mealType: "pranz",
    time: "35 min",
    age: "10+ luni",
    difficulty: "Mediu",
    servings: "8-10 chifteluțe",
    ingredients: ["200g file de somon (fără piele, fără oase)","1 morcov ras","1 ou","2 linguri fulgi de ovăz (măcinați)","1 vârf mărar","1 linguriță ulei pentru uns tava"],
    steps: ["Preîncălzește cuptorul la 180°C.","Verifică somonul atent pentru oase. Toacă mărunt sau blendează grosier.","Amestecă somonul cu morcovul ras, oul, fulgii de ovăz și mărarul.","Formează biluțe mici (cât o nucă).","Unge tava cu ulei. Pune biluțele și aplatizează-le ușor.","Coace 15-18 minute până se auresc ușor.","Lasă să se răcească puțin. Servește cu piure sau legume moi."],
    allergens: ["Pește", "Ou", "Gluten"],
    relatedFoods: ["somon", "morcov", "ou"],
    storage: "Se păstrează la frigider 3 zile sau congelator 2 luni.",
  },
  {
    id: "orez-cod-legume",
    name: "Orez cu cod și legume",
    emoji: "🍚",
    mealType: "pranz",
    time: "30 min",
    age: "10+ luni",
    difficulty: "Ușor",
    servings: "2-3",
    ingredients: ["100g file de cod (fără piele, fără oase)","¼ cană orez","1 morcov","½ zucchini","1 linguriță ulei de măsline","1 vârf cimbru","400ml apă"],
    steps: ["Curăță și taie legumele cuburi mici.","Fierbe orezul cu apa 15 minute la foc mic.","Verifică codul pentru oase. Adaugă-l peste orez în ultimele 8 minute.","Adaugă legumele în ultimele 10 minute.","Fărâmițează bine codul, verifică din nou pentru oase.","Amestecă, adaugă ulei și cimbru. Servește călduț."],
    allergens: ["Pește"],
    relatedFoods: ["cod", "orez", "morcov", "zucchini"],
    storage: "Se păstrează la frigider 2 zile.",
  },
  {
    id: "peste-cuptor-legume-coapte",
    name: "File de pește la cuptor cu legume coapte",
    emoji: "🍽️",
    mealType: "cina",
    time: "35 min",
    age: "10+ luni",
    difficulty: "Ușor",
    servings: "2",
    ingredients: ["150g file de somon sau cod (fără piele, fără oase)","1 zucchini","1 morcov","½ ardei gras roșu (fără semințe)","1 lingură ulei de măsline","1 vârf oregano","zeamă de lămâie (câteva picături)"],
    steps: ["Preîncălzește cuptorul la 180°C.","Taie legumele bețișoare groase (cât un deget).","Pune legumele în tavă, stropește cu jumătate din ulei.","Verifică peștele pentru oase. Pune-l peste legume.","Stropește cu restul de ulei, oregano și lămâie.","Acoperă cu folie aluminiu. Coace 20-25 minute.","Verifică din nou peștele pentru oase înainte de servire.","Fărâmițează peștele. Servește cu legumele."],
    allergens: ["Pește"],
    relatedFoods: ["somon", "zucchini", "morcov", "ardei"],
    storage: "Se păstrează la frigider 2 zile.",
  },
  {
    id: "tocana-merluciu-rosii",
    name: "Tocăniță de merluciu cu roșii și legume",
    emoji: "🍅",
    mealType: "pranz",
    time: "30 min",
    age: "10+ luni",
    difficulty: "Mediu",
    servings: "2-3",
    ingredients: ["150g file de merluciu (fără piele, fără oase)","2 roșii coapte (sau 100ml roșii pasate fără sare)","1 morcov","½ ceapă","1 linguriță ulei de măsline","1 vârf busuioc","1 vârf oregano"],
    steps: ["Toacă ceapa mărunt. Curăță și taie morcovul cuburi mici.","Călește ceapa în ulei la foc mic 5 minute.","Adaugă morcovul, gătește 5 minute.","Adaugă roșiile. Fierbe 10 minute la foc mic.","Verifică merluciul pentru oase. Adaugă-l în sos.","Fierbe 8-10 minute. Fărâmițează bine peștele.","Adaugă busuioc și oregano. Servește cu orez sau pâine moale."],
    allergens: ["Pește"],
    relatedFoods: ["merluciu", "rosii", "morcov"],
    storage: "Se păstrează la frigider 2 zile.",
  },
  {
    id: "somon-linte-rosie",
    name: "Somon cu linte roșie",
    emoji: "🍛",
    mealType: "pranz",
    time: "30 min",
    age: "10+ luni",
    difficulty: "Ușor",
    servings: "2-3",
    ingredients: ["100g file de somon (fără piele, fără oase)","½ cană linte roșie","1 morcov","1 linguriță ulei de măsline","1 vârf curcuma","1 vârf chimen","400ml apă"],
    steps: ["Clătește lintea. Fierbe cu apa și morcovul tăiat cuburi 20 minute.","Verifică somonul pentru oase. Adaugă-l în ultimele 10 minute.","Fărâmițează somonul, verifică din nou pentru oase.","Amestecă bine. Adaugă uleiul, curcuma și chimenul.","Dacă consistența e prea groasă, mai adaugă puțină apă.","Servește călduț."],
    allergens: ["Pește"],
    relatedFoods: ["somon", "linte"],
    storage: "Se păstrează la frigider 2 zile sau congelator 1 lună.",
  },
  {
    id: "chiftele-cod-spanac",
    name: "Chifteluțe de cod cu spanac",
    emoji: "🟢",
    mealType: "cina",
    time: "35 min",
    age: "10+ luni",
    difficulty: "Mediu",
    servings: "8-10 chifteluțe",
    ingredients: ["200g file de cod (fără piele, fără oase)","50g spanac proaspăt (sau congelat, dezghețat și stors)","1 ou","2 linguri fulgi de ovăz (măcinați)","1 vârf usturoi granulat (opțional)","1 linguriță ulei pentru uns tava"],
    steps: ["Preîncălzește cuptorul la 180°C.","Verifică codul pentru oase. Toacă mărunt.","Toacă spanacul mărunt. Dacă e congelat, stoarce bine apa.","Amestecă codul cu spanacul, oul și fulgii de ovăz.","Formează biluțe mici. Pune în tavă unsă.","Coace 15-18 minute.","Lasă să se răcească. Verifică din nou pentru oase înainte de servire."],
    allergens: ["Pește", "Ou", "Gluten"],
    relatedFoods: ["cod", "spanac", "ou"],
    storage: "Se păstrează la frigider 3 zile sau congelator 2 luni.",
  },
  {
    id: "pastrav-quinoa-legume",
    name: "Păstrăv cu quinoa și legume",
    emoji: "🌿",
    mealType: "cina",
    time: "30 min",
    age: "10+ luni",
    difficulty: "Ușor",
    servings: "2",
    ingredients: ["100g file de păstrăv (fără piele, fără oase)","¼ cană quinoa","1 morcov","½ zucchini","1 linguriță ulei de măsline","1 vârf mărar"],
    steps: ["Clătește quinoa. Fierbe cu ½ cană apă 15 minute.","Taie morcovul și zucchiniul cuburi mici. Fierbe 10 minute.","Verifică păstrăvul pentru oase. Gătește la abur 10 minute.","Fărâmițează păstrăvul, verifică din nou pentru oase.","Combină quinoa, legumele și păstrăvul.","Adaugă ulei și mărar. Servește călduț."],
    allergens: ["Pește"],
    relatedFoods: ["pastrav", "quinoa", "morcov"],
    storage: "Se păstrează la frigider 2 zile.",
  },
  {
    id: "somon-paste-smantana",
    name: "Paste cu somon și smântână",
    emoji: "🍝",
    mealType: "pranz",
    time: "25 min",
    age: "12+ luni",
    difficulty: "Ușor",
    servings: "2",
    ingredients: ["150g file de somon (fără piele, fără oase)","100g paste mici (farfalle sau penne)","2 linguri smântână grasă","1 linguriță ulei de măsline","1 vârf mărar","1 vârf coajă lămâie (opțional)"],
    steps: ["Fierbe pastele conform instrucțiunilor. Scurge.","Verifică somonul pentru oase. Gătește la abur 8-10 minute.","Fărâmițează somonul, verifică din nou pentru oase.","Amestecă pastele cu smântâna și uleiul la foc mic 2 minute.","Adaugă somonul, mărarul și coaja de lămâie.","Servește imediat."],
    allergens: ["Pește", "Lactoză", "Gluten"],
    relatedFoods: ["somon", "paste", "smantana"],
    storage: "Se consumă imediat. Nu se recomandă reîncălzirea cu smântână.",
  },
  {
    id: "ciorba-peste-legume",
    name: "Ciorbă de pește cu legume",
    emoji: "🍲",
    mealType: "pranz",
    time: "40 min",
    age: "12+ luni",
    difficulty: "Mediu",
    servings: "4-5",
    ingredients: ["200g file de somon sau cod (fără piele, fără oase)","2 morcovi","1 păstârnac","1 cartof","½ ceapă","1 lingură ulei de măsline","1 vârf leuștean uscat","1 vârf mărar","zeamă de lămâie (1 lingură, opțional)","700ml apă"],
    steps: ["Toacă ceapa. Taie morcovii, păstârnacul și cartoful cuburi.","Călește ceapa în ulei 3 minute.","Adaugă legumele și apa. Fierbe 20 minute.","Verifică peștele pentru oase. Adaugă-l în supă.","Fierbe 10 minute la foc mic.","Fărâmițează bine peștele, verifică din nou pentru oase.","Adaugă leușteanul, mărarul și zeama de lămâie.","Servește călduț."],
    allergens: ["Pește"],
    relatedFoods: ["somon", "morcov", "pastarnac", "cartof"],
    storage: "Se păstrează la frigider 2 zile sau congelator 1 lună.",
  },
  {
    id: "cod-piure-telina-mere",
    name: "Cod cu piure de țelină și mere",
    emoji: "🍎",
    mealType: "cina",
    time: "30 min",
    age: "12+ luni",
    difficulty: "Mediu",
    servings: "2",
    ingredients: ["150g file de cod (fără piele, fără oase)","200g țelină (rădăcină)","1 măr mic","1 linguriță unt","1 vârf nucșoară","zeamă de lămâie (câteva picături)"],
    steps: ["Curăță țelina și taie cuburi. Fierbe 15-20 minute.","Curăță și rade mărul.","Verifică codul pentru oase. Gătește la abur 8-10 minute.","Blendează țelina cu untul, nucșoara și zeama de lămâie.","Adaugă mărul ras în piure, amestecă.","Fărâmițează bine codul, verifică din nou pentru oase.","Servește codul peste piure."],
    allergens: ["Pește", "Lactoză"],
    relatedFoods: ["cod", "telina", "mere"],
    storage: "Se păstrează la frigider 2 zile.",
  },
  {
    id: "somon-orez-avocado",
    name: "Somon cu orez și avocado",
    emoji: "🥑",
    mealType: "pranz",
    time: "25 min",
    age: "12+ luni",
    difficulty: "Ușor",
    servings: "2",
    ingredients: ["150g file de somon (fără piele, fără oase)","¼ cană orez","½ avocado copt","zeamă de lămâie (câteva picături)","1 vârf susan (opțional)"],
    steps: ["Fierbe orezul conform instrucțiunilor.","Verifică somonul pentru oase. Gătește la abur sau la cuptor 10 minute.","Zdrobește avocado cu câteva picături de lămâie.","Fărâmițează somonul, verifică din nou pentru oase.","Pune orezul în bol, adaugă somonul și avocado deasupra.","Presară susan. Servește imediat."],
    allergens: ["Pește", "Susan"],
    relatedFoods: ["somon", "orez", "avocado"],
    storage: "Se consumă imediat (avocado se oxidează rapid).",
  },
  {
    id: "omlet-sardine-rosii-12",
    name: "Omletă cu sardine și roșii",
    emoji: "🍳",
    mealType: "mic-dejun",
    time: "15 min",
    age: "12+ luni",
    difficulty: "Ușor",
    servings: "1-2",
    ingredients: ["2 ouă","40g sardine în apă (conservă, fără sare)","1 roșie mică","1 linguriță ulei de măsline","1 vârf oregano"],
    steps: ["Scurge sardinele. Verifică pentru oase. Fărâmițează.","Toacă roșia cuburi mici.","Bate ouăle.","Încălzește uleiul în tigaie la foc mediu.","Toarnă ouăle. Când încep să se coaguleze, adaugă sardinele și roșia.","Pliază omleta. Adaugă oregano.","Servește cu pâine moale sau toast."],
    allergens: ["Pește", "Ou"],
    relatedFoods: ["sardine", "ou", "rosii"],
    storage: "Se consumă imediat.",
  },
  {
    id: "merluciu-fasole-alba",
    name: "Merluciu cu fasole albă și rozmarin",
    emoji: "🫘",
    mealType: "cina",
    time: "25 min",
    age: "12+ luni",
    difficulty: "Ușor",
    servings: "2",
    ingredients: ["150g file de merluciu (fără piele, fără oase)","200g fasole albă fiartă (sau conservă, fără sare)","1 roșie","1 cățel usturoi (mic)","1 lingură ulei de măsline","1 vârf rozmarin"],
    steps: ["Încălzește uleiul. Adaugă usturoiul tocat mărunt, călește 1 minut.","Adaugă roșia tăiată cuburi. Gătește 5 minute.","Adaugă fasolea albă și rozmarinul. Gătește 5 minute.","Verifică merluciul pentru oase. Adaugă-l în tigaie.","Gătește 8-10 minute la foc mic, acoperit.","Fărâmițează merluciul, verifică din nou pentru oase.","Servește cu pâine moale."],
    allergens: ["Pește"],
    relatedFoods: ["merluciu", "fasole-alba", "usturoi"],
    storage: "Se păstrează la frigider 2 zile.",
  },
  {
    id: "somon-legume-wok",
    name: "Somon cu legume sotat rapid",
    emoji: "🥢",
    mealType: "cina",
    time: "20 min",
    age: "12+ luni",
    difficulty: "Ușor",
    servings: "2",
    ingredients: ["150g file de somon (fără piele, fără oase)","1 morcov","½ ardei gras galben","½ zucchini","1 lingură ulei de măsline","1 vârf ghimbir ras (opțional)","zeamă de lămâie"],
    steps: ["Taie toate legumele bețișoare subțiri.","Verifică somonul pentru oase. Taie cuburi de 2cm.","Încălzește uleiul în tigaie la foc mediu-mare.","Sotează legumele 5-7 minute amestecând.","Adaugă somonul. Gătește 5 minute, amestecând ușor.","Fărâmițează somonul cu lingura. Verifică din nou pentru oase.","Adaugă ghimbirul și zeama de lămâie. Servește imediat."],
    allergens: ["Pește"],
    relatedFoods: ["somon", "morcov", "ardei", "zucchini"],
    storage: "Se consumă imediat.",
  },
];
